<?php

/**
 * Localizations for the Kolab SSO plugin
 *
 * Copyright (C) 2018, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_sso/
 */

$labels['loginby'] = 'Login by $provider';
$labels['sso'] = 'Single Sign On';
$labels['errorunknown'] = 'Unknown SSO error.';
$labels['errorinvalidresponse'] = 'Invalid SSO response.';
$labels['errortokenfailed'] = 'Failed to get SSO token.';
$labels['errorivalidtoken'] = 'Invalid SSO token.';
$labels['errorinvalidrequest'] = 'Malformed SSO request.';
$labels['errorunauthorizedclient'] = 'Unauthorized SSO client.';
$labels['errorinvalidclient'] = 'SSO client authentication failed.';
$labels['erroraccessdienied'] = 'SSO request denied.';
$labels['errorunsupportedresponsetype'] = 'Unsupported SSO response type.';
$labels['errorinvalidgrant'] = 'Invalid authorization grant.';
$labels['errorinvalidscope'] = 'Invalid SSO scope.';
$labels['errorservererror'] = 'SSO server error.';
$labels['errortemporarilyunavailable'] = 'SSO service temporarily unavailable.';
$labels['errorinteractionrequired'] = 'User interaction required.';
$labels['errorloginrequired'] = 'User authentication required.';
$labels['erroraccountselectionrequired'] = 'User account selection required.';
$labels['errorconsentrequired'] = 'User consent required.';
$labels['errorinvalidrequesturi'] = 'Invalid request_uri.';
$labels['errorinvalidrequestobject'] = 'Invalid request object';
$labels['errorrequestnotsupported'] = 'Request not supported.';
$labels['errorrequesturinotsupported'] = 'Request_uri parameter not supported.';
$labels['errorregistrationnotsupported'] = 'Registration not supported';
