<?php
/**
 * Localizations for the Kolab SSO plugin
 *
 * Copyright (C) 2018, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_sso/
 */
$labels['loginby'] = 'Kirjautumisen mahdollistaa $provider';
$labels['sso'] = 'Kertakirjautuminen';
$labels['errorunknown'] = 'Tuntematon kertakirjautumisvirhe.';
$labels['errorinvalidresponse'] = 'Virheellinen kertakirjautumisen vastaus.';
$labels['errorinvalidrequest'] = 'Väärinmuodostettu kertakirjautumispyyntö.';
$labels['erroraccessdienied'] = 'Kertakirjautumispyyntö kiellettiin.';
$labels['errorservererror'] = 'Kertakirjautumispalvelimen virhe.';
$labels['errortemporarilyunavailable'] = 'Kertakirjautumispalvelu ei ole juuri nyt käytettävissä.';
$labels['errorinteractionrequired'] = 'Käyttäjän vuorovaikutusta vaaditaan.';
$labels['errorloginrequired'] = 'Käyttäjätunnistautuminen vaaditaan.';
$labels['erroraccountselectionrequired'] = 'Käyttäjätilin valinta vaaditaan.';
$labels['errorconsentrequired'] = 'Käyttäjän hyväksyntä vaaditaan.';
$labels['errorrequestnotsupported'] = 'Pyyntö ei tuettu.';
$labels['errorrequesturinotsupported'] = 'Request_uri-parametri ei tuettu.';
$labels['errorregistrationnotsupported'] = 'Rekisteröinti ei tuettu';
