<?php
/**
 * Localizations for the Kolab SSO plugin
 *
 * Copyright (C) 2018, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_sso/
 */
$labels['loginby'] = 'Zaloguj przez $provider';
$labels['sso'] = 'Jednokrotne Logowanie';
$labels['errorunknown'] = 'Nieznany błąd SSO.';
$labels['errorinvalidresponse'] = 'Błędna odpowiedź SSO.';
$labels['errortokenfailed'] = 'Nie udało się pobrać tokenu SSO.';
$labels['errorivalidtoken'] = 'Błędny token SSO.';
$labels['errorinvalidrequest'] = 'Nieprawidłowe żądanie SSO.';
$labels['errorunauthorizedclient'] = 'Nieupoważniony klient SSO.';
$labels['errorinvalidclient'] = 'Błąd uwierzytelniania SSO.';
$labels['erroraccessdienied'] = 'Odrzucone żądanie SSO.';
$labels['errorunsupportedresponsetype'] = 'Nieobsługiwany typ odpowiedzi SSO.';
$labels['errorinvalidgrant'] = 'Nieprawidłowy grant autoryzacji.';
$labels['errorinvalidscope'] = 'Błędny zakres SSO.';
$labels['errorservererror'] = 'Błąd serwera SSO.';
$labels['errortemporarilyunavailable'] = 'Usługa jednokrotnego logowania tymczasowo niedostępna.';
$labels['errorinteractionrequired'] = 'Wymagana interakcja użytkownika.';
$labels['errorloginrequired'] = 'Wymagane uwierzytelnienie użytkownika.';
$labels['erroraccountselectionrequired'] = 'Wymagany wybór konta użytkownika.';
$labels['errorconsentrequired'] = 'Wymagana zgoda użytkownika.';
$labels['errorinvalidrequesturi'] = 'Błędny request_uri.';
$labels['errorinvalidrequestobject'] = 'Błędny obiekt żądania.';
$labels['errorrequestnotsupported'] = 'Żądanie nie obsługiwane.';
$labels['errorrequesturinotsupported'] = 'Parametr request_uri nie obsługiwany.';
$labels['errorregistrationnotsupported'] = 'Rejestracja nie obsługiwana.';
