<?php
$labels['initials'] = 'Инциали';
$labels['profession'] = 'Професия';
$labels['officelocation'] = 'Офис адрес';
$labels['children'] = 'Деца';
$labels['pgppublickey'] = 'PGP публичен ключ';
$labels['pkcs7publickey'] = 'S/MIME публичен ключ';
$labels['freebusyurl'] = 'Free-busy URL';
$labels['typebusiness'] = 'Работен';
$labels['typebusinessfax'] = 'Работен Факс';
$labels['typecompany'] = 'Компания';
$labels['typeprimary'] = 'Основен';
?>
