<?php
/**
 * Localizations for the Kolab Address Book plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_addressbook/
 */
$labels['initials'] = 'Initialien';
$labels['profession'] = 'Beruf';
$labels['children'] = 'Kinder';
$labels['freebusyurl'] = 'Frei/Beschäftigt-URL';
$labels['typebusiness'] = 'Geschäftlich';
$labels['typebusinessfax'] = 'Fax geschäftlich';
$labels['typecompany'] = 'Firma';
$labels['typeprimary'] = 'Bevorzugt';
$labels['typeisdn'] = 'ISDN';
$labels['settings'] = 'Einstellungen';
$labels['bookcreate'] = 'Adressbuch anlegen';
$labels['bookedit'] = 'Adressbuch bearbeiten';
$labels['bookdelete'] = 'Adressbuch löschen';
$labels['bookremove'] = 'Aus Liste entfernen';
$labels['bookproperties'] = 'Eigenschaften des Adressbuchs';
$labels['bookshowurl'] = 'Zeige CardDAV-URL';
$labels['carddavurldescription'] = 'Kopieren Sie diese Adresse in eine <a href="https://de.wikipedia.org/wiki/CardDAV" target="_blank">CardDAV</a>-Client-Anwendung um dieses Adressbuch mit Ihrem Computer oder Mobilgerät zu synchronisieren.';
$labels['searchterms'] = 'Suchbegriffe';
$labels['listsearchresults'] = 'Zusätzliche Adressbücher';
$labels['nraddressbooksfound'] = '$nr Adressbücher gefunden';
$labels['noaddressbooksfound'] = 'Keine Adressbücher gefunden';
$labels['showhistory'] = 'Historie anzeigen';
$labels['objectchangelog'] = 'Änderungshistorie';
$labels['objectdiff'] = 'Änderungen seit $rev1 bis $rev2';
$labels['revisionrestoreconfirm'] = 'Möchten Sie wirklich den Stand $rev für diesen Kontakt wiederherstellen? Dadurch wird der aktuelle Kontakt durch die alte Version ersetzt.';
$labels['objectchangelognotavailable'] = 'Für diesen Kontakt ist keine Änderungshistorie verfügbar';
$labels['objectdiffnotavailable'] = 'Kein vergleich für die ausgewählten Stände möglich';
$labels['objectrestoresuccess'] = 'Stand $rev erfolgreich wiederhergestellt';
$labels['objectrestoreerror'] = 'Der alte Stand konnte nicht wiederhergestellt werden';
$messages['bookdeleteconfirm']  = 'Möchten Sie das ausgewählte Adressbuch und alle darin enthaltenen Kontakte wirklich löschen?';
$messages['bookdeleting'] = 'Adressbuch wird gelöscht...';
$messages['booksaving'] = 'Adressbuch wird gespeichert...';
$messages['bookdeleted'] = 'Adressbuch erfolgreich gelöscht.';
$messages['bookupdated'] = 'Adressbuch erfolgreich aktualisiert.';
$messages['bookcreated'] = 'Adressbuch erfolgreich angelegt.';
$messages['bookdeleteerror'] = 'Beim Löschen des Adressbuchs ist ein Fehler aufgetreten.';
$messages['bookupdateerror'] = 'Bei der Aktualisierung des Adressbuchs ist ein Fehler aufgetreten.';
$messages['bookcreateerror'] = 'Beim Anlegen des Adressbuchs ist ein Fehler aufgetreten.';
$messages['nobooknamewarning'] = 'Bitte geben Sie den Namen des Adressbuchs ein.';
?>
