<?php
/**
 * Localizations for the Kolab Address Book plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_addressbook/
 */
$labels['initials'] = 'Initsiaalid';
$labels['profession'] = 'Eriala';
$labels['officelocation'] = 'Kontori asukoht';
$labels['children'] = 'Lapsed';
$labels['pgppublickey'] = 'PGP avalik võti';
$labels['pkcs7publickey'] = 'S/MIME avalik võti';
$labels['freebusyurl'] = 'Vaba-Hõivatud URL';
$labels['typebusiness'] = 'Ettevõte';
$labels['typebusinessfax'] = 'Ettevõtte faks';
$labels['typecompany'] = 'Ettevõte';
$labels['typeprimary'] = 'Peamine';
$labels['typetelex'] = 'Telex';
$labels['typeradio'] = 'Radio';
$labels['typeisdn'] = 'ISDN';
$labels['typettytdd'] = 'TTY/TDD';
$labels['typecallback'] = 'Tagasihelistamine';
$labels['settings'] = 'Seaded';
$labels['bookcreate'] = 'Loo aadressiraamat';
$labels['bookedit'] = 'Muuda aadressiraamatut';
$labels['bookdelete'] = 'Kustuta aadressiraamat';
$labels['bookremove'] = 'Eemalda nimekirjast';
$labels['bookproperties'] = 'Aadressiraamatu omadused';
$labels['bookname'] = 'Raamatu nimi';
$labels['parentbook'] = 'Peamine raamat';
$labels['bookshowurl'] = 'Näita CardDAV URL-i';
$labels['showhistory'] = 'Näita ajalugu';
$labels['objectchangelog'] = 'Muuda ajalugu';
$labels['objectdiff'] = 'Muudatused versioonide $rev1 ja $rev2 vahel';
$messages['bookdeleting'] = 'Aadressiraamatu kustutamine...';
$messages['booksaving'] = 'Aadressiraamatu salvestamine...';
$messages['bookdeleted'] = 'Aadressiraamat on kustutatud.';
$messages['bookupdated'] = 'Aadressiraamatut on uuendatud.';
$messages['bookcreated'] = 'Aadressiraamat on loodud.';
$messages['nobooknamewarning'] = 'Palun sisesta aadressiraamatu nimi.';
$messages['noemailnamewarning'] = 'Palun sisesta e-posti aadress või kontakti nimi.';
?>
