<?php
/**
 * Localizations for the Kolab Address Book plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_addressbook/
 */
$labels['initials'] = 'イニシャル';
$labels['profession'] = '職業';
$labels['officelocation'] = '会社所在';
$labels['children'] = '子供';
$labels['pgppublickey'] = 'PGP パブリックキー';
$labels['pkcs7publickey'] = 'S/MIME パブリックキー';
$labels['freebusyurl'] = '空き状況 URL';
$labels['typebusiness'] = '仕事';
$labels['typebusinessfax'] = '仕事 Fax';
$labels['typecompany'] = '会社名';
$labels['typeprimary'] = '代表';
$labels['typetelex'] = 'テレックス';
$labels['typeradio'] = 'ラジオ';
$labels['typeisdn'] = 'ISDN';
$labels['typettytdd'] = 'TTY/TDD';
$labels['typecallback'] = 'コールバック';
$labels['settings'] = '設定';
$labels['bookcreate'] = 'アドレス帳作成';
$labels['bookedit'] = 'アドレス帳編集';
$labels['bookdelete'] = 'アドレス帳削除';
$labels['bookremove'] = 'Remove from list';
$labels['bookproperties'] = 'アドレス帳設定';
$labels['bookname'] = 'ブック名';
$labels['parentbook'] = '上位ブック';
$labels['addressbookprio'] = 'アドレス帳(s)セレクション/動作';
$labels['personalfirst'] = '個人アドレス帳(s) を前に';
$labels['globalfirst'] = 'グローバルアドレス帳(s) を前に';
$labels['personalonly'] = '個人アドレス帳(s) のみ';
$labels['globalonly'] = 'グローバルアドレス帳(s) のみ';
$labels['searchterms'] = 'Search terms';
$labels['foldersubscribe'] = 'List permanently';
$messages['bookdeleteconfirm']  = '本当に選択したアドレス帳およびそのデータをすべて削除しますか?';
$messages['bookdeleting'] = 'アドレス帳を削除中...';
$messages['booksaving'] = 'アドレス帳を保存中…';
$messages['bookdeleted'] = 'アドレス帳を削除しました。';
$messages['bookupdated'] = 'アドレス帳を更新しました。';
$messages['bookcreated'] = 'アドレス帳を作成しました。';
$messages['bookdeleteerror'] = 'アドレス帳の削除中にエラーが発生しました。';
$messages['bookupdateerror'] = 'アドレス帳の更新中にエラーが発生しました。';
$messages['bookcreateerror'] = 'アドレス帳の作成中にエラーが発生しました。';
$messages['nobooknamewarning'] = 'アドレス帳名を入力してください。';
$messages['noemailnamewarning'] = 'Emailアドレスまたはコンタクト名を入力してください。';
?>
