<?php
/**
 * Localizations for the Kolab Address Book plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_addressbook/
 */
$labels['bookremove'] = 'Usuń z listy';
$labels['searchterms'] = 'Szukana fraza';
$labels['foldersubscribe'] = 'Dodaj do listy na stałe';
$labels['objectchangelog'] = 'Historia zmian';
$labels['objectdiffnotavailable'] = 'Nie można porównać wybranych wersji';
?>
