<?php
/**
 * Localizations for the Kolab Address Book plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_addressbook/
 */
$labels['initials'] = 'Inicjały';
$labels['profession'] = 'Zawód';
$labels['officelocation'] = 'Biuro';
$labels['children'] = 'Dzieci';
$labels['pgppublickey'] = 'Klucz publiczny PGP';
$labels['pkcs7publickey'] = 'Klucz publiczny S/MIME';
$labels['freebusyurl'] = 'Adres URL free-busy';
$labels['typebusiness'] = 'Firmowy';
$labels['typebusinessfax'] = 'Fax firmowy';
$labels['typecompany'] = 'Firma';
$labels['typeprimary'] = 'Główny';
$labels['typetelex'] = 'Teleks';
$labels['typeradio'] = 'Radiowy';
$labels['typeisdn'] = 'ISDN';
$labels['typettytdd'] = 'TTY/TDD';
$labels['typecallback'] = 'Callback';
$labels['settings'] = 'Ustawienia';
$labels['bookcreate'] = 'Utwórz książkę adresową';
$labels['bookedit'] = 'Edytuj książkę adresową';
$labels['bookdelete'] = 'Usuń książkę adresową';
$labels['bookremove'] = 'Usuń z listy';
$labels['bookproperties'] = 'Właściwości książki adresowej';
$labels['bookname'] = 'Nazwa książki';
$labels['parentbook'] = 'Nadrzędna książka';
$labels['bookshowurl'] = 'Pokaż adres URL CardDAV';
$labels['carddavurldescription'] = 'Skopiuj ten adres do aplikacji obsługującej format <a href="http://en.wikipedia.org/wiki/CardDAV" target="_blank">CardDAV</a> aby zsynchronizować książkę adresową z twoim komputerem lub urządzeniem przenośnym.';
$labels['addressbookprio'] = 'Wybór/zachowanie książek adresowych';
$labels['personalfirst'] = 'najpierw prywatne książki adresowe';
$labels['globalfirst'] = 'najpierw globalne książki adresowe';
$labels['personalonly'] = 'tylko prywatne książki adresowe';
$labels['globalonly'] = 'tylko globalne książki adresowe';
$labels['searchterms'] = 'Szukana fraza';
$labels['listsearchresults'] = 'Dodatkowe książki adresowe';
$labels['foldersearchform'] = 'Formularz wyszukiwania książek adresowych';
$labels['foldersubscribe'] = 'Dodaj do listy na stałe';
$labels['nraddressbooksfound'] = 'znaleziono $nr książkek adresowych';
$labels['noaddressbooksfound'] = 'Nie znaleziono żadnych książek adresowych';
$labels['showhistory'] = 'Pokaż Historię';
$labels['objectchangelog'] = 'Historia zmian';
$labels['objectdiff'] = 'Zmiany od $rev1 do $rev2';
$labels['revisionrestoreconfirm'] = 'Czy na pewno chcesz przywrócić rewizję $rev tego kontaktu? Starsza wersja nadpisze obecną.';
$labels['objectnotfound'] = 'Błąd pobierania danych kontaktu';
$labels['objectchangelognotavailable'] = 'Historia zmian nie jest dostępna dla tego kontaktu';
$labels['objectdiffnotavailable'] = 'Nie można porównać wybranych wersji';
$labels['objectrestoresuccess'] = 'Wersja $rev poprawnie przywrócona';
$labels['objectrestoreerror'] = 'Błąd przywracania starej wersji';
$messages['bookdeleteconfirm']  = 'Czy na pewno chcesz usunąć wybraną książkę i wszystkie kontakty?';
$messages['bookdeleting'] = 'Usuwanie książki adresowej...';
$messages['booksaving'] = 'Zapisywanie książki adresowej...';
$messages['bookdeleted'] = 'Książka adresowa została usunięta.';
$messages['bookupdated'] = 'Książka adresowa została zaktualizowana.';
$messages['bookcreated'] = 'Książka adresowa została utworzona.';
$messages['bookdeleteerror'] = 'Podczas usuwania książki adresowej wystąpił błąd.';
$messages['bookupdateerror'] = 'Podczas zapisywania książki adresowej wystąpił błąd.';
$messages['bookcreateerror'] = 'Podczas dodawania książki adresowej wystąpił błąd.';
$messages['nobooknamewarning'] = 'Proszę podać nazwę książki adresowej.';
$messages['noemailnamewarning'] = 'Proszę podać adres email lub nazwę kontaktu.';
?>
