<?php
/**
 * Localizations for the Kolab Address Book plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_addressbook/
 */
$labels['bookremove'] = 'Remove from list';
$labels['searchterms'] = 'Search terms';
$labels['foldersubscribe'] = 'Listar permanentemente';
$labels['objectchangelog'] = 'Alterar histórico';
$labels['objectdiff'] = 'Diferenças entre $rev1 e $rev2';
$labels['objectdiffnotavailable'] = 'Não é possível comparar as versões selecionadas';
$labels['objectrestoresuccess'] = 'A versão $rev foi reposta com sucesso.';
$labels['objectrestoreerror'] = 'Não foi possível repor a versão anterior.';
?>
