<?php
/**
 * Localizations for the Kolab Address Book plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_addressbook/
 */
$labels['initials'] = 'Initialer';
$labels['profession'] = 'Yrke';
$labels['officelocation'] = 'Kontorsadress';
$labels['children'] = 'Barn';
$labels['pgppublickey'] = 'Publik PGP-nyckel';
$labels['pkcs7publickey'] = 'Publik S/MIME-nyckel';
$labels['freebusyurl'] = 'Ledig-upptagen-URL';
$labels['typebusiness'] = 'Företag';
$labels['typebusinessfax'] = 'Företagsfax';
$labels['typecompany'] = 'Företag';
$labels['typeprimary'] = 'Primär';
$labels['typetelex'] = 'Telex';
$labels['typeradio'] = 'Radio';
$labels['typeisdn'] = 'ISDN';
$labels['typettytdd'] = 'TTY/TDD';
$labels['typecallback'] = 'Återuppringning';
$labels['settings'] = 'Inställningar';
$labels['bookcreate'] = 'Skapa adressbok';
$labels['bookedit'] = 'Redigera adressbok';
$labels['bookdelete'] = 'Ta bort adressbok';
$labels['bookremove'] = 'Ta bort från lista';
$labels['bookproperties'] = 'Egenskaper för adressbok';
$labels['bookname'] = 'Bokens namn';
$labels['parentbook'] = 'Överordnad bok';
$labels['bookshowurl'] = 'Visa CardDAV-URL';
$labels['carddavurldescription'] = 'Kopiera denna adress till ett <a href="http://en.wikipedia.org/wiki/CardDAV" target="_blank"> CardDAV</a>-klientprogram för att fullt ut synkronisera denna specifika adressbok med din dator eller mobila enhet .';
$labels['addressbookprio'] = 'Val/beteenden för adressbok(böcker) ';
$labels['personalfirst'] = 'Personliga adressböcker först';
$labels['globalfirst'] = 'Globala adressböcker först';
$labels['personalonly'] = 'Personliga adressböcker enbart';
$labels['globalonly'] = 'Globala adressböcker enbart';
$labels['searchterms'] = 'Sökord';
$labels['listsearchresults'] = 'Ytterligare adressböcker';
$labels['foldersearchform'] = 'Sökformulär för adressböcker';
$labels['foldersubscribe'] = 'Lista permanent';
$labels['nraddressbooksfound'] = '$nr adressböcker hittades';
$labels['noaddressbooksfound'] = 'Inga adressböcker hittades';
$labels['showhistory'] = 'Visa historik';
$labels['objectchangelog'] = 'Ändringshistorik';
$labels['objectdiff'] = 'Ändringar från $rev1 till $rev2';
$labels['revisionrestoreconfirm'] = 'Vill du verkligen vill återställa version $rev av denna kontakt? Detta kommer att ersätta nuvarande kontakt med den gamla versionen.';
$labels['objectnotfound'] = 'Det gick ej att läsa in kontaktdata';
$labels['objectchangelognotavailable'] = 'Att ändra i historiken är inte möjligt för denna kontakt';
$labels['objectdiffnotavailable'] = 'Ingen jämförelse möjlig för valda revisioner';
$labels['objectrestoresuccess'] = 'Version $rev har återställts ';
$labels['objectrestoreerror'] = 'Det gick inte att återställa den gamla versionen';
$messages['bookdeleteconfirm']  = 'Vill du verkligen ta bort den valda adressboken och alla kontakter i den?';
$messages['bookdeleting'] = 'Tar bort adressbok ...';
$messages['booksaving'] = 'Sparar adressbok ...';
$messages['bookdeleted'] = 'Adressbok borttagen.';
$messages['bookupdated'] = 'Adressbok uppdaterad.';
$messages['bookcreated'] = 'Adressbok skapad.';
$messages['bookdeleteerror'] = 'Ett fel uppstod vid borttagning av adressbok.';
$messages['bookupdateerror'] = 'Ett fel uppstod vid uppdatering av adressbok.';
$messages['bookcreateerror'] = 'Ett fel uppstod vid skapandet av adressbok.';
$messages['nobooknamewarning'] = 'Vänligen ange adressbokens namn.';
$messages['noemailnamewarning'] = 'Vänligen ange e-postadress eller kontaktnamn.';
?>
