<?php
/**
 * Localizations for the Kolab Delegation plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_delegation/
 */
$labels['mail'] = 'E-mail';
$labels['contact'] = 'Adresáře';
$labels['event'] = 'Kalendáře';
$labels['task'] = 'Úkoly';
$labels['note'] = 'Poznámky';
$labels['yes'] = 'Ano';
$labels['savingdata'] = 'Ukládám data...';
?>
