<?php
$labels['delegates'] = 'Delegierte';
$labels['mail'] = 'E-Mail';
$labels['contact'] = 'Kontakte';
$labels['event'] = 'Kalender';
$labels['task'] = 'Aufgaben';
$labels['note'] = 'Notizen';
$labels['yes'] = 'Ja';
$labels['no'] = 'Nein';
$labels['read'] = 'Schreibgeschützt';
$labels['write'] = 'Schreiben';
$labels['savingdata'] = 'Speichere Daten...';
$labels['deleteconfirm'] = 'Bestätigung';
?>
