<?php
/**
 * Localizations for the Kolab Delegation plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_delegation/
 */
$labels['delegates'] = 'Vertreter';
$labels['mail'] = 'E-Mail';
$labels['contact'] = 'Kontakte';
$labels['event'] = 'Kalender';
$labels['task'] = 'Aufgaben';
$labels['note'] = 'Notizen';
$labels['yes'] = 'Ja';
$labels['no'] = 'Nein';
$labels['savingdata'] = 'Daten werden gespeichert...';
?>
