<?php
/**
 * Localizations for the Kolab Delegation plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_delegation/
 */
$labels['delegates'] = 'Delegados';
$labels['mail'] = 'Correo electrónico';
$labels['contact'] = 'Libreta de direcciones';
$labels['event'] = 'Calendarios';
$labels['task'] = 'Tareas';
$labels['note'] = 'Notas';
$labels['yes'] = 'Sí';
$labels['no'] = 'No';
$labels['read'] = 'Solo-lectura';
$labels['savingdata'] = 'Guardando datos...';
?>
