<?php
/**
 * Localizations for the Kolab Delegation plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_delegation/
 */
$labels['delegates'] = 'Delegaadid';
$labels['delegate'] = 'Delegeeri';
$labels['mail'] = 'E-post';
$labels['contact'] = 'Kontaktid';
$labels['event'] = 'Kalendrid';
$labels['task'] = 'Ülesanded';
$labels['note'] = 'Märkmed';
$labels['yes'] = 'Jah';
$labels['no'] = 'Ei';
$labels['read'] = 'Ainult loetav';
$labels['write'] = 'Kirjuta';
$labels['savingdata'] = 'Andmete salvestamine...';
$labels['deleteconfirm'] = 'Kinnitamine';
?>
