<?php
/**
 * Localizations for the Kolab Delegation plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_delegation/
 */
$labels['tabtitle'] = 'Délégation';
$labels['delegationtitle'] = 'Gérer mainteneurs';
$labels['delegates'] = 'Délégation';
$labels['delegate'] = 'Déléguer';
$labels['mail'] = 'Adresse de messagerie';
$labels['contact'] = 'Carnet d\'adresse';
$labels['event'] = 'Calendriers';
$labels['task'] = 'Tâches';
$labels['note'] = 'Notes';
$labels['yes'] = 'Oui';
$labels['no'] = 'Non';
$labels['read'] = 'Lecture Seule';
$labels['write'] = 'Écriture';
$labels['adddelegate'] = 'Ajouter une délégation';
$labels['deletedelegate'] = 'Supprimer une délégation';
$labels['savingdata'] = 'Enregistrer...';
$labels['delegatedeleteconfirm'] = 'Voulez-vous vraiment supprimer cette délégation?';
$labels['delegateremoveacl'] = 'Supprimer les droits d\'accès aux dossiers affectés à cet utilisateur';
$labels['deleteconfirm'] = 'Confirmation';
$labels['deletesuccess'] = 'La délégation a été supprimée';
$labels['deleteerror'] = 'La délégation n\'a pas pu être supprimée';
$labels['updatesuccess'] = 'La délégation a été mise à jour';
$labels['updateerror'] = 'La délégation n\'a pas pu être mise à jour';
$labels['createsuccess'] = 'La délégation a été ajoutée';
$labels['createerror'] = 'La délégation n\'a pas pu être ajoutée';
$labels['arialabeldelegatedelete'] = 'Dialog de suppression du mainteneur';
$labels['arialabeldelegateform'] = 'Formulaire de propriétés du mainteneur';
?>
