<?php
$labels['tabtitle'] = '委任';
$labels['delegates'] = '委任者';
$labels['delegate'] = '委任者';
$labels['mail'] = 'Email';
$labels['contact'] = 'アドレス帳';
$labels['event'] = 'カレンダー';
$labels['task'] = 'タスク';
$labels['note'] = 'ノート';
$labels['yes'] = 'はい';
$labels['no'] = 'いいえ';
$labels['adddelegate'] = '委任者を追加';
$labels['deletedelegate'] = '委任者を削除';
$labels['savingdata'] = 'データを保存中…';
$labels['delegatedeleteconfirm'] = 'この委任者を本当に削除しますか？';
$labels['delegateremoveacl'] = 'このユーザにアサインされたフォルダのアクセス権を削除しました';
$labels['deleteconfirm'] = '確認';
$labels['deletesuccess'] = '委任者の削除に成功しました';
$labels['deleteerror'] = '委任者の削除ができません。';
$labels['updatesuccess'] = '委任者の更新に成功しました。';
$labels['updateerror'] = '委任者の更新ができません。';
$labels['createsuccess'] = '委任者の追加に成功しました。';
$labels['createerror'] = '委任者の追加ができません。';
?>
