<?php
/**
 * Localizations for the Kolab Delegation plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_delegation/
 */
$labels['tabtitle'] = 'Delegatie';
$labels['delegationtitle'] = 'Manage delegates';
$labels['delegates'] = 'Gedelegeerden';
$labels['delegate'] = 'Gedelegeerde';
$labels['mail'] = 'Email';
$labels['contact'] = 'Adresboeken';
$labels['event'] = 'Kalenders';
$labels['task'] = 'Taken';
$labels['note'] = 'Notities';
$labels['yes'] = 'Ja';
$labels['no'] = 'Nee';
$labels['read'] = 'Alleen-lezen';
$labels['write'] = 'Schrijven';
$labels['adddelegate'] = 'Gedelegeerde toevoegen';
$labels['deletedelegate'] = 'Gedelegeerde verwijderen';
$labels['savingdata'] = 'Data wordt opgeslagen...';
$labels['delegatedeleteconfirm'] = 'Wilt u deze gedelegeerde echt verwijderen?';
$labels['delegateremoveacl'] = 'verwijder toegangsrechten op mappen toegewezen aan deze gebruiker';
$labels['deleteconfirm'] = 'Bevestiging';
$labels['deletesuccess'] = 'De gedelegeerde is succesvol verwijderd.';
$labels['deleteerror'] = 'De gedelegeerde kon niet worden verwijderd.';
$labels['updatesuccess'] = 'De gedelegeerde is succesvol gewijzigd.';
$labels['updateerror'] = 'De gedelegeerde kon niet worden gewijzigd.';
$labels['createsuccess'] = 'De gedelegeerde is succesvol toegevoegd.';
$labels['createerror'] = 'De gedelegeerde kon niet worden toegevoegd.';
$labels['arialabeldelegatedelete'] = 'Delegate deletion dialog';
$labels['arialabeldelegateform'] = 'Delegate properties form';
?>
