<?php
$labels['tabtitle'] = 'Pełnomocnictwa';
$labels['delegates'] = 'Wydelegowani';
$labels['delegate'] = 'Pełnomocnik';
$labels['mail'] = 'Poczta';
$labels['contact'] = 'Książki adresowe';
$labels['event'] = 'Kalendarze';
$labels['task'] = 'Zadania';
$labels['note'] = 'Notatki';
$labels['yes'] = 'Tak';
$labels['no'] = 'Nie';
$labels['read'] = 'Tylko-do-odczytu';
$labels['write'] = 'Zapis';
$labels['adddelegate'] = 'Dodaj delegata';
$labels['deletedelegate'] = 'Usuń delegata';
$labels['savingdata'] = 'Zapisuję dane...';
$labels['delegatedeleteconfirm'] = 'Czy na pewno chcesz usunąć tego delegata?';
$labels['delegateremoveacl'] = 'usuń prawa dostępu do folderów przypisanych do tego użytkownika';
$labels['deleteconfirm'] = 'Potwierdzenie';
$labels['deletesuccess'] = 'Delegat został usunięty.';
$labels['deleteerror'] = 'Nie można usunąć delegata.';
$labels['updatesuccess'] = 'Delegat został zaktualizowany.';
$labels['updateerror'] = 'Nie można zaktualizować delegata.';
$labels['createsuccess'] = 'Delegat został dodany.';
$labels['createerror'] = 'Nie można dodać delegata.';
?>
