<?php
/**
 * Localizations for the Kolab Delegation plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_delegation/
 */
$labels['tabtitle'] = 'Delegering';
$labels['delegationtitle'] = 'Hantera ombud';
$labels['delegates'] = 'Ombud';
$labels['delegate'] = 'Delegera';
$labels['mail'] = 'E-post';
$labels['contact'] = 'Kontakter';
$labels['event'] = 'Kalendrar';
$labels['task'] = 'Uppgifter';
$labels['note'] = 'Anteckningar';
$labels['yes'] = 'Ja';
$labels['no'] = 'Nej';
$labels['read'] = 'Endast läsbar';
$labels['write'] = 'Skriv';
$labels['adddelegate'] = 'Lägg till ombud';
$labels['deletedelegate'] = 'Ta bort ombud';
$labels['savingdata'] = 'Sparar data ...';
$labels['delegatedeleteconfirm'] = 'Vill du verkligen ta bort detta ombud?';
$labels['delegateremoveacl'] = 'ta bort åtkomsträttigheter för mappar som tilldelats denna användare';
$labels['deleteconfirm'] = 'Bekräftelse';
$labels['deletesuccess'] = 'Ombudet togs bort.';
$labels['deleteerror'] = 'Ombudet kunde inte tas bort.';
$labels['updatesuccess'] = 'Detta ombud uppdaterades.';
$labels['updateerror'] = 'Ombudet kunde inte uppdateras.';
$labels['createsuccess'] = 'Ombudet lades till.';
$labels['createerror'] = 'Ombudet kunde inte läggas till.';
$labels['arialabeldelegatedelete'] = 'Borttagningsdialog för ombud';
$labels['arialabeldelegateform'] = 'Egenskapsformulär för ombud';
?>
