<?php
/**
 * Localizations for the Kolab Delegation plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_delegation/
 */
$labels['mail'] = 'E-post';
$labels['event'] = 'Kalendrar';
$labels['task'] = 'Uppgifter';
$labels['note'] = 'Anteckningar';
$labels['write'] = 'Skriv';
$labels['savingdata'] = 'Sparar data ...';
?>
