<?php
$labels['navtitle'] = 'Задачи';
$labels['edit'] = 'Промяна';
$labels['description'] = 'Описание';
$labels['start'] = 'Начало';
$labels['alarms'] = 'Напомняне';
$labels['today'] = 'Днес';
$labels['tomorrow'] = 'Утре';
$labels['removetag'] = 'Изтриване';
$labels['save'] = 'Запис';
$labels['cancel'] = 'Отказ';
$labels['tabsummary'] = 'Заглавие';
$labels['listname'] = 'Име';
$labels['showalarms'] = 'Показване на аларми';
$labels['savingdata'] = 'Запазване на данни...';
