<?php
/**
 * Localizations for the Kolab Tasks plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/tasklist/
 */
$labels['navtitle'] = 'Задачи';
$labels['edit'] = 'Промяна';
$labels['description'] = 'Описание';
$labels['start'] = 'Начало';
$labels['alarms'] = 'Напомняне';
$labels['repeat'] = 'Repeat';
$labels['status'] = 'Статус';
$labels['all'] = 'All';
$labels['today'] = 'Днес';
$labels['tomorrow'] = 'Утре';
$labels['removetag'] = 'Изтриване';
$labels['save'] = 'Запис';
$labels['cancel'] = 'Отказ';
$labels['tabsummary'] = 'Заглавие';
$labels['tabrecurrence'] = 'Recurrence';
$labels['tabattachments'] = 'Прикрепени файлове';
$labels['tabsharing'] = 'Споделяне';
$labels['listname'] = 'Име';
$labels['showalarms'] = 'Show reminders';
$labels['savingdata'] = 'Запазване на данни...';
$labels['role'] = 'Роля';
$labels['availability'] = 'Avail.';
$labels['confirmstate'] = 'Статус';
$labels['roleorganizer'] = 'Организатор';
$labels['rolerequired'] = 'Задължителен';
$labels['roleoptional'] = 'По избор';
$labels['rolechair'] = 'Chair';
$labels['sendinvitations'] = 'Изпращане на покани';
$labels['itipupdatesubject'] = '"$title" has been updated';
$labels['itipcancelsubject'] = '"$title" has been canceled';
$labels['andnmore'] = '$nr повече...';
$labels['attendeupdateesuccess'] = 'Successfully updated the participant\'s status';
$labels['itipinvalidrequest'] = 'This invitation is no longer valid';
