<?php
/**
 * Localizations for the Kolab Tasks plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/tasklist/
 */
$labels['edit'] = 'Edita';
$labels['description'] = 'Descripció';
$labels['start'] = 'Inici';
$labels['alarms'] = 'Recordatori';
$labels['removetag'] = 'Suprimeix';
$labels['save'] = 'Desa';
$labels['cancel'] = 'Cancel·la';
$labels['tabsummary'] = 'Resum';
$labels['listname'] = 'Nom';
