<?php
$labels['edit'] = 'Upravit';
$labels['description'] = 'Popis';
$labels['start'] = 'Začátek';
$labels['alarms'] = 'Připomenutí';
$labels['all'] = 'Všechny';
$labels['today'] = 'Dnes';
$labels['tomorrow'] = 'Zítra';
$labels['removetag'] = 'Odstranit';
$labels['save'] = 'Uložit';
$labels['cancel'] = 'Storno';
$labels['tabsummary'] = 'Souhrn';
$labels['tabrecurrence'] = 'Opakování';
$labels['tabattachments'] = 'Přílohy';
$labels['tabsharing'] = 'Sdílení';
$labels['listname'] = 'Název';
$labels['showalarms'] = 'Zobrazit upozornění';
$labels['savingdata'] = 'Ukládám data...';
