<?php
/**
 * Localizations for the Kolab Tasks plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/tasklist/
 */
$labels['edit'] = 'Upravit';
$labels['description'] = 'Popis';
$labels['start'] = 'Začátek';
$labels['alarms'] = 'Připomenutí';
$labels['repeat'] = 'Opakovat';
$labels['status'] = 'Stav';
$labels['all'] = 'Všechny';
$labels['today'] = 'Dnes';
$labels['tomorrow'] = 'Zítra';
$labels['removetag'] = 'Odstranit';
$labels['save'] = 'Uložit';
$labels['cancel'] = 'Storno';
$labels['tabsummary'] = 'Souhrn';
$labels['tabrecurrence'] = 'Opakování';
$labels['tabattachments'] = 'Přílohy';
$labels['tabsharing'] = 'Sdílení';
$labels['listname'] = 'Název';
$labels['showalarms'] = 'Show reminders';
$labels['savingdata'] = 'Ukládám data...';
$labels['role'] = 'Role';
$labels['availability'] = 'Dost.';
$labels['confirmstate'] = 'Stav';
$labels['roleorganizer'] = 'Organizátor';
$labels['rolerequired'] = 'Povinný';
$labels['roleoptional'] = 'Nepovinný';
$labels['rolechair'] = 'Chair';
$labels['sendinvitations'] = 'Poslat pozvánky';
$labels['itipupdatesubject'] = 'Událost "$title" byla aktualizována';
$labels['itipcancelsubject'] = 'Událost "$title" byla zrušena';
$labels['andnmore'] = 'dalších $nr...';
$labels['attendeupdateesuccess'] = 'Stav účastníka byl úspěšně aktualizován';
$labels['itipinvalidrequest'] = 'Tato pozvánka již není platná';
