<?php
/**
 * Localizations for the Kolab Tasks plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/tasklist/
 */
$labels['navtitle'] = 'Opgaver';
$labels['lists'] = 'Opgavelister';
$labels['list'] = 'Opgaveliste';
$labels['tags'] = 'Mærker';
$labels['newtask'] = 'Ny opgave';
$labels['createnewtask'] = 'Opret ny opgave (eks. Lørdag, Slå græsplænen)';
$labels['createfrommail'] = 'Gem som opgave';
$labels['mark'] = 'Markér';
$labels['unmark'] = 'Fravælg';
$labels['edit'] = 'Redigér';
$labels['delete'] = 'Slet';
$labels['title'] = 'Titel';
$labels['description'] = 'Beskrivelse';
$labels['datetime'] = 'Forfalder';
$labels['start'] = 'Start';
$labels['alarms'] = 'Påmindelse';
$labels['repeat'] = 'Gentag';
$labels['status'] = 'Status';
$labels['status-cancelled'] = 'Annulleret';
$labels['all'] = 'Alle';
$labels['flagged'] = 'Markeret';
$labels['complete'] = 'Udført';
$labels['overdue'] = 'Forfalden';
$labels['today'] = 'I dag';
$labels['tomorrow'] = 'I morgen';
$labels['next7days'] = 'Næste 7 dage';
$labels['later'] = 'Senere';
$labels['nodate'] = 'ingen dato';
$labels['removetag'] = 'Fjern';
$labels['taskdetails'] = 'Detaljer';
$labels['newtask'] = 'Ny opgave';
$labels['edittask'] = 'Redigér opgave';
$labels['save'] = 'Gem';
$labels['cancel'] = 'Annullér';
$labels['addsubtask'] = 'Tilføj delopgave';
$labels['deletetask'] = 'Slet opgave';
$labels['deletethisonly'] = 'Slet kunne denne opgave';
$labels['deletewithchilds'] = 'Slette inklusive alle delopgaver';
$labels['tabsummary'] = 'Resumé';
$labels['tabrecurrence'] = 'Gentagelse';
$labels['tabattachments'] = 'Vedhæftninger';
$labels['tabsharing'] = 'Deling';
$labels['editlist'] = 'Redigér liste';
$labels['createlist'] = 'Tilføj liste';
$labels['listactions'] = 'Tilvalg for liste...';
$labels['listname'] = 'Navn';
$labels['import'] = 'Import';
$labels['focusview'] = 'Vis kun denne liste';
$labels['on'] = 'til';
$labels['at'] = 'ved';
$labels['this'] = 'denne';
$labels['next'] = 'næste';
$labels['savingdata'] = 'Gemmer data...';
$labels['errorsaving'] = 'Kunne ikke gemme data.';
$labels['notasksfound'] = 'Fandt ingen opgaver ud fra angivne kriterie';
$labels['invalidstartduedates'] = 'Startdato må ikke være senere end tidsfrist.';
$labels['deletetasktconfirm'] = 'Vil du virkelig slette denne opgave?';
$labels['deleteparenttasktconfirm'] = 'Vil du virkelig slette denne opgaver og alle dens delopgaver?';
$labels['deletelistconfirm'] = 'Vil du virkelig slette denne liste og alle dens opgaver?';
$labels['deletelistconfirmrecursive'] = 'Vil du virkelig slette denne liste og alle dens dellister og opgaver?';
$labels['role'] = 'Rolle';
$labels['availability'] = 'Tilg.';
$labels['confirmstate'] = 'Status';
$labels['roleorganizer'] = 'Organisator';
$labels['rolerequired'] = 'Påkrævet';
$labels['roleoptional'] = 'Valgfri';
$labels['rolechair'] = 'Formand';
$labels['sendinvitations'] = 'Send invitationer';
$labels['itipupdatesubject'] = '"$title" er blevet opdateret';
$labels['itipcancelsubject'] = '"$title" er blevet aflyst';
$labels['andnmore'] = '$nr flere...';
$labels['attendeupdateesuccess'] = 'Opdatering af deltagernes status blev gennemført';
$labels['itipinvalidrequest'] = 'Denne invitation er ikke længere gyldig';
