<?php

/**
 * Localizations for the Kolab Tasks plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/tasklist/
 */

$labels = array();
$labels['navtitle'] = 'Aufgaben';
$labels['lists'] = 'Aufgabenlisten';
$labels['list'] = 'Aufgabenliste';
$labels['tags'] = 'Schlagworte';
$labels['tasklistsubscribe'] = 'Permanent anzeigen';
$labels['listsearchresults'] = 'Verfügbare Aufgaben';
$labels['findlists'] = 'Finde Aufgabenlisten,..';
$labels['searchterms'] = 'Suchbegriffe';
$labels['notasklistsfound'] = 'Keine Aufgabenlisten gefunden';
$labels['nrtasklistsfound'] = '$nr Aufgabenlisten gefunden';
$labels['removelist'] = 'Von der Liste entfernen';

$labels['newtask'] = 'Neue Aufgabe';
$labels['createtask'] = 'Aufgabe erstellen <Enter>';
$labels['createnewtask'] = 'Neue Aufgabe erstellen (z.B. Samstag, Rasen mähen)';
$labels['createfrommail'] = 'Aufgabe speichern';
$labels['mark'] = 'Markieren';
$labels['unmark'] = 'Markierung entfernen';
$labels['edit'] = 'Bearbeiten';
$labels['delete'] = 'Löschen';
$labels['title'] = 'Titel';
$labels['description'] = 'Beschreibung';
$labels['datetime'] = 'Fällig';
$labels['duetime'] = 'Frist';
$labels['start'] = 'Beginn';
$labels['starttime'] = 'Startzeit';
$labels['alarms'] = 'Erinnerung';
$labels['repeat'] = 'Wiederholung';
$labels['links'] = 'Reference';
$labels['status'] = 'Status';
$labels['status-needs-action'] = 'Braucht Aktion';
$labels['status-in-process'] = 'In Bearbeitung';
$labels['status-completed'] = 'Erledigt';
$labels['status-cancelled'] = 'Gekündigt';
$labels['assignedto'] = 'Zugewiesen an';
$labels['created'] = 'Erstellt';
$labels['changed'] = 'Geändert';

$labels['all'] = 'Alle';
$labels['flagged'] = 'Markiert';
$labels['complete'] = 'Abgeschlossen';
$labels['completeness'] = 'Fortschritt';
$labels['overdue'] = 'Überfällig';
$labels['today'] = 'Heute';
$labels['tomorrow'] = 'Morgen';
$labels['next7days'] = 'Innerhalb von 7 Tagen';
$labels['later'] = 'Später';
$labels['assigned'] = 'Zugewiesen';
$labels['assignedtitle'] = 'Aufgaben, welche an andere vergeben wurden';
$labels['mytasks'] = 'Meine Aufgaben';
$labels['mytaskstitle'] = 'An mich übertragene Aufgaben';
$labels['nodate'] = 'Ohne Datum';
$labels['removetag'] = 'Entfernen';
$labels['removelink'] = 'E-Mail-Referenz entfernen';
$labels['auto'] = 'Automatisch';

$labels['taskdetails'] = 'Details';
$labels['newtask'] = 'Neue Aufgabe';
$labels['edittask'] = 'Aufgabe ändern';
$labels['save'] = 'Speichern';
$labels['cancel'] = 'Abbrechen';
$labels['saveandnotify'] = 'Speichern und Benachrichtigen';
$labels['addsubtask'] = 'Teilaufgabe hinzufügen';
$labels['deletetask'] = 'Aufgabe löschen';
$labels['deletethisonly'] = 'Nur diese Aufgabe löschen';
$labels['deletewithchilds'] = 'Mit allen Teilaufgaben löschen';
$labels['taskactions'] = 'Aufgabeneinstellungen...';

$labels['tabsummary'] = 'Titel';
$labels['tabrecurrence'] = 'Wiederholung';
$labels['tabassignments'] = 'Zuweisungen';
$labels['tabattachments'] = 'Anhänge';
$labels['tabsharing'] = 'Freigabe';

$labels['editlist'] = 'Liste bearbeiten';
$labels['createlist'] = 'Liste hinzufügen';
$labels['listactions'] = 'Listeneinstellungen…';
$labels['listname'] = 'Name';
$labels['showalarms'] = 'Show reminders';
$labels['import'] = 'Importieren';
$labels['viewactions'] = 'Ansicht-Aktionen';
$labels['focusview'] = 'Nur diese Liste anzeigen';

// date words
$labels['on'] = 'am';
$labels['at'] = 'um';
$labels['this'] = 'dies';
$labels['next'] = 'weiter';

// messages
$labels['savingdata'] = 'Daten werden gespeichert…';
$labels['errorsaving'] = 'Daten konnten nicht gespeichert werden.';
$labels['notasksfound'] = 'Keine Aufgabe erfüllt die angelegten Kriterien';
$labels['invalidstartduedates'] = 'Das Anfangsdatum muss vor dem Fälligkeitsdatum liegen.';
$labels['deletetasktconfirm'] = 'Diese Aufgabe wirklich löschen?';
$labels['deleteparenttasktconfirm'] = 'Diese Aufgabe wirklich mit allen Teilaufgaben löschen?';
$labels['deletelistconfirm'] = 'Diese Aufgabenliste wirklich mit allen Aufgaben löschen?';
$labels['deletelistconfirmrecursive'] = 'Soll diese Liste wirklich mit allen Aufgaben und Unterlisten gelöscht werden?';
$labels['aclnorights'] = 'Der Zugriff auf diese Aufgabenliste erfordert Administrator-Rechte.';
$labels['changetaskconfirm'] = 'Aufgabe ändern';
$labels['changeconfirmnotifications'] = 'Wollen Sie die beauftragten Teilnehmer über diese Änderung informieren?';
$labels['partstatupdatenotification'] = 'Wollen Sie den Organisator über die Statusänderung benachrichtigen?';

// (hidden) titles and labels for accessibility annotations
$labels['quickaddinput'] = 'Neue Aufgabe Datum und Titel';
$labels['arialabelquickaddbox'] = 'Neue Aufgabe schnell hinzufügen';
$labels['arialabelsearchform'] = 'Suchformular für Aufgaben';
$labels['arialabelquicksearchbox'] = 'Sucheingabe für Aufgaben';
$labels['arialabellistsearchform'] = 'Sucheingabe für Aufgabenlisten';
$labels['arialabeltaskselector'] = 'Listenmodus';
$labels['arialabeltasklisting'] = 'Aufgabenliste';

// attendees
$labels['attendee'] = 'Beauftragter';
$labels['role'] = 'Rolle';
$labels['availability'] = 'Verfüg.';
$labels['confirmstate'] = 'Status';
$labels['addattendee'] = 'Beauftragten hinzufügen';
$labels['roleorganizer'] = 'Organisator';
$labels['rolerequired'] = 'Erforderlich';
$labels['roleoptional'] = 'Optional';
$labels['rolechair'] = 'Stuhl';
$labels['rolenonparticipant'] = 'Beobachter';
$labels['sendinvitations'] = 'Einladungen versenden';
$labels['sendnotifications'] = 'Beauftragte Teilnehmer über die Änderung informieren';
$labels['sendcancellation'] = 'Beauftragte Teilnehmer über die Stornierung informieren';
$labels['invitationsubject'] = 'You\'ve been assigned to "$title"';
$labels['invitationmailbody'] = "*\$title*\n\nDue: \$date\n\nAssignees: \$attendees\n\nPlease find attached an iCalendar file with all the task details which you can import to your tasks application.";
$labels['itipupdatesubject'] = '"$title" wurde aktualisiert';
$labels['itipupdatesubjectempty'] = 'A task that concerns you has been updated';
$labels['itipupdatemailbody'] = "*\$title*\n\nDue: \$date\n\nAssignees: \$attendees\n\nPlease find attached an iCalendar file with the updated task details which you can import to your tasks application.";
$labels['itipcancelsubject'] = '"$title" wurde abgesagt';
$labels['itipcancelmailbody'] = "*\$title*\n\nDue: \$date\n\nAssignees: \$attendees\n\nThe task has been cancelled by \$organizer.\n\nPlease find attached an iCalendar file with the updated task details.";
$labels['saveintasklist'] = 'speichern in';

// invitation handling (overrides labels from libcalendaring)
$labels['itipobjectnotfound'] = 'The task referred by this message was not found in your tasks list.';

$labels['itipmailbodyaccepted'] = "\$sender has accepted the assignment to the following task:\n\n*\$title*\n\nDue: \$date\n\nAssignees: \$attendees";
$labels['itipmailbodytentative'] = "\$sender has tentatively accepted the assignment to the following task:\n\n*\$title*\n\nDue: \$date\n\nAssignees: \$attendees";
$labels['itipmailbodydeclined'] = "\$sender has declined the assignment to the following task:\n\n*\$title*\n\nDue: \$date\n\nAssignees: \$attendees";
$labels['itipmailbodycancel'] = "\$sender has rejected your assignment to the following task:\n\n*\$title*\n\nDue: \$date";
$labels['itipmailbodyin-process'] = "\$sender has set the status of the following task to in-process:\n\n*\$title*\n\nDue: \$date";
$labels['itipmailbodycompleted'] = "\$sender has completed the following task:\n\n*\$title*\n\nDue: \$date";

$labels['attendeeaccepted'] = 'Assignee has accepted';
$labels['attendeetentative'] = 'Assignee has tentatively accepted';
$labels['attendeedeclined'] = 'Assignee has declined';
$labels['attendeedelegated'] = 'Assignee has delegated to $delegatedto';
$labels['attendeein-process'] = 'Assignee is in-process';
$labels['attendeecompleted'] = 'Assignee has completed';

$labels['acceptinvitation'] = 'Do you accept this assignment?';
$labels['itipdeclinetask'] = 'Decline your assignment to this task to the organizer';
$labels['declinedeleteconfirm'] = 'Do you also want to delete this declined task from your tasks list?';
$labels['itipcomment'] = 'Kommentar zur Einladungs-/Benachrichtigungsnachricht';
$labels['itipcommenttitle'] = 'This comment will be attached to the invitation/notification message sent to assignees';
$labels['itipsendsuccess'] = 'Notification sent to assignees';
$labels['errornotifying'] = 'Failed to send notifications to task assignees';
$labels['removefromcalendar'] = 'Aus meinen Aufgaben entfernen';

$labels['andnmore'] = '$nr weitere...';
$labels['delegatedto'] = 'Delegiert an:';
$labels['delegatedfrom'] = 'Delegiert von:';
$labels['savetotasklist'] = 'In den Aufgaben speichern';
$labels['comment'] = 'Kommentar';
$labels['errorimportingtask'] = 'Fehler beim Importieren der Aufgabe(n)';
$labels['importwarningexists'] = 'A copy of this task already exists in your tasklist.';
$labels['importsuccess'] = 'Successfully imported $nr tasks';
$labels['newerversionexists'] = 'A newer version of this task already exists! Aborted.';
$labels['nowritetasklistfound'] = 'No tasklist found to save the task';
$labels['importedsuccessfully'] = 'The task was successfully added to \'$list\'';
$labels['updatedsuccessfully'] = 'The task was successfully updated in \'$list\'';
$labels['attendeupdateesuccess'] = 'Teilnehmerstatus erfolgreich aktualisiert';
$labels['itipresponseerror'] = 'Failed to send the response to this task assignment';
$labels['itipinvalidrequest'] = 'Diese Einladung ist nicht mehr gültig.';
$labels['sentresponseto'] = 'Successfully sent assignment response to $mailto';
$labels['successremoval'] = 'Diese Aufgabe wurde erfolgreich gelöscht.';

$labels['arialabelsortmenu'] = 'Tasks sorting options';
