<?php
/**
 * Localizations for the Kolab Tasks plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/tasklist/
 */
$labels['navtitle'] = 'Aufgaben';
$labels['lists'] = 'Aufgabenlisten';
$labels['list'] = 'Aufgabenliste';
$labels['export'] = 'Exportieren';
$labels['exporttitle'] = 'Nach iCalendar exportieren';
$labels['exportattachments'] = 'Mit Anhängen';
$labels['currentview'] = 'aktuelle Ansicht';
$labels['listsearchresults'] = 'Verfügbare Aufgabenlisten';
$labels['findlists'] = 'Finde Aufgabenlisten...';
$labels['searchterms'] = 'Suchbegriffe';
$labels['notasklistsfound'] = 'Keine Aufgabenlisten gefunden';
$labels['nrtasklistsfound'] = '$nr Aufgabenlisten gefunden';
$labels['removelist'] = 'Aus Liste entfernen';
$labels['showcaldavurl'] = 'Zeige CalDAV URL';
$labels['caldavurldescription'] = 'Kopieren Sie diese Adresse in eine <a href="https://de.wikipedia.org/wiki/CalDAV" target="_blank">CalDAV</a>-Client-Anwendung (z.B. Evolution oder Mozilla Thunderbird) um diese Aufgabenliste mit Ihrem Computer oder Mobilgerät zu synchronisieren.';
$labels['newtask'] = 'Neue Aufgabe';
$labels['createtask'] = 'Aufgabe erstellen <Enter>';
$labels['createnewtask'] = 'Neue Aufgabe erstellen (z.B. Samstag, Rasen mähen)';
$labels['createfrommail'] = 'Als Aufgabe speichern';
$labels['printtitle'] = 'Aufgaben drucken';
$labels['edit'] = 'Bearbeiten';
$labels['delete'] = 'Löschen';
$labels['title'] = 'Titel';
$labels['description'] = 'Beschreibung';
$labels['start'] = 'Start';
$labels['starttime'] = 'Beginn';
$labels['alarms'] = 'Erinnerung';
$labels['repeat'] = 'Wiederholen';
$labels['status'] = 'Status';
$labels['status-needs-action'] = 'Bearbeitung erforderlich';
$labels['status-completed'] = 'Abgeschlossen';
$labels['status-cancelled'] = 'Gekündigt';
$labels['assignedto'] = 'Zugewiesen an';
$labels['created'] = 'Erstellt';
$labels['changed'] = 'Zuletzt bearbeitet';
$labels['taskoptions'] = 'Optionen';
$labels['all'] = 'Alle';
$labels['complete'] = 'Erledigt';
$labels['completeness'] = 'Fortschritt';
$labels['overdue'] = 'Überfällig';
$labels['today'] = 'Heute';
$labels['tomorrow'] = 'Morgen';
$labels['next7days'] = 'Nächste 7 Tage';
$labels['later'] = 'Später';
$labels['assignedtitle'] = 'Aufgaben die Sie anderen Personen zugewiesen haben';
$labels['mytasks'] = 'Meine Aufgaben';
$labels['mytaskstitle'] = 'Mir zugewiesene Aufgaben';
$labels['nodate'] = 'kein Datum';
$labels['removetag'] = 'Entfernen';
$labels['newtask'] = 'Neue Aufgabe';
$labels['edittask'] = 'Aufgabe bearbeiten';
$labels['save'] = 'Speichern';
$labels['cancel'] = 'Abbrechen';
$labels['addsubtask'] = 'Unteraufgabe hinzufügen';
$labels['tabsummary'] = 'Zusammenfassung';
$labels['tabrecurrence'] = 'Wiederholung';
$labels['tabattachments'] = 'Anhänge';
$labels['listname'] = 'Name';
$labels['at'] = 'am';
$labels['yes'] = 'Ja';
$labels['savingdata'] = 'Daten werden gespeichert...';
$labels['confirmstate'] = 'Status';
$labels['roleorganizer'] = 'Organisator';
$labels['rolerequired'] = 'Pflichtfeld';
$labels['roleoptional'] = 'Optional';
$labels['rolechair'] = 'Vorsitzender';
$labels['itipupdatesubject'] = '"$title" wurde aktualisiert';
$labels['itipcancelsubject'] = '"$title" wurde abgesagt';
$labels['taskhistory'] = 'Historie';
$labels['objectchangelog'] = 'Änderungshistorie';
$labels['objectdiff'] = 'Änderungen seit $rev1 bis $rev2';
$labels['objectdiffnotavailable'] = 'Kein vergleich für die ausgewählten Stände möglich';
$labels['objectrestoresuccess'] = 'Stand $rev erfolgreich wiederhergestellt';
$labels['objectrestoreerror'] = 'Der alte Stand konnte nicht wiederhergestellt werden';
$labels['andnmore'] = '$nr mehr...';
$labels['comment'] = 'Kommentar';
$labels['rsvpcomment'] = 'Kommentar';
$labels['itipinvalidrequest'] = 'Die Einladung ist nicht länger gültig';
