<?php
$labels['navtitle'] = 'Tareas';
$labels['edit'] = 'Editar';
$labels['delete'] = 'Borrar';
$labels['title'] = 'Título';
$labels['description'] = 'Descripción';
$labels['start'] = 'Start';
$labels['alarms'] = 'Reminder';
$labels['all'] = 'All';
$labels['today'] = 'Today';
$labels['tomorrow'] = 'Tomorrow';
$labels['removetag'] = 'Remove';
$labels['taskdetails'] = 'Detalles';
$labels['save'] = 'Guardar';
$labels['cancel'] = 'Cancelar';
$labels['tabsummary'] = 'Summary';
$labels['tabrecurrence'] = 'Recurrence';
$labels['tabattachments'] = 'Attachments';
$labels['tabsharing'] = 'Sharing';
$labels['listname'] = 'Nombre';
$labels['showalarms'] = 'Show reminders';
// date words
// mesages
$labels['savingdata'] = 'Guardando datos...';
