<?php
/**
 * Localizations for the Kolab Tasks plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/tasklist/
 */
$labels['navtitle'] = 'Tareas';
$labels['edit'] = 'Editar';
$labels['delete'] = 'Borrar';
$labels['title'] = 'Título';
$labels['description'] = 'Descripción';
$labels['start'] = 'Start';
$labels['alarms'] = 'Reminder';
$labels['repeat'] = 'Repeat';
$labels['status'] = 'Status';
$labels['all'] = 'All';
$labels['today'] = 'Today';
$labels['tomorrow'] = 'Tomorrow';
$labels['removetag'] = 'Remove';
$labels['taskdetails'] = 'Detalles';
$labels['save'] = 'Guardar';
$labels['cancel'] = 'Cancelar';
$labels['tabsummary'] = 'Summary';
$labels['tabrecurrence'] = 'Recurrence';
$labels['tabattachments'] = 'Attachments';
$labels['tabsharing'] = 'Sharing';
$labels['listname'] = 'Nombre';
$labels['showalarms'] = 'Show reminders';
$labels['savingdata'] = 'Guardando datos...';
$labels['role'] = 'Rol';
$labels['availability'] = 'Avail.';
$labels['confirmstate'] = 'Status';
$labels['roleorganizer'] = 'Organizer';
$labels['rolerequired'] = 'Requerido';
$labels['roleoptional'] = 'Opcional';
$labels['rolechair'] = 'Chair';
$labels['sendinvitations'] = 'Send invitations';
$labels['itipupdatesubject'] = '"$title" has been updated';
$labels['itipcancelsubject'] = '"$title" has been canceled';
$labels['andnmore'] = '$nr more...';
$labels['comment'] = 'Comentario';
$labels['attendeupdateesuccess'] = 'Successfully updated the participant\'s status';
$labels['itipinvalidrequest'] = 'This invitation is no longer valid';
