<?php
$labels['edit'] = 'Edit';
$labels['delete'] = 'Kustuta';
$labels['title'] = 'Pealkiri';
$labels['description'] = 'Description';
$labels['start'] = 'Start';
$labels['alarms'] = 'Reminder';
$labels['all'] = 'All';
$labels['today'] = 'Today';
$labels['tomorrow'] = 'Tomorrow';
$labels['removetag'] = 'Remove';
$labels['save'] = 'Salvesta';
$labels['cancel'] = 'Cancel';
$labels['tabsummary'] = 'Summary';
$labels['tabrecurrence'] = 'Recurrence';
$labels['tabattachments'] = 'Attachments';
$labels['tabsharing'] = 'Sharing';
$labels['listname'] = 'Nimi';
$labels['showalarms'] = 'Show reminders';
// date words
// mesages
$labels['savingdata'] = 'Saving data...';
