<?php
/**
 * Localizations for the Kolab Tasks plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/tasklist/
 */
$labels['navtitle'] = 'Tehtävät';
$labels['lists'] = 'Tehtävätlistat';
$labels['list'] = 'Tehtävälista';
$labels['tags'] = 'Tunnisteet';
$labels['newtask'] = 'Uusi tehtävä';
$labels['createnewtask'] = 'Luo uusi tehtävä (esim. Sunnuntai, leikkaa ruoho)';
$labels['createfrommail'] = 'Tallenna tehtävänä';
$labels['mark'] = 'Merkitse';
$labels['unmark'] = 'Poista merkintä';
$labels['edit'] = 'Muokkaa';
$labels['delete'] = 'Poista';
$labels['description'] = 'Kuvaus';
$labels['datetime'] = 'Erääntyy';
$labels['start'] = 'Alkaa';
$labels['alarms'] = 'Muistutus';
$labels['status'] = 'Tila';
$labels['status-cancelled'] = 'Peruttu';
$labels['all'] = 'Kaikki';
$labels['flagged'] = 'Liputettu';
$labels['complete'] = 'Valmiina';
$labels['overdue'] = 'Myöhässä';
$labels['today'] = 'Tänään';
$labels['tomorrow'] = 'Huomenna';
$labels['next7days'] = 'Seuraavat 7 päivää';
$labels['later'] = 'Myöhemmin';
$labels['nodate'] = 'ei päivää';
$labels['removetag'] = 'Poista';
$labels['taskdetails'] = 'Tiedot';
$labels['newtask'] = 'Uusi tehtävä';
$labels['edittask'] = 'Muokkaa tehtävää';
$labels['save'] = 'Tallenna';
$labels['cancel'] = 'Peru';
$labels['addsubtask'] = 'Lisää alitehtävä';
$labels['deletetask'] = 'Poista tehtävä';
$labels['deletethisonly'] = 'Poista vain tämä tehtävä';
$labels['deletewithchilds'] = 'Poista alitehtävineen';
$labels['tabsummary'] = 'Yhteenveto';
$labels['tabrecurrence'] = 'Toistuminen';
$labels['tabattachments'] = 'Liitteet';
$labels['tabsharing'] = 'Jakaminen';
$labels['editlist'] = 'Muokkaa listaa';
$labels['createlist'] = 'Lisää lista';
$labels['listactions'] = 'Listan valinnat...';
$labels['listname'] = 'Nimi';
$labels['import'] = 'Tuo';
$labels['savingdata'] = 'Tallennetaan tietoja...';
$labels['errorsaving'] = 'Tietojen tallenntaminen epäonnistui.';
$labels['notasksfound'] = 'Ehtoja vastaavia tehtäviä ei löytynyt';
$labels['invalidstartduedates'] = 'Aloituspäivän tulee olla vanhempi kuin eräpäivän.';
$labels['deletetasktconfirm'] = 'Haluatko varmasti poistaa tämän tehtävän?';
$labels['deleteparenttasktconfirm'] = 'Haluatko varmasti poistaa tämän tehtävän kaikkine alitehtävineen?';
$labels['deletelistconfirm'] = 'Haluatko varmasti poistaa tämän listan ja sen kaikki tehtävät?';
$labels['deletelistconfirmrecursive'] = 'Haluatko varmasti poistaa tämän listan, sen alilistat ja tehtävät?';
$labels['role'] = 'Rooli';
$labels['confirmstate'] = 'Tila';
$labels['roleorganizer'] = 'Järjestäjä';
$labels['rolerequired'] = 'Vaadittu';
$labels['roleoptional'] = 'Valinnainen';
$labels['sendinvitations'] = 'Lähetä kutsut';
$labels['itipupdatesubject'] = '"$title" on päivitetty';
$labels['itipcancelsubject'] = '"$title" on peruttu';
$labels['andnmore'] = '$nr lisää...';
$labels['comment'] = 'Kommentti';
$labels['itipinvalidrequest'] = 'Kutsu ei ole enää kelvollinen';
