<?php
/**
 * Localizations for the Kolab Tasks plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/tasklist/
 */
$labels['navtitle'] = 'Attività';
$labels['lists'] = 'Elenchi attività';
$labels['list'] = 'Elenco attività';
$labels['tags'] = 'Etichette';
$labels['newtask'] = 'Nuova attività';
$labels['createnewtask'] = 'Crea una nuova attività (es. Saturday, Falciare il prato)';
$labels['createfrommail'] = 'Salva come attività';
$labels['mark'] = 'Importante';
$labels['unmark'] = 'Non importante';
$labels['edit'] = 'Modifica';
$labels['delete'] = 'Elimina';
$labels['title'] = 'Titolo';
$labels['description'] = 'Descrizione';
$labels['datetime'] = 'Scadenza';
$labels['start'] = 'Inizio';
$labels['alarms'] = 'Promemoria';
$labels['repeat'] = 'Frequenza';
$labels['status'] = 'Stato';
$labels['all'] = 'Tutto';
$labels['flagged'] = 'Importanti';
$labels['complete'] = 'Fatto';
$labels['overdue'] = 'In ritardo';
$labels['today'] = 'Oggi';
$labels['tomorrow'] = 'Domani';
$labels['next7days'] = 'Prossimi 7 giorni';
$labels['later'] = 'Dopo';
$labels['nodate'] = 'Senza data';
$labels['removetag'] = 'Elimina';
$labels['taskdetails'] = 'Dettagli';
$labels['newtask'] = 'Nuova attività';
$labels['edittask'] = 'Modifica attività';
$labels['save'] = 'Salva';
$labels['cancel'] = 'Annulla';
$labels['addsubtask'] = 'Aggiungi sotto-attività';
$labels['deletetask'] = 'Elimina attività';
$labels['deletethisonly'] = 'Elimina solo questa attività';
$labels['deletewithchilds'] = 'Elimina con tutte le sotto-attività';
$labels['tabsummary'] = 'Oggetto';
$labels['tabrecurrence'] = 'Ricorrenza';
$labels['tabattachments'] = 'Allegati';
$labels['tabsharing'] = 'Condivisione';
$labels['editlist'] = 'Modifca elenco';
$labels['createlist'] = 'Aggiungi elenco';
$labels['listactions'] = 'Opzioni elenco...';
$labels['listname'] = 'Nome';
$labels['showalarms'] = 'Mostra promemoria';
$labels['import'] = 'Importa';
$labels['focusview'] = 'Mostra solo questo elenco';
$labels['savingdata'] = 'Salvataggio dati...';
$labels['notasksfound'] = 'Nessuna attività trovata.';
$labels['invalidstartduedates'] = 'La data di inizio non può essere successiva a quella di scadenza.';
$labels['deletetasktconfirm'] = 'Eliminare davvero questa attività?';
$labels['deleteparenttasktconfirm'] = 'Eliminare davvero questa attività e tutte le sotto-attività?';
$labels['role'] = 'Ruolo';
$labels['availability'] = 'Dispon.';
$labels['confirmstate'] = 'Stato';
$labels['roleorganizer'] = 'Organizzatore';
$labels['rolerequired'] = 'Necessario';
$labels['roleoptional'] = 'Facoltativo';
$labels['rolechair'] = 'Presidente';
$labels['sendinvitations'] = 'Manda inviti';
$labels['itipupdatesubject'] = '"$title" è stato aggiornato';
$labels['itipcancelsubject'] = '"$title" è stato annullato';
$labels['andnmore'] = 'Altri $nr...';
$labels['attendeupdateesuccess'] = 'Stato dei partecipanti aggiornato correttamente';
$labels['itipinvalidrequest'] = 'Questo invito non è più valido';
