<?php
/**
 * Localizations for the Kolab Tasks plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/tasklist/
 */
$labels['navtitle'] = 'Tarefas';
$labels['lists'] = 'Listas de tarefas';
$labels['list'] = 'Lista de tarefas';
$labels['tags'] = 'Etiquetas';
$labels['tasklistsubscribe'] = 'Listar permanentemente';
$labels['newtask'] = 'Nova Tarefa';
$labels['createnewtask'] = 'Criar nova Tarefa (ex.: Sábado, Cortar a grama)';
$labels['createfrommail'] = 'Salvar como tarefa';
$labels['mark'] = 'Marcar';
$labels['unmark'] = 'Desmarcar';
$labels['edit'] = 'Editar';
$labels['delete'] = 'Deletar';
$labels['title'] = 'Título';
$labels['description'] = 'Descrição';
$labels['start'] = 'Início';
$labels['alarms'] = 'Lembrete';
$labels['repeat'] = 'Repetir';
$labels['status'] = 'Situação';
$labels['status-cancelled'] = 'Cancalado';
$labels['all'] = 'Todos';
$labels['flagged'] = 'Marcado';
$labels['complete'] = 'Completado';
$labels['overdue'] = 'Atrasado';
$labels['today'] = 'Hoje';
$labels['tomorrow'] = 'Amanhã';
$labels['next7days'] = 'Próximos 7 dias';
$labels['later'] = 'Mais tarde';
$labels['nodate'] = 'sem data';
$labels['removetag'] = 'Remover';
$labels['taskdetails'] = 'Detalhes';
$labels['newtask'] = 'Nova Tarefa';
$labels['edittask'] = 'Editar Tarefa';
$labels['save'] = 'Gravar';
$labels['cancel'] = 'Cancelar';
$labels['addsubtask'] = 'Adicionar subtarefa';
$labels['deletetask'] = 'Remover tarefa';
$labels['deletethisonly'] = 'Remover esta tarefa somente';
$labels['deletewithchilds'] = 'Remover com todas as subtarefas';
$labels['tabsummary'] = 'Sumário';
$labels['tabrecurrence'] = 'Repetição';
$labels['tabattachments'] = 'Anexos';
$labels['tabsharing'] = 'Compartilhamento';
$labels['editlist'] = 'Editar lista';
$labels['createlist'] = 'Adicionar lista';
$labels['listactions'] = 'Opções da lista...';
$labels['listname'] = 'Nome';
$labels['showalarms'] = 'Show reminders';
$labels['import'] = 'Importar';
$labels['on'] = 'em';
$labels['at'] = 'no';
$labels['this'] = 'este';
$labels['next'] = 'próximo';
$labels['savingdata'] = 'Salvando dados...';
$labels['errorsaving'] = 'Falha ao salvar dados.';
$labels['notasksfound'] = 'Nenhuma tarefa encontrada com estes critérios';
$labels['invalidstartduedates'] = 'Data de início não deve ser maior que data de término.';
$labels['deletetasktconfirm'] = 'Você realmente quer remover esta tarefa?';
$labels['deleteparenttasktconfirm'] = 'Você realmente quer remover esta tarefa e todas suas subtarefas?';
$labels['deletelistconfirm'] = 'Você realmente quer remover esta lista com todas as suas tarefas?';
$labels['role'] = 'Papel';
$labels['availability'] = 'Disp.';
$labels['confirmstate'] = 'Situação';
$labels['roleorganizer'] = 'Organizador';
$labels['rolerequired'] = 'Obrigatório';
$labels['roleoptional'] = 'Opcional';
$labels['rolechair'] = 'Chair';
$labels['sendinvitations'] = 'Enviar convites';
$labels['itipupdatesubject'] = '"$title" foi atualizado';
$labels['itipcancelsubject'] = '"$title" foi cancelado';
$labels['andnmore'] = '$nr mais...';
$labels['delegatedto'] = 'Delegado para:';
$labels['delegatedfrom'] = 'Delegado de:';
$labels['comment'] = 'Comentário';
$labels['attendeupdateesuccess'] = 'O status do participante foi atualizado com sucesso.';
$labels['itipinvalidrequest'] = 'Este convite não é mais válido';
