<?php

/**
 * Localizations for the csv_export plugin
 *
 * Copyright (C) 2016, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/csv_export/
 */

$labels = array();
$labels['title'] = 'Contacts export';
$labels['text'] = 'Please, choose the export file format:';
$labels['csv'] = 'CSV (comma-separated)';
$labels['vcf'] = 'vCard';
$labels['format'] = 'Format';
