<?php

/**
 * Localizations for the Kolab libkolab plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/libkolab/
 */

$labels = array();
$labels['compare'] = 'Comparer';
$labels['objectchangelog'] = 'Historique';
$labels['revision'] = 'Version';
$labels['user'] = 'Utilisateur';
$labels['operation'] = 'Action';
$labels['actionappend'] = 'Sauvegardé';
$labels['actionmove'] = 'Déplacé';
$labels['actiondelete'] = 'Supprimé';
$labels['showrevision'] = 'Afficher cette version';
$labels['restore'] = 'Restaurer cette version';

