<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_notes/
 */
$labels['navtitle'] = 'Notizen';
$labels['tags'] = 'Tags';
$labels['notes'] = 'Notizen';
$labels['created'] = 'Erstellt';
$labels['changed'] = 'Geändert';
$labels['title'] = 'Titel';
$labels['listname'] = 'Name';
$labels['tabsharing'] = 'Freigabe';
$labels['abort'] = 'Abbrechen';
$labels['foldersubscribe'] = 'List permanently';
$labels['removelist'] = 'Remove from list';
$labels['removelink'] = 'E-Mail-Referenz entfernen';
$labels['savingdata'] = 'Speichere...';
