<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_notes/
 */
$labels['navtitle'] = 'Notizen';
$labels['lists'] = 'Notizbücher';
$labels['notes'] = 'Notizen';
$labels['create'] = 'Neue Notiz';
$labels['createnote'] = 'Eine neue Notiz anlegen';
$labels['send'] = 'Senden';
$labels['sendnote'] = 'Notiz per E-Mail senden';
$labels['newnote'] = 'Neue Notiz';
$labels['created'] = 'Erstellt';
$labels['changed'] = 'Zuletzt bearbeitet';
$labels['title'] = 'Titel';
$labels['now'] = 'Jetzt';
$labels['sortby'] = 'Sortieren nach';
$labels['newnotebook'] = 'Ein neues Notizbuch anlegen';
$labels['addnotebook'] = 'Notizbuch hinzufügen';
$labels['editlist'] = 'Notizbuch bearbeiten';
$labels['listname'] = 'Name';
$labels['discard'] = 'Verwerfen';
$labels['abort'] = 'Abbrechen';
$labels['unsavedchanges'] = 'Ungespeicherte Änderungen!';
$labels['appendnote'] = 'Eine Notiz hinzufügen';
$labels['editnote'] = 'Notiz bearbeiten';
$labels['findnotebooks'] = 'Finde Notizbücher...';
$labels['listsearchresults'] = 'Zusätzliche Notizbücher';
$labels['nrnotebooksfound'] = '$nr Notizbücher gefunden';
$labels['nonotebooksfound'] = 'Keine Notizbücher gefunden';
$labels['removelist'] = 'Aus Liste entfernen';
$labels['savingdata'] = 'Daten werden gespeichert...';
$labels['norecordsfound'] = 'Keine Notizen gefunden';
$labels['deletenotesconfirm'] = 'Möchten Sie die ausgewählten Notizen wirklich löschen?';
$labels['deletenotebookconfirm'] = 'Möchten Sie dieses Notizbuch mit allen darin enthaltenen Notizen wirklich löschen? Diese Aktion kann nicht rückgängig gemacht werden.';
$labels['aclnorights'] = 'Sie haben keine Administrations-Privilegien für dieses Notizbuch.';
$labels['arialabelnoteslist'] = 'Liste der Notizen';
