<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_notes/
 */
$labels['navtitle'] = 'Notas';
$labels['notes'] = 'Notas';
$labels['created'] = 'Creado';
$labels['changed'] = 'Última modificación';
$labels['title'] = 'Título';
$labels['listname'] = 'Nombre';
$labels['tabsharing'] = 'Compartir';
$labels['foldersubscribe'] = 'Lista Permanente';
$labels['removelist'] = 'Borrar de la lista';
$labels['removelink'] = 'Eliminar la referencia de correo electrónico';
$labels['savingdata'] = 'Guardando datos...';
