<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_notes/
 */
$labels['navtitle'] = 'Märkmed';
$labels['tags'] = 'Sildid';
$labels['lists'] = 'Märkmikud';
$labels['notes'] = 'Märkmed';
$labels['create'] = 'Uus märkus';
$labels['createnote'] = 'Loo uus märkus';
$labels['send'] = 'Saada';
$labels['sendnote'] = 'Saada märkus e-postiga';
$labels['newnote'] = 'Uus märkusUus märkus';
$labels['notags'] = 'Silte pole';
$labels['removetag'] = 'Eemalda silt';
$labels['created'] = 'Loodud';
$labels['changed'] = 'Viimati muudetud';
$labels['title'] = 'Pealkiri';
$labels['now'] = 'Praegu';
$labels['sortby'] = 'Sorteeri';
$labels['newnotebook'] = 'Loo uus märkmik';
$labels['addnotebook'] = 'Lisa märkmik';
$labels['listname'] = 'Nimi';
$labels['tabsharing'] = 'Jagamine';
$labels['discard'] = 'Loobu';
$labels['abort'] = 'Katkesta';
$labels['unsavedchanges'] = 'Salvestama muudatused!';
$labels['appendnote'] = 'Lisa märkus';
$labels['editnote'] = 'Muuda märkust';
$labels['findnotebooks'] = 'Find notebooks...';
$labels['findnotes'] = 'Otsi märkuseid';
$labels['listsearchresults'] = 'Lisamärkmikud';
$labels['nonotebooksfound'] = 'Ühtegi märkmikku ei leitud';
$labels['removelist'] = 'Eemalda nimekirjast';
$labels['savingdata'] = 'Andmete salvestamine...';
$labels['recordnotfound'] = 'Sissekannet ei leitud';
$labels['arialabelnotebookform'] = 'Märkmiku omadused';
$labels['arialabelnoteform'] = 'Märkme muutmise vorm';
