<?php
$labels['navtitle'] = 'Muistiot';
$labels['tags'] = 'Tunnisteet';
$labels['notes'] = 'Muistiot';
$labels['removetag'] = 'Poista tunniste';
$labels['created'] = 'Luotu';
$labels['changed'] = 'Viimeksi muokattu';
$labels['title'] = 'Nimi';
$labels['listname'] = 'Nimi';
$labels['tabsharing'] = 'Jakaminen';
$labels['abort'] = 'Keskeytä';
$labels['foldersubscribe'] = 'Luetteloi pysyvästi';
$labels['removelist'] = 'Poista listasta';
$labels['removelink'] = 'Poista sähköpostiviittaus';
$labels['savingdata'] = 'Tallennetaan tietoja...';
