<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_notes/
 */
$labels['navtitle'] = 'Muistiot';
$labels['tags'] = 'Tunnisteet';
$labels['lists'] = 'Muistikirjat';
$labels['notes'] = 'Muistiot';
$labels['create'] = 'Uusi muistio';
$labels['createnote'] = 'Luo uusi muistio';
$labels['send'] = 'Lähetä';
$labels['sendnote'] = 'Lähetä muistio sähköpostitse';
$labels['newnote'] = 'Luo uusi muistio';
$labels['notags'] = 'Ei tunnisteita';
$labels['removetag'] = 'Poista tunniste';
$labels['created'] = 'Luotu';
$labels['changed'] = 'Viimeksi muokattu';
$labels['title'] = 'Nimi';
$labels['now'] = 'Nyt';
$labels['sortby'] = 'Lajittelujärjestys';
$labels['newnotebook'] = 'Luo uusi muistikirja';
$labels['addnotebook'] = 'Lisää muistikirja';
$labels['deletelist'] = 'Poista muistikirja';
$labels['editlist'] = 'Muokkaa tai jaa muistikirja';
$labels['listname'] = 'Nimi';
$labels['tabsharing'] = 'Jakaminen';
$labels['discard'] = 'Hylkää';
$labels['abort'] = 'Keskeytä';
$labels['unsavedchanges'] = 'Tallentamattomia muutoksia!';
$labels['appendnote'] = 'Lisää muistio';
$labels['editnote'] = 'Muokkaa muistiota';
$labels['savein'] = 'Tallenna kohteeseen';
$labels['foldersubscribe'] = 'Luetteloi pysyvästi';
$labels['findnotebooks'] = 'Etsi muistikirjoja...';
$labels['findnotes'] = 'Etsi muistioita';
$labels['listsearchresults'] = 'Lisämuistikirjat';
$labels['nrnotebooksfound'] = '$nr muistikirjaa löytyi';
$labels['nonotebooksfound'] = 'Muistikirjoja ei löytynyt';
$labels['removelist'] = 'Poista listasta';
$labels['removelink'] = 'Poista sähköpostiviittaus';
$labels['savingdata'] = 'Tallennetaan tietoja...';
$labels['norecordsfound'] = 'Muistioita ei löytynyt';
$labels['nochanges'] = 'Ei muutoksia tallennettavaksi';
$labels['entertitle'] = 'Anna nimi tälle muistiolle!';
$labels['deletenotesconfirm'] = 'Haluatko varmasti poistaa valitut muistiot?';
$labels['deletenotebookconfirm'] = 'Haluatko varmasti poistaa muistikirjan ja kaikki siihen kuuluvat muistiot? Tätä toimenpidettä ei voi perua.';
$labels['discardunsavedchanges'] = 'Nykyistiä muistiota ei ole tannettu. Hylätäänkö muutokset?';
$labels['invalidlistproperties'] = 'Virheelliset muistikirjan ominaisuudet! Aseta muistikirjalle kelvollinen nimi.';
$labels['entertitle'] = 'Anna nimi tälle muistiolle!';
$labels['aclnorights'] = 'Sinulla ei ole ylläpitäjän oikeuksia tähän muistikirjaan.';
$labels['arialabelnoteslist'] = 'Lista muistioista';
$labels['arialabelnotesearchform'] = 'Muistioiden hakulomake';
$labels['arialabelnotesquicksearchbox'] = 'Muistioiden hakusyöte';
$labels['arialabelnotesoptionsmenu'] = 'Muistikirjan toimenpidevalikko';
$labels['arialabelnotebookform'] = 'Muistikirjan ominaisuudet';
$labels['arialabelmessagereferences'] = 'Linkitetyt sähköpostiviestit';
$labels['arialabelfoldersearchform'] = 'Muistikirjojen hakulomake';
$labels['arialabelnoteform'] = 'Muistion muokkauslomake';
