<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_notes/
 */
$labels['navtitle'] = 'Jegyzetek';
$labels['tags'] = 'Kulcsszavak';
$labels['notes'] = 'Jegyzetek';
$labels['listname'] = 'Név';
$labels['tabsharing'] = 'Megosztás';
$labels['findnotebooks'] = 'Find notebooks...';
$labels['savingdata'] = 'Adatok mentése...';
$labels['arialabelfoldersearchform'] = 'Notebooks search form';
