<?php
$labels['navtitle'] = 'Note';
$labels['tags'] = 'Etichette';
$labels['notes'] = 'Note';
$labels['created'] = 'Creato';
$labels['changed'] = 'Ultima modifica';
$labels['title'] = 'Titolo';
$labels['listname'] = 'Nome';
$labels['tabsharing'] = 'Condivisione';
$labels['foldersubscribe'] = 'Elenca sempre';
$labels['removelist'] = 'Rimuovi dalla lista';
$labels['removelink'] = 'Rimuovi riferimento email';
$labels['savingdata'] = 'Salvataggio dati...';
