<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_notes/
 */
$labels['navtitle'] = 'Notities';
$labels['notes'] = 'Notities';
$labels['listname'] = 'Naam';
$labels['tabsharing'] = 'Delen';
$labels['foldersubscribe'] = 'Permanent weergeven';
$labels['savingdata'] = 'Data wordt opgeslagen...';
