<?php
$labels['navtitle'] = 'Anteckningar';
$labels['tags'] = 'Etiketter';
$labels['notes'] = 'Anteckningar';
$labels['created'] = 'Skapad';
$labels['changed'] = 'Senast ändrad';
$labels['title'] = 'Titel';
$labels['listname'] = 'Namn';
$labels['tabsharing'] = 'Delning';
$labels['foldersubscribe'] = 'Lista permanent';
$labels['removelist'] = 'Ta bort från lista';
$labels['savingdata'] = 'Sparar data ...';
