<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_notes/
 */
$labels['navtitle'] = 'Anteckningar';
$labels['tags'] = 'Etiketter';
$labels['lists'] = 'Anteckningsböcker';
$labels['notes'] = 'Anteckningar';
$labels['create'] = 'Ny anteckning';
$labels['createnote'] = 'Skapa en ny anteckning';
$labels['send'] = 'Skicka';
$labels['sendnote'] = 'Skicka anteckning med e-post';
$labels['newnote'] = 'Ny anteckning';
$labels['notags'] = 'Inga etiketter';
$labels['removetag'] = 'Ta bort etikett';
$labels['created'] = 'Skapad';
$labels['changed'] = 'Senast ändrad';
$labels['title'] = 'Titel';
$labels['now'] = 'Nu';
$labels['sortby'] = 'Sortera enligt';
$labels['newnotebook'] = 'Skapa en ny anteckningsbok';
$labels['addnotebook'] = 'Lägg till anteckningsbok';
$labels['listname'] = 'Namn';
$labels['tabsharing'] = 'Delning';
$labels['discard'] = 'Kassera';
$labels['abort'] = 'Avbryt';
$labels['unsavedchanges'] = 'Ej sparade ändringar!';
$labels['appendnote'] = 'Lägg till en anteckning';
$labels['editnote'] = 'Redigera anteckning';
$labels['savein'] = 'Spara i';
$labels['foldersubscribe'] = 'Lista permanent';
$labels['findnotebooks'] = 'Hitta anteckningsböcker ...';
$labels['listsearchresults'] = 'Ytterligare anteckningsböcker';
$labels['nrnotebooksfound'] = '$nr anteckningsböcker hittades';
$labels['nonotebooksfound'] = 'Inga anteckningsböcker hittades';
$labels['removelist'] = 'Ta bort från lista';
$labels['removelink'] = 'Ta bort e-postreferens';
$labels['savingdata'] = 'Sparar data ...';
$labels['recordnotfound'] = 'Hittade inte post';
$labels['norecordsfound'] = 'Inga anteckningar hittades';
$labels['nochanges'] = 'Inga ändringar att spara';
$labels['entertitle'] = 'Vänligen ange en titel för denna anteckning!';
$labels['deletenotesconfirm'] = 'Vill du verkligen ta bort valda anteckningar?';
$labels['deletenotebookconfirm'] = 'Vill du verkligen ta denna anteckningsbok med alla anteckningar? Denna åtgärd kan inte ångras.';
$labels['discardunsavedchanges'] = 'Den nuvarande anteckningen har inte sparats än. Ignorera ändringarna?';
$labels['invalidlistproperties'] = 'Ogiltiga egenskaper för anteckningsbok! Vänligen ange ett giltigt namn.';
$labels['entertitle'] = 'Vänligen ange en titel för denna anteckning!';
$labels['aclnorights'] = 'Du har inte administratörsrättigheter för denna anteckningsbok.';
$labels['arialabelnoteslist'] = 'Lista med anteckningar';
$labels['arialabelnotesearchform'] = 'Sökformulär för anteckningar';
$labels['arialabelnotesquicksearchbox'] = 'Sökinmatning för anteckningar';
$labels['arialabelnotessortmenu'] = 'Sorteringsalternativ för anteckningslista';
$labels['arialabelnotesoptionsmenu'] = 'Åtgärdsmeny för anteckningsbok';
$labels['arialabelnotebookform'] = 'Egenskaper för anteckningsbok';
$labels['arialabelmessagereferences'] = 'Länkade e-postmeddelanden';
$labels['arialabelfoldersearchform'] = 'Sökformulär för anteckningsböcker';
$labels['arialabelnoteform'] = 'Redigeringsformulär för anteckning';
