<?php
/**
 * Localizations for Kolab Calendar plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/calendar/
 */
$labels['default_view'] = 'Vista per defecte';
$labels['time_format'] = 'Format de l\'hora';
$labels['first_day'] = 'Primer dia de la setmana';
$labels['first_hour'] = 'Primera hora a mostrar';
$labels['workinghours'] = 'Hores de feina';
$labels['add_category'] = 'Afegeix categoria';
$labels['remove_category'] = 'Suprimeix categoria';
$labels['calendar'] = 'Calendari';
$labels['calendars'] = 'Calendaris';
$labels['category'] = 'Categoria';
$labels['categories'] = 'Categories';
$labels['createcalendar'] = 'Crea un nou calendari';
$labels['editcalendar'] = 'Edita les propietats del calendari';
$labels['name'] = 'Nom';
$labels['color'] = 'Color';
$labels['day'] = 'Dia';
$labels['week'] = 'Setmana';
$labels['month'] = 'Mes';
$labels['agenda'] = 'Agenda';
$labels['new'] = 'Nou';
$labels['edit'] = 'Edita';
$labels['save'] = 'Desa';
$labels['remove'] = 'Suprimeix';
$labels['cancel'] = 'Cancel·la';
$labels['select'] = 'Selecciona';
$labels['print'] = 'Imprimeix';
$labels['printtitle'] = 'Imprimeix calendaris';
$labels['title'] = 'Resum';
$labels['description'] = 'Descripció';
$labels['all-day'] = 'tot-el-dia';
$labels['export'] = 'Exporta';
$labels['exporttitle'] = 'Exporta a iCalendari';
$labels['location'] = 'Ubicació';
$labels['date'] = 'Data';
$labels['start'] = 'Inici';
$labels['end'] = 'Final';
$labels['selectdate'] = 'Tria la data';
$labels['freebusy'] = 'Mostra\'m com';
$labels['free'] = 'Lliure';
$labels['busy'] = 'Ocupat';
$labels['outofoffice'] = 'Fora de l\'oficina';
$labels['priority'] = 'Prioritat';
$labels['sensitivity'] = 'Privadesa';
$labels['public'] = 'públic';
$labels['private'] = 'privat';
$labels['confidential'] = 'confidencial';
$labels['alarms'] = 'Recordatori';
$labels['weekofyear'] = 'Setmana';
$labels['availfree'] = 'Lliure';
$labels['availbusy'] = 'Ocupat';
$labels['availoutofoffice'] = 'Fora de l\'oficina';
$labels['tabsummary'] = 'Resum';
?>
