<?php

/**
 * Localizations for Kolab Calendar plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/calendar/
 */

$labels = array();

// preferences
$labels['default_view'] = 'Standardvisning';
$labels['time_format'] = 'Tidsformat';
$labels['timeslots'] = 'Time slots per hour';
$labels['first_day'] = 'Første ugedag';
$labels['first_hour'] = 'Første time som vises';
$labels['workinghours'] = 'Arbejdstider';
$labels['add_category'] = 'Tilføj kategori';
$labels['remove_category'] = 'Fjern kategori';
$labels['defaultcalendar'] = 'Opret nye arragementer i';
$labels['eventcoloring'] = 'Farver for arrangementer';
$labels['coloringmode0'] = 'Ifølge kalender';
$labels['coloringmode1'] = 'Ifølge kategori';
$labels['coloringmode2'] = 'Kalender til oversigt, kategori til indhold';
$labels['coloringmode3'] = 'Kategori til oversigt, kalender til indhold';
$labels['afternothing'] = 'Do nothing';
$labels['aftertrash'] = 'Move to Trash';
$labels['afterdelete'] = 'Delete the message';
$labels['afterflagdeleted'] = 'Flag as deleted';
$labels['aftermoveto'] = 'Move to...';
$labels['itipoptions'] = 'Event Invitations';
$labels['afteraction'] = 'After an invitation or update message is processed';

// calendar
$labels['calendar'] = 'Kalender';
$labels['calendars'] = 'Kalendere';
$labels['category'] = 'Kategori';
$labels['categories'] = 'Kategorier';
$labels['createcalendar'] = 'Opret ny kalender';
$labels['editcalendar'] = 'Redigér kalenderegenskaber';
$labels['name'] = 'Navn';
$labels['color'] = 'Farve';
$labels['day'] = 'Dag';
$labels['week'] = 'Uge';
$labels['month'] = 'Måned';
$labels['agenda'] = 'Dagsorden';
$labels['new'] = 'Ny';
$labels['new_event'] = 'Nyt arrangement';
$labels['edit_event'] = 'Redigér arrangement';
$labels['edit'] = 'Redigér';
$labels['save'] = 'Gem';
$labels['removelist'] = 'Remove from list';
$labels['cancel'] = 'Annullér';
$labels['select'] = 'Vælg';
$labels['print'] = 'Udskriv';
$labels['printtitle'] = 'Udskriv kalendere';
$labels['title'] = 'Resumé';
$labels['description'] = 'Beskrivelse';
$labels['all-day'] = 'hele-dagen';
$labels['export'] = 'Eksport';
$labels['exporttitle'] = 'Eksportér til iCalendar';
$labels['exportrange'] = 'Arrangementer fra';
$labels['exportattachments'] = 'Med vedhæftninger';
$labels['customdate'] = 'Brugerdefineret dato';
$labels['location'] = 'Placering';
$labels['url'] = 'URL';
$labels['date'] = 'Dato';
$labels['start'] = 'Start';
$labels['starttime'] = 'Start time';
$labels['end'] = 'Slut';
$labels['endtime'] = 'End time';
$labels['repeat'] = 'Gentag';
$labels['selectdate'] = 'Vælg dato';
$labels['freebusy'] = 'Vis mig som';
$labels['free'] = 'Ledig';
$labels['busy'] = 'Optaget';
$labels['outofoffice'] = 'Ikke på kontoret';
$labels['tentative'] = 'Forsøgsvis';
$labels['mystatus'] = 'My status';
$labels['status'] = 'Status';
$labels['status-confirmed'] = 'Bekræftet';
$labels['status-cancelled'] = 'Annulleret';
$labels['priority'] = 'Prioritet';
$labels['sensitivity'] = 'Privatliv';
$labels['public'] = 'offentlig';
$labels['private'] = 'privat';
$labels['confidential'] = 'fortrolig';
$labels['alarms'] = 'Påmindelse';
$labels['comment'] = 'Comment';
$labels['created'] = 'Created';
$labels['changed'] = 'Last Modified';
$labels['unknown'] = 'Ukendt';
$labels['eventoptions'] = 'Tilvalg';
$labels['generated'] = 'oprettet per';
$labels['eventhistory'] = 'History';
$labels['printdescriptions'] = 'Udskriv beskrivelser';
$labels['parentcalendar'] = 'Indsæt indeni';
$labels['searchearlierdates'] = '« Søg efter tidligere arrangementer';
$labels['searchlaterdates'] = 'Søg efter senere arrangementer »';
$labels['andnmore'] = '$nr flere...';
$labels['togglerole'] = 'Klik for at vise eller skjule rolle';
$labels['createfrommail'] = 'Gem som arrangement';
$labels['importevents'] = 'Importér arrangement';
$labels['importrange'] = 'Arrangementer fra';
$labels['onemonthback'] = '1 måned tilbage';
$labels['nmonthsback'] = '$nr måneder tilbage';
$labels['showurl'] = 'Vis kalenderens URL';
$labels['showurldescription'] = 'Brug følgende adresse for at tilgå din kalender (skrivebeskyttet) fra andre programmer.  Du kan kopiere og indsætet denne i ethvert kalenderprogram, der understøtter iCal-formatet.';
$labels['caldavurldescription'] = 'Kopiér denne adresse til en <a href="http://en.wikipedia.org/wiki/CalDAV" target="_blank">CalDAV</a>-klientprogram (eks. Evolution eller Mozilla Thunderbird) for at synkronisere denne kalender komplet med din computer eller mobilenhed.';
$labels['findcalendars'] = 'Find calendars...';
$labels['searchterms'] = 'Search terms';
$labels['calsearchresults'] = 'Available Calendars';
$labels['calendarsubscribe'] = 'List permanently';
$labels['nocalendarsfound'] = 'No calendars found';
$labels['nrcalendarsfound'] = '$nr calendars found';
$labels['quickview'] = 'View only this calendar';
$labels['invitationspending'] = 'Pending invitations';
$labels['invitationsdeclined'] = 'Declined invitations';
$labels['changepartstat'] = 'Change participant status';
$labels['rsvpcomment'] = 'Invitation text';

// agenda view
$labels['listrange'] = 'Interval som skal vises:';
$labels['listsections'] = 'Del op i:';
$labels['smartsections'] = 'Smarte sektioner';
$labels['until'] = 'indtil';
$labels['today'] = 'I dag';
$labels['tomorrow'] = 'I morgen';
$labels['thisweek'] = 'Denne uge';
$labels['nextweek'] = 'Næste uge';
$labels['prevweek'] = 'Previous week';
$labels['thismonth'] = 'Denne måned';
$labels['nextmonth'] = 'Næste måned';
$labels['weekofyear'] = 'Uge';
$labels['pastevents'] = 'Tidligere';
$labels['futureevents'] = 'Fremtid';

// alarm/reminder settings
$labels['showalarms'] = 'Show reminders';
$labels['defaultalarmtype'] = 'Standardindstilling for påmindelse';
$labels['defaultalarmoffset'] = 'Standardtidspunkt for påmindelse';

// attendees
$labels['attendee'] = 'Deltager';
$labels['role'] = 'Rolle';
$labels['availability'] = 'Tilg.';
$labels['confirmstate'] = 'Status';
$labels['addattendee'] = 'Tilføj deltager';
$labels['roleorganizer'] = 'Organisator';
$labels['rolerequired'] = 'Påkrævet';
$labels['roleoptional'] = 'Valgfri';
$labels['rolechair'] = 'Formand';
$labels['rolenonparticipant'] = 'Absent';
$labels['cutypeindividual'] = 'Individuel';
$labels['cutypegroup'] = 'Gruppe';
$labels['cutyperesource'] = 'Ressource';
$labels['cutyperoom'] = 'Lokale';
$labels['availfree'] = 'Ledig';
$labels['availbusy'] = 'Optaget';
$labels['availunknown'] = 'Ukendt';
$labels['availtentative'] = 'Forsøgsvis';
$labels['availoutofoffice'] = 'Ikke på kontoret';
$labels['delegatedto'] = 'Delegated to: ';
$labels['delegatedfrom'] = 'Delegated from: ';
$labels['scheduletime'] = 'Find ledigt tidspunkt';
$labels['sendinvitations'] = 'Send invitationer';
$labels['sendnotifications'] = 'Gør deltagere opmærksom på ændringer';
$labels['sendcancellation'] = 'Giv deltagere besked om aflysning af arrangementer';
$labels['onlyworkinghours'] = 'Find ledigt tidspunkt inden for mine arbejdstider';
$labels['reqallattendees'] = 'Påkrævet/alle deltagere';
$labels['prevslot'] = 'Forrige blok';
$labels['nextslot'] = 'Næste blok';
$labels['suggestedslot'] = 'Suggested Slot';
$labels['noslotfound'] = 'Kunne ikke finde en ledig tidsblok';
$labels['invitationsubject'] = 'Du er blevet inviteret til "$title"';
$labels['invitationmailbody'] = "*\$title*\n\nTidspunkt: \$date\n\nInviterede: \$attendees\n\nBemærk venligst vedhæftede iCalendar-fil med alle detaljer om arrangementet, som du kan importere til dit kalenderprogram.";
$labels['invitationattendlinks'] = "Hvis dit e-postprogram ikke understøtter iTip-forespørgsler, så kan du benytte følgende henvisning til enten at acceptere eller afvise denne invitation:\n\$url";
$labels['eventupdatesubject'] = '"$title" er blevet opdateret';
$labels['eventupdatesubjectempty'] = 'Et arrangement der vedrører dig er blevet opdateret';
$labels['eventupdatemailbody'] = "*\$title*\n\nTidspunkt: \$date\n\nInviterede: \$attendees\n\nBemærk venligst vedhæftede iCalendar-fil med alle detaljer om arrangementet, som du kan importere til dit kalenderprogram.";
$labels['eventcancelsubject'] = '"$title" er blevet aflyst';
$labels['eventcancelmailbody'] = "*\$title*\n\nTidspunkt: \$date\n\nInviterede: \$attendees\n\nDette arrangement er blevet aflyst af \$organizer.\n\nBemærk venligst vedhæftede iCalendard-fil med de opdaterede detaljer om arrangementet.";

// invitation handling (overrides labels from libcalendaring)
$labels['itipobjectnotfound'] = 'The event referred by this message was not found in your calendar.';

$labels['itipmailbodyaccepted'] = "\$sender har accepteret invitationen til det følgende arrangement:\n\n*\$title*\n\nTidspunkt: \$date\n\nInviterede: \$attendees";
$labels['itipmailbodytentative'] = "\$sender har forsøgsvist accepteret invitationen til det følgende arrangement:\n\n*\$title*\n\nTidspunkt: \$date\n\nInviterede: \$attendees";
$labels['itipmailbodydeclined'] = "\$sender har afvist invitationen til det følgende arrangement:\n\n*\$title*\n\nTidspunkt: \$date\n\nInviterede: \$attendees";
$labels['itipmailbodycancel'] = "\$sender has rejected your participation in the following event:\n\n*\$title*\n\nWhen: \$date";
$labels['itipmailbodydelegated'] = "\$sender has delegated the participation in the following event:\n\n*\$title*\n\nWhen: \$date";
$labels['itipmailbodydelegatedto'] = "\$sender has delegated the participation in the following event to you:\n\n*\$title*\n\nWhen: \$date";

$labels['itipdeclineevent'] = 'Sikker på at du vil afvise dette arrangement?';
$labels['declinedeleteconfirm'] = 'Vil du også slette dette afviste arrangement fra din kalender?';
$labels['itipcomment'] = 'Invitation/notification comment';
$labels['itipcommenttitle'] = 'This comment will be attached to the invitation/notification message sent to participants';

$labels['notanattendee'] = 'Du er ikke opført som deltager for dette arrangement';
$labels['eventcancelled'] = 'Arrangementet er blevet aflyst';
$labels['saveincalendar'] = 'gem i';
$labels['updatemycopy'] = 'Update in my calendar';
$labels['savetocalendar'] = 'Save to calendar';
$labels['openpreview'] = 'Check Calendar';
$labels['noearlierevents'] = 'No earlier events';
$labels['nolaterevents'] = 'No later events';

// resources
$labels['resource'] = 'Ressource';
$labels['addresource'] = 'Book resource';
$labels['findresources'] = 'Find resources';
$labels['resourcedetails'] = 'Detaljer';
$labels['resourceavailability'] = 'Availability';
$labels['resourceowner'] = 'Owner';
$labels['resourceadded'] = 'The resource was added to your event';

// event dialog tabs
$labels['tabsummary'] = 'Resumé';
$labels['tabrecurrence'] = 'Gentagelse';
$labels['tabattendees'] = 'Deltagere';
$labels['tabresources'] = 'Ressourcer';
$labels['tabattachments'] = 'Vedhæftninger';
$labels['tabsharing'] = 'Deling';

// messages
$labels['deleteobjectconfirm'] = 'Sikker på at du vil slette dette arrangement?';
$labels['deleteventconfirm'] = 'Sikker på at du vil slette dette arrangement?';
$labels['deletecalendarconfirm'] = 'Sikker på at du vil slette denne kalender med alle dets arrangementer?';
$labels['deletecalendarconfirmrecursive'] = 'Sikker på du vil slette denne kalender med alle dens arrangementer og delkalendere?';
$labels['savingdata'] = 'Gemmer data...';
$labels['errorsaving'] = 'Kunne ikke gemme ændringer.';
$labels['operationfailed'] = 'Den forespurgte handling mislykkedes.';
$labels['invalideventdates'] = 'Ugyldig dato indtastet! Tjek venligst dit input.';
$labels['invalidcalendarproperties'] = 'Ugyldige kalenderegenskaber! Angiv venligst et gyldigt navn.';
$labels['searchnoresults'] = 'Der blev ikke fundet arrangementer i de valgte kalendere.';
$labels['successremoval'] = 'Sletning af arrangementet blev gennemført.';
$labels['successrestore'] = 'Gendannelse af arrangementet blev gennemført.';
$labels['errornotifying'] = 'Kunne ikke sende notifikation til arrangementets deltagere';
$labels['errorimportingevent'] = 'Kunne ikke importere arrangementet';
$labels['importwarningexists'] = 'A copy of this event already exists in your calendar.';
$labels['newerversionexists'] = 'Der findes allerede en nyere version af arrangementet! Afbrød.';
$labels['nowritecalendarfound'] = 'Ingen funden kalender til lagring af arrangementet';
$labels['importedsuccessfully'] = 'Arrangementet blev tilføjet til \'$calendar\'';
$labels['updatedsuccessfully'] = 'The event was successfully updated in \'$calendar\'';
$labels['attendeupdateesuccess'] = 'Opdatering af deltagernes status blev gennemført';
$labels['itipsendsuccess'] = 'Invitation blev sendt til deltagerne.';
$labels['itipresponseerror'] = 'Kunne ikke sende svar til denne arrangementsinvitation';
$labels['itipinvalidrequest'] = 'Denne invitation er ikke længere gyldig';
$labels['sentresponseto'] = 'Gennemførte afsendelse af invitationssvar til $mailto';
$labels['localchangeswarning'] = 'Du er i færd med at foretage ændringer, der vil påvirke din kalender og som ikke vil blive sendt til afholderen af arrangementet.';
$labels['importsuccess'] = 'Gennemførte import af $nr arrangementer';
$labels['importnone'] = 'Fandt ingen arrangementer som kunne importeres';
$labels['importerror'] = 'Der opstod en fejl under import';
$labels['aclnorights'] = 'Du har ikke administratorrettigheder for denne kalender.';

$labels['changeeventconfirm'] = 'Tilpas arrangement';
$labels['removeeventconfirm'] = 'Delete event';
$labels['changerecurringeventwarning'] = 'Dette er et tilbagevendende arrangement. Ønsker du kun at redige det aktuelle arrangement, dette og alle fremtidige forekomster, alle forekomster eller gemme det som et nyt arrangement?';
$labels['removerecurringeventwarning'] = 'This is a recurring event. Would you like to delete the current event only, this and all future occurences or all occurences of this event?';
$labels['currentevent'] = 'Nuværende';
$labels['futurevents'] = 'Fremtid';
$labels['allevents'] = 'Alle';
$labels['saveasnew'] = 'Gem som ny';

// birthdays calendar
$labels['birthdays'] = 'Birthdays';
$labels['birthdayscalendar'] = 'Birthdays Calendar';
$labels['displaybirthdayscalendar'] = 'Display birthdays calendar';
$labels['birthdayscalendarsources'] = 'From these address books';
$labels['birthdayeventtitle'] = '$name\'s Birthday';
$labels['birthdayage'] = 'Age $age';

// history dialog
$labels['eventchangelog'] = 'Change History';
$labels['eventdiff'] = 'Changes from revisions $rev';
$labels['revision'] = 'Revision';
$labels['user'] = 'Bruger';
$labels['operation'] = 'Action';
$labels['actionappend'] = 'Saved';
$labels['actionmove'] = 'Moved';
$labels['actiondelete'] = 'Slettet';
$labels['compare'] = 'Compare';
$labels['showrevision'] = 'Show this version';
$labels['restore'] = 'Restore this version';
$labels['eventnotfound'] = 'Failed to load event data';
$labels['eventchangelognotavailable'] = 'Change history is not available for this event';
$labels['eventdiffnotavailable'] = 'No comparison possible for the selected revisions';
$labels['eventrestoreconfirm'] = 'Do you really want to restore revision $rev of this event? This will replace the current event with the old version.';


// (hidden) titles and labels for accessibility annotations
$labels['arialabelminical'] = 'Calendar date selection';
$labels['arialabelcalendarview'] = 'Calendar view';
$labels['arialabelsearchform'] = 'Event search form';
$labels['arialabelquicksearchbox'] = 'Event search input';
$labels['arialabelcalsearchform'] = 'Calendars search form';
$labels['calendaractions'] = 'Calendar actions';
$labels['arialabeleventattendees'] = 'Event participants list';
$labels['arialabeleventresources'] = 'Event resources list';
$labels['arialabelresourcesearchform'] = 'Resources search form';
$labels['arialabelresourceselection'] = 'Available resources';

?>
