<?php
/**
 * Localizations for Kolab Calendar plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/calendar/
 */
$labels['name'] = 'Nombre';
$labels['color'] = 'Color';
$labels['edit'] = 'Editar';
$labels['remove'] = 'Remove';
$labels['repeat'] = 'Repeat';
$labels['status'] = 'Status';
$labels['comment'] = 'Comentario';
$labels['unknown'] = 'Unknown';
$labels['eventoptions'] = 'Opciones';
$labels['andnmore'] = '$nr more...';
$labels['until'] = 'until';
$labels['role'] = 'Rol';
$labels['availability'] = 'Avail.';
$labels['confirmstate'] = 'Status';
$labels['roleorganizer'] = 'Organizer';
$labels['rolerequired'] = 'Requerido';
$labels['roleoptional'] = 'Opcional';
$labels['rolechair'] = 'Chair';
$labels['cutyperesource'] = 'Recurso';
$labels['availunknown'] = 'Unknown';
$labels['sendinvitations'] = 'Send invitations';
$labels['eventupdatesubject'] = '"$title" has been updated';
$labels['eventcancelsubject'] = '"$title" has been canceled';
$labels['resource'] = 'Recurso';
$labels['resourcedetails'] = 'Detalles';
$labels['tabresources'] = 'Recursos';
$labels['tabsharing'] = 'Sharing';
$labels['savingdata'] = 'Guardando datos...';
$labels['attendeupdateesuccess'] = 'Successfully updated the participant\'s status';
$labels['itipinvalidrequest'] = 'This invitation is no longer valid';
$labels['user'] = 'Usuario';
$labels['operation'] = 'Acción';
?>
