<?php
// preferences
// calendar
$labels['name'] = 'Nombre';
$labels['remove'] = 'Remove';
$labels['status'] = 'Status';
// agenda view
// alarm/reminder settings
// attendees
$labels['confirmstate'] = 'Status';
$labels['cutyperesource'] = 'Recurso';
// invitation handling (overrides labels from libcalendaring)
// resources
$labels['resource'] = 'Recurso';
$labels['resourcedetails'] = 'Detalles';
// event dialog tabs
$labels['tabresources'] = 'Recursos';
// messages
// recurrence form
// birthdays calendar
?>
