<?php
/**
 * Localizations for Kolab Calendar plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/calendar/
 */
$labels['name'] = 'Nimi';
$labels['color'] = 'Color';
$labels['edit'] = 'Edit';
$labels['remove'] = 'Remove';
$labels['title'] = 'Summary';
$labels['description'] = 'Description';
$labels['location'] = 'Location';
$labels['url'] = 'URL';
$labels['start'] = 'Start';
$labels['end'] = 'End';
$labels['repeat'] = 'Repeat';
$labels['status'] = 'Status';
$labels['priority'] = 'Priority';
$labels['comment'] = 'Kommentaar';
$labels['unknown'] = 'Unknown';
$labels['andnmore'] = '$nr more...';
$labels['until'] = 'until';
$labels['role'] = 'Role';
$labels['availability'] = 'Avail.';
$labels['confirmstate'] = 'Status';
$labels['roleorganizer'] = 'Organizer';
$labels['rolerequired'] = 'Kohustuslik';
$labels['roleoptional'] = 'Optional';
$labels['rolechair'] = 'Chair';
$labels['cutyperesource'] = 'Resource';
$labels['availunknown'] = 'Unknown';
$labels['sendinvitations'] = 'Send invitations';
$labels['eventupdatesubject'] = '"$title" has been updated';
$labels['eventcancelsubject'] = '"$title" has been canceled';
$labels['resource'] = 'Resource';
$labels['tabsummary'] = 'Summary';
$labels['tabsharing'] = 'Sharing';
$labels['savingdata'] = 'Saving data...';
$labels['attendeupdateesuccess'] = 'Successfully updated the participant\'s status';
$labels['itipinvalidrequest'] = 'This invitation is no longer valid';
$labels['allevents'] = 'All';
$labels['operation'] = 'Toiming';
?>
