<?php
// preferences
// calendar
$labels['name'] = 'Nimi';
$labels['remove'] = 'Remove';
$labels['status'] = 'Status';
// agenda view
// alarm/reminder settings
// attendees
$labels['confirmstate'] = 'Status';
$labels['cutyperesource'] = 'Resource';
// invitation handling (overrides labels from libcalendaring)
// resources
$labels['resource'] = 'Resource';
// event dialog tabs
// messages
// recurrence form
// birthdays calendar
?>
