<?php
// preferences
$labels['time_format'] = 'Format datuma';
$labels['first_day'] = 'Prvi dan tjedna';
$labels['first_hour'] = 'Prvi sat za prikaz';
$labels['workinghours'] = 'Radni sati';
$labels['add_category'] = 'Dodaj kategoriju';
$labels['remove_category'] = 'Obriši kategoriju';
$labels['defaultcalendar'] = 'Kreiraj nove događaje u';
$labels['eventcoloring'] = 'Bojanje događaja';
$labels['coloringmode0'] = 'Prema kalendaru';
$labels['coloringmode1'] = 'Prema kategoriji';
// calendar
$labels['calendar'] = 'Kalendar';
$labels['calendars'] = 'Kalendari';
$labels['category'] = 'Kategorija';
$labels['categories'] = 'Kategorije';
// agenda view
// alarm/reminder settings
// attendees
// invitation handling (overrides labels from libcalendaring)
// resources
// event dialog tabs
// messages
// recurrence form
// birthdays calendar
?>
