<?php

$labels = array();

// preferences
$labels['default_view'] = 'Alap nézet';
$labels['time_format'] = 'Idõ formátum';
$labels['first_day'] = 'A hét elsõ napja';

// calendar
$labels['calendar'] = 'Naptár';
$labels['category'] = 'Kategória';
$labels['day'] = 'Nap';
$labels['week'] = 'Hét';
$labels['month'] = 'Hónap';
$labels['new_event'] = 'Új bejegyzés';
$labels['edit_event'] = 'Bejegyzés szerkesztése';
$labels['save'] = 'Mentés';
$labels['remove'] = 'Törlés';
$labels['cancel'] = 'Mégse';
$labels['title'] = 'Tárgy';
$labels['description'] = 'Leírás';
$labels['all-day'] = 'Egész nap';
$labels['export'] = 'Exportálás ICS formátumba';

?>
