<?php

/**
 * Localizations for Kolab Calendar plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/calendar/
 */

$labels = array();

// preferences
$labels['default_view'] = 'Alapnézett nézet';
$labels['time_format'] = 'Idő formátum';
$labels['timeslots'] = 'Órák felbontása időrésekre';
$labels['first_day'] = 'A hét első napja';
$labels['first_hour'] = 'Kezdő óra';
$labels['workinghours'] = 'Munkaidő';
$labels['add_category'] = 'Kategória hozzáadása';
$labels['remove_category'] = 'Kategória törlése';
$labels['defaultcalendar'] = 'Új események alapértelmezett helye';
$labels['eventcoloring'] = 'Események színezése';
$labels['coloringmode0'] = 'Naptár szerint';
$labels['coloringmode1'] = 'Kategória szerint';
$labels['coloringmode2'] = 'Naptár színe körvonal, kategória színe belsőrész';
$labels['coloringmode3'] = 'Kategória színe körvonal, naptár színe belsőrész';
$labels['afternothing'] = 'Do nothing';
$labels['aftertrash'] = 'Move to Trash';
$labels['afterdelete'] = 'Delete the message';
$labels['afterflagdeleted'] = 'Flag as deleted';
$labels['aftermoveto'] = 'Move to...';
$labels['itipoptions'] = 'Event Invitations';
$labels['afteraction'] = 'After an invitation or update message is processed';

// calendar
$labels['calendar'] = 'Naptár';
$labels['calendars'] = 'Naptárak';
$labels['category'] = 'Kategória';
$labels['categories'] = 'Kategóriák';
$labels['createcalendar'] = 'Új naptár létrehozása';
$labels['editcalendar'] = 'Naptár tulajdonságai';
$labels['name'] = 'Név';
$labels['color'] = 'Szín';
$labels['day'] = 'Nap';
$labels['week'] = 'Hét';
$labels['month'] = 'Hónap';
$labels['agenda'] = 'Napirend';
$labels['new'] = 'Új';
$labels['new_event'] = 'Új esemény';
$labels['edit_event'] = 'Esemény módosítása';
$labels['edit'] = 'Módosítás';
$labels['save'] = 'Mentés';
$labels['removelist'] = 'Remove from list';
$labels['cancel'] = 'Mégse';
$labels['select'] = 'Jelölés';
$labels['print'] = 'Nyomtatás';
$labels['printtitle'] = 'Naptárak nyomtatása';
$labels['title'] = 'Tárgy';
$labels['description'] = 'Leírás';
$labels['all-day'] = 'Egész nap';
$labels['export'] = 'Exportálás';
$labels['exporttitle'] = 'Exportálás iCalendar-ba';
$labels['exportrange'] = 'Visszamenőleg';
$labels['exportattachments'] = 'Csatolmányokkal';
$labels['customdate'] = 'Megadott dátumig';
$labels['location'] = 'Hol';
$labels['url'] = 'URL';
$labels['date'] = 'Dátum';
$labels['start'] = 'Kezdet';
$labels['starttime'] = 'Start time';
$labels['end'] = 'Vég';
$labels['endtime'] = 'End time';
$labels['repeat'] = 'Ismétlődés';
$labels['selectdate'] = 'Válasszon dátumot';
$labels['freebusy'] = 'Foglaltság';
$labels['free'] = 'Szabad';
$labels['busy'] = 'Foglalt';
$labels['outofoffice'] = 'Házon kívűl';
$labels['tentative'] = 'Feltételes';
$labels['mystatus'] = 'My status';
$labels['status'] = 'Stát.';
$labels['status-confirmed'] = 'Confirmed';
$labels['status-cancelled'] = 'Cancelled';
$labels['priority'] = 'Prioritás';
$labels['sensitivity'] = 'Manánszféra';
$labels['public'] = 'publikus';
$labels['private'] = 'privát';
$labels['confidential'] = 'titkos';
$labels['alarms'] = 'Emlékeztető';
$labels['comment'] = 'Megjegyzés';
$labels['created'] = 'Created';
$labels['changed'] = 'Last Modified';
$labels['unknown'] = 'Ismeretlen foglaltság';
$labels['eventoptions'] = 'Options';
$labels['generated'] = 'készítve:';
$labels['eventhistory'] = 'History';
$labels['printdescriptions'] = 'Leírás nyomtatása';
$labels['parentcalendar'] = 'Szülőnaptár';
$labels['searchearlierdates'] = '< Korábbi események keresése';
$labels['searchlaterdates'] = 'Későbbi események keresése >';
$labels['andnmore'] = 'még $nr ...';
$labels['togglerole'] = 'Kattintson a szerepváltáshoz';
$labels['createfrommail'] = 'Mentés naptári eseményként';
$labels['importevents'] = 'Események importálása';
$labels['importrange'] = 'Visszamenőleg';
$labels['onemonthback'] = '1 hónapra';
$labels['nmonthsback'] = '$nr hónapra';
$labels['showurl'] = 'Naptár URL címe';
$labels['showurldescription'] = 'Ezen a címen érhető el (csak olvasásra!) a naptár más alkalmazások számára, iCal formátumban.';
$labels['caldavurldescription'] = 'Másolja be ezt a címet egy <a href="http://en.wikipedia.org/wiki/CalDAV" target="_blank">CalDAV</a>-kompatibilis kliensbe (pl. Evolution vagy Mozilla Thunderbird) hogy kétirányú szinkronizációval tudjon a naptárához hozzáférni.';
$labels['findcalendars'] = 'Find calendars...';
$labels['searchterms'] = 'Search terms';
$labels['calsearchresults'] = 'Available Calendars';
$labels['calendarsubscribe'] = 'List permanently';
$labels['nocalendarsfound'] = 'No calendars found';
$labels['nrcalendarsfound'] = '$nr calendars found';
$labels['quickview'] = 'View only this calendar';
$labels['invitationspending'] = 'Pending invitations';
$labels['invitationsdeclined'] = 'Declined invitations';
$labels['changepartstat'] = 'Change participant status';
$labels['rsvpcomment'] = 'Invitation text';

// agenda view
$labels['listrange'] = 'Megjelenítés:';
$labels['listsections'] = 'Felosztás:';
$labels['smartsections'] = 'Áttekintve';
$labels['until'] = 'eddig';
$labels['today'] = 'Ma';
$labels['tomorrow'] = 'Holnap';
$labels['thisweek'] = 'Ezen a héten';
$labels['nextweek'] = 'Jövő héten';
$labels['prevweek'] = 'Previous week';
$labels['thismonth'] = 'Ebben a hónapban';
$labels['nextmonth'] = 'Jövő hónapban';
$labels['weekofyear'] = 'Hét:';
$labels['pastevents'] = 'Múltban';
$labels['futureevents'] = 'Jövőben';

// alarm/reminder settings
$labels['showalarms'] = 'Emlékeztetők megjelenítése';
$labels['defaultalarmtype'] = 'Alapértelmezett emlékeztető';
$labels['defaultalarmoffset'] = 'Alapértelmezett emlékeztető ideje';

// attendees
$labels['attendee'] = 'Résztvevő';
$labels['role'] = 'Szerepkör';
$labels['availability'] = 'Elérh.';
$labels['confirmstate'] = 'Stát.';
$labels['addattendee'] = 'Résztvevő meghívása';
$labels['roleorganizer'] = 'Szervező';
$labels['rolerequired'] = 'Kötelező';
$labels['roleoptional'] = 'Opcionális';
$labels['rolechair'] = 'Elnöklő';
$labels['rolenonparticipant'] = 'Hiányzó';
$labels['cutypeindividual'] = 'Egyén';
$labels['cutypegroup'] = 'Csoport';
$labels['cutyperesource'] = 'Eszköz';
$labels['cutyperoom'] = 'Helyiség';
$labels['availfree'] = 'Szabad';
$labels['availbusy'] = 'Foglalt';
$labels['availunknown'] = 'Ismeretlen foglaltság';
$labels['availtentative'] = 'Feltételes';
$labels['availoutofoffice'] = 'Házon kívül';
$labels['delegatedto'] = 'Beosztva ide: ';
$labels['delegatedfrom'] = 'Beosztva innen: ';
$labels['scheduletime'] = 'Elérhetőség';
$labels['sendinvitations'] = 'Meghívók küldése';
$labels['sendnotifications'] = 'Résztvevők értesítése a változásokról';
$labels['sendcancellation'] = 'Résztvevők értesítése a lemondásról';
$labels['onlyworkinghours'] = 'Elérhetőség figyelembevétele csak az én munkaidőmben';
$labels['reqallattendees'] = 'Mindenki részére';
$labels['prevslot'] = 'Előző idősáv';
$labels['nextslot'] = 'Következő idősáv';
$labels['suggestedslot'] = 'Suggested Slot';
$labels['noslotfound'] = 'Nem sikerült szabad idősávot találni';
$labels['invitationsubject'] = '$title';
$labels['invitationmailbody'] = "Meghívó érkezett '\$title' eseményre.\n\nIdőpont: \$date\nSzervező: \$organizer\nRésztvevők: \$attendees\n\n\nMellékletben egy iCalendar naptárbejegyzés, mely tetszőleges naptárprogramba importálható.";
$labels['invitationattendlinks'] = "Amennyiben a levelezőben nem lát elfogadó/elutasító gombokat (a levelező program nem támogatja az iTip üzeneteket), kattintson ide a meghívó elfogadására, vagy elutasítására:\n\$url";
$labels['eventupdatesubject'] = '$title - módosítva';
$labels['eventupdatesubjectempty'] = 'Egy Önt érintő esemény módosítva lett';
$labels['eventupdatemailbody'] = "Módosítás érkezett '\$title' eseményre vonatkozóan.\n\nIdőpont: \$date\nSzervező: \$organizer\nRésztvevők: \$attendees\n\n\nMellékletben egy frissített iCalendar naptárbejegyzés, mely tetszőleges naptárprogramba importálható.";
$labels['eventcancelsubject'] = '$title - lemondva';
$labels['eventcancelmailbody'] = "'\$title' eseményre \$organizer szervező visszavonta a meghívást.\n\nIdőpont: \$date\nRésztvevők: \$attendees\n\n\nMellékletben egy frissített iCalendar naptárbejegyzés, mely tetszőleges naptárprogramba importálható.";

// invitation handling (overrides labels from libcalendaring)
$labels['itipobjectnotfound'] = 'Az üzenetben hivatkozott esemény nem található a naptárban.';

$labels['itipmailbodyaccepted'] = "\$sender elfogadta a meghívást '\$title' eseményre.\n\nIdőpont: \$date\nRésztvevők: \$attendees";
$labels['itipmailbodytentative'] = "\$sender feltételesen elfogadta a meghívást '\$title' eseményre.\n\nIdőpont: \$date\nRésztvevők: \$attendees";
$labels['itipmailbodydeclined'] = "\$sender elutasította a meghívást '\$title' eseményre.\n\nIdőpont: \$date\nRésztvevők: \$attendees";
$labels['itipmailbodycancel'] = "\$sender elutasította a részvételét '\$title' eseményen, \$date időpontra";
$labels['itipmailbodydelegated'] = "\$sender has delegated the participation in the following event:\n\n*\$title*\n\nWhen: \$date";
$labels['itipmailbodydelegatedto'] = "\$sender has delegated the participation in the following event to you:\n\n*\$title*\n\nWhen: \$date";

$labels['itipdeclineevent'] = 'Biztos benne, hogy el szeretné utasítani ezt a meghívást?';
$labels['declinedeleteconfirm'] = 'Ki is szeretné törölni a saját naptárából ezt az időpontot?';
$labels['itipcomment'] = 'Invitation/notification comment';
$labels['itipcommenttitle'] = 'This comment will be attached to the invitation/notification message sent to participants';

$labels['notanattendee'] = 'Ön nem szerepel az esemény meghívottai között';
$labels['eventcancelled'] = 'Az esemény le lett mondva';
$labels['saveincalendar'] = 'Mentés naptárba';
$labels['updatemycopy'] = 'Naptárbejegyzés frissítése';
$labels['savetocalendar'] = 'Save to calendar';
$labels['openpreview'] = 'Check Calendar';
$labels['noearlierevents'] = 'No earlier events';
$labels['nolaterevents'] = 'No later events';

// resources
$labels['resource'] = 'Eszközök';
$labels['addresource'] = 'Eszköz foglalása';
$labels['findresources'] = 'Eszközök keresése';
$labels['resourcedetails'] = 'Részletek';
$labels['resourceavailability'] = 'Elérhetőség';
$labels['resourceowner'] = 'Tulajdonos';
$labels['resourceadded'] = 'Az eszköz le lett foglalva az eseményhez';

// event dialog tabs
$labels['tabsummary'] = 'Részletek';
$labels['tabrecurrence'] = 'Ismétlődés';
$labels['tabattendees'] = 'Résztvevők';
$labels['tabresources'] = 'Eszközök';
$labels['tabattachments'] = 'Csatolmányok';
$labels['tabsharing'] = 'Megosztás';

// messages
$labels['deleteobjectconfirm'] = 'Biztos benne, hogy törölni szeretné ezt az eseményt?';
$labels['deleteventconfirm'] = 'Biztos benne, hogy törölni szeretné ezt az eseményt?';
$labels['deletecalendarconfirm'] = 'Biztos benne, hogy törölni szeretné ezt a naptárat, az összes benne lévő eseménnyel?';
$labels['deletecalendarconfirmrecursive'] = 'Biztos benne, hogy törölni szeretné ezt a naptárat, az összes benne lévő al-naptárral és eseménnyel?';
$labels['savingdata'] = 'Adatok mentése...';
$labels['errorsaving'] = 'A módosításokat nem sikerült elmenteni.';
$labels['operationfailed'] = 'A műveletet nem sikerült elvégezni.';
$labels['invalideventdates'] = 'Helytelen dátumokoat adott meg! Kérem, ellenörizze a bevírt adatokat.';
$labels['invalidcalendarproperties'] = 'Helytelen naptár tulajdonságok! Kérem, adjon meg egy helyes nevet.';
$labels['searchnoresults'] = 'Nem található esemény a kiválasztott naptárakban.';
$labels['successremoval'] = 'Az esemény törlése sikerült.';
$labels['successrestore'] = 'Az esemény sikeresen vissza lett állítva.';
$labels['errornotifying'] = 'Nem sikerült meghívókat küldeni a résztvevőknek.';
$labels['errorimportingevent'] = 'Az esemény importálása sikertelen volt.';
$labels['importwarningexists'] = 'A copy of this event already exists in your calendar.';
$labels['newerversionexists'] = 'Egy újabb verzió már van ebből az eseményből! Itt abbahagytam.';
$labels['nowritecalendarfound'] = 'No calendar found to save the event';
$labels['importedsuccessfully'] = 'Az esemény a \'$calendar\' naptárhoz hozzá lett adva';
$labels['updatedsuccessfully'] = 'The event was successfully updated in \'$calendar\'';
$labels['attendeupdateesuccess'] = 'A résztvevők adatai sikeresen frissítve';
$labels['itipsendsuccess'] = 'Értesítés küldve a résztvevőknek';
$labels['itipresponseerror'] = 'Nem sikerült választ küldeni erre a meghívásra';
$labels['itipinvalidrequest'] = 'Ez a meghívás már érvénytelen';
$labels['sentresponseto'] = 'Értesítésre válasz küldve: $mailto';
$labels['localchangeswarning'] = 'Ezek a változások csak az ön naptárában fognak megjelenni, az esemény szervezőjénél nem.';
$labels['importsuccess'] = '$nr esemény sikeresen importálva lett';
$labels['importnone'] = 'Nem található importálható esemény.';
$labels['importerror'] = 'Hiba importálás közben';
$labels['aclnorights'] = 'Nincs adminisztrátori joga ehhez a naptárhoz';

$labels['changeeventconfirm'] = 'Bejegyzés módosítása';
$labels['removeeventconfirm'] = 'Delete event';
$labels['changerecurringeventwarning'] = 'Ez egy ismétlődő esemény. Csak ezt az előfordulást szeretné módosítani, esetleg ezt az előfordulást az összes következővel, netán a teljes sorozatot, vagy új eseményként legyen mentve?';
$labels['removerecurringeventwarning'] = 'This is a recurring event. Would you like to delete the current event only, this and all future occurences or all occurences of this event?';
$labels['currentevent'] = 'Csak ezt';
$labels['futurevents'] = 'Ezt és a következőeket';
$labels['allevents'] = 'Egész sorozatot';
$labels['saveasnew'] = 'Mentés újként';

// birthdays calendar
$labels['birthdays'] = 'Születésnapok';
$labels['birthdayscalendar'] = 'Születésnapi naptár';
$labels['displaybirthdayscalendar'] = 'Születésnapok megjelenítése';
$labels['birthdayscalendarsources'] = 'Alábbi címjegyzékekből:';
$labels['birthdayeventtitle'] = '$name születésnapja';
$labels['birthdayage'] = '$age éves';

// history dialog
$labels['eventchangelog'] = 'Change History';
$labels['eventdiff'] = 'Changes from revisions $rev';
$labels['revision'] = 'Revision';
$labels['user'] = 'User';
$labels['operation'] = 'Action';
$labels['actionappend'] = 'Saved';
$labels['actionmove'] = 'Moved';
$labels['actiondelete'] = 'Deleted';
$labels['compare'] = 'Compare';
$labels['showrevision'] = 'Show this version';
$labels['restore'] = 'Restore this version';
$labels['eventnotfound'] = 'Failed to load event data';
$labels['eventchangelognotavailable'] = 'Change history is not available for this event';
$labels['eventdiffnotavailable'] = 'No comparison possible for the selected revisions';
$labels['eventrestoreconfirm'] = 'Do you really want to restore revision $rev of this event? This will replace the current event with the old version.';


// (hidden) titles and labels for accessibility annotations
$labels['arialabelminical'] = 'Calendar date selection';
$labels['arialabelcalendarview'] = 'Calendar view';
$labels['arialabelsearchform'] = 'Event search form';
$labels['arialabelquicksearchbox'] = 'Event search input';
$labels['arialabelcalsearchform'] = 'Calendars search form';
$labels['calendaractions'] = 'Calendar actions';
$labels['arialabeleventattendees'] = 'Event participants list';
$labels['arialabeleventresources'] = 'Event resources list';
$labels['arialabelresourcesearchform'] = 'Resources search form';
$labels['arialabelresourceselection'] = 'Available resources';

?>
