<?php
$labels['default_view'] = 'Visualizzazine di default';
$labels['time_format'] = 'Formato ora';
$labels['timeslots'] = 'Timeslots per ora';
$labels['first_day'] = 'Inizio settimana';
$labels['calendar'] = 'Calendario';
$labels['category'] = 'Categoria';
$labels['day'] = 'Giorno';
$labels['week'] = 'Settimana';
$labels['month'] = 'Mese';
$labels['new_event'] = 'Nuovo evento';
$labels['edit_event'] = 'Modifica evento';
$labels['save'] = 'Salva';
$labels['remove'] = 'Elimina';
$labels['cancel'] = 'Annulla';
$labels['title'] = 'Oggetto';
$labels['description'] = 'Descrizione';
$labels['all-day'] = 'Giorno intero';
$labels['export'] = 'Esporta in ICS';
$labels['tabsummary'] = 'Oggetto';
?>
