<?php

$labels = array();

// preferences
$labels['default_view'] = 'Standaard agenda';
$labels['time_format'] = 'Tijdsformaat';
$labels['first_day'] = 'Eerste weekdag';
$labels['first_hour'] = 'Eerste uur om weer te geven';
$labels['workinghours'] = 'Werkuren';
$labels['add_category'] = 'Categorie toevoegen';
$labels['remove_category'] = 'Categorie verwijderen';
$labels['defaultcalendar'] = 'Maak nieuwe afspraken in';
$labels['eventcoloring'] = 'Kleuren van afspraken';
$labels['coloringmode0'] = 'Volgens kalender';
$labels['coloringmode1'] = 'Volgens categorie';
$labels['coloringmode2'] = 'Kalender voor omtrek, categorie voor inhoud';
$labels['coloringmode3'] = 'Categorie voor omtrek, kalender voor inhoud';

// calendar
$labels['calendar'] = 'Agenda';
$labels['calendars'] = 'Kalenders';
$labels['category'] = 'Categorie';
$labels['categories'] = 'Categorieen';
$labels['createcalendar'] = 'Creeer nieuwe kalender';
$labels['editcalendar'] = 'Wijzig calendar eigenschappen';
$labels['name'] = 'Naam';
$labels['color'] = 'Kleur';
$labels['day'] = 'Dag';
$labels['week'] = 'Week';
$labels['month'] = 'Maand';
$labels['agenda'] = 'Agenda';
$labels['new'] = 'Nieuw';
$labels['new_event'] = 'Nieuwe afspraak';
$labels['edit_event'] = 'Wijzig evenement';
$labels['edit'] = 'Wijzig';
$labels['save'] = 'Bewaar';
$labels['remove'] = 'Verwijder';
$labels['cancel'] = 'Terug';
$labels['select'] = 'Selecteer';
$labels['print'] = 'Print';
$labels['printtitle'] = 'Print kalenders';
$labels['title'] = 'Samenvatting';
$labels['description'] = 'Beschrijving';
$labels['all-day'] = 'hele dag';
$labels['export'] = 'Exporteer naar ICS';
$labels['exporttitle'] = 'Als iCalender exporteren';
$labels['exportrange'] = 'Events from';
$labels['location'] = 'Locatie';
$labels['url'] = 'URL';
$labels['date'] = 'Datum';
$labels['start'] = 'Begin';
$labels['end'] = 'Eind';
$labels['selectdate'] = 'Kies datum';
$labels['freebusy'] = 'Toon mij als';
$labels['free'] = 'Vrij';
$labels['busy'] = 'Bezig';
$labels['outofoffice'] = 'Niet Aanwezig';
$labels['tentative'] = 'Misschien';
$labels['priority'] = 'Prioriteit';
$labels['sensitivity'] = 'Privacy';
$labels['public'] = 'publiek';
$labels['private'] = 'prive';
$labels['confidential'] = 'vertrouwelijk';
$labels['alarms'] = 'Herinnering';
$labels['generated'] = 'gegenereerd op';
$labels['printdescriptions'] = 'Print beschrijvingen';
$labels['parentcalendar'] = 'Insert inside';
$labels['searchearlierdates'] = '« Zoek voor eerdere evenementen';
$labels['searchlaterdates'] = 'Zoek voor latere evenementen »';
$labels['andnmore'] = '$nr meer...';
$labels['togglerole'] = 'Click to toggle role';
$labels['createfrommail'] = 'Bewaar als evenement';
$labels['importevents'] = 'Evenementen importeren';
$labels['importrange'] = 'Events from';
$labels['onemonthback'] = '1 maand terug';
$labels['nmonthsback'] = '$nr maanden terug';
$labels['showurl'] = 'Toon kalender URL';
$labels['showurldescription'] = 'Use the following address to access (read only) your calendar from other applications. You can copy and paste this into any calendar software that supports the iCal format.';
$labels['caldavurldescription'] = 'Copy this address to a <a href="http://en.wikipedia.org/wiki/CalDAV" target="_blank">CalDAV</a> client application (e.g. Evolution or Mozilla Thunderbird) to fully synchronize this specific calendar with your computer or mobile device.';

// agenda view
$labels['listrange'] = 'Range to display:';
$labels['listsections'] = 'Verdeel in:';
$labels['smartsections'] = 'Smart sections';
$labels['until'] = 'tot';
$labels['today'] = 'Vandaag';
$labels['tomorrow'] = 'Morgen';
$labels['thisweek'] = 'Deze week';
$labels['nextweek'] = 'Volgende week';
$labels['thismonth'] = 'Deze maand';
$labels['nextmonth'] = 'Volgende maand';
$labels['weekofyear'] = 'Week';
$labels['pastevents'] = 'Verleden';
$labels['futureevents'] = 'Toekomst';

// alarm/reminder settings
$labels['showalarms'] = 'Show reminders';
$labels['defaultalarmtype'] = 'Standaard herinnering instelling';
$labels['defaultalarmoffset'] = 'Standaard herinnering tijd';

// attendees
$labels['attendee'] = 'Deelnemer';
$labels['role'] = 'Rol';
$labels['availability'] = 'Beschikb.';
$labels['confirmstate'] = 'Status';
$labels['addattendee'] = 'Deelnemer toevoegen';
$labels['roleorganizer'] = 'Organisatie';
$labels['rolerequired'] = 'Verplicht';
$labels['roleoptional'] = 'Optioneel';
$labels['rolechair'] = 'Chair';
$labels['rolenonparticipant'] = 'Absent';
$labels['cutypeindividual'] = 'Individual';
$labels['cutypegroup'] = 'Groep';
$labels['cutyperesource'] = 'Middel';
$labels['availfree'] = 'Vrij';
$labels['availbusy'] = 'Bezig';
$labels['availunknown'] = 'Onbekend';
$labels['availtentative'] = 'Misschien';
$labels['availoutofoffice'] = 'Niet Aanwezig';
$labels['scheduletime'] = 'Vind beschikbaarheid';
$labels['sendinvitations'] = 'Verzend uitnodigingen';
$labels['invitationsubject'] = 'U bent uitgenodigd voor "$title"';

$labels['eventcancelled'] = 'Dit evenement is afgelast';
$labels['saveincalendar'] = 'bewaar in';

// event dialog tabs
$labels['tabsummary'] = 'Samenvatting';
$labels['tabrecurrence'] = 'Herhaling';
$labels['tabattendees'] = 'Deelnemers';
$labels['tabattachments'] = 'Toebehoren';
$labels['tabsharing'] = 'Delen';

// messages
$labels['savingdata'] = 'Data wordt opgeslagen...';

// recurrence form
$labels['repeat'] = 'Herhaal';
$labels['frequency'] = 'Herhaal';
$labels['never'] = 'nooit';
$labels['daily'] = 'dagelijks';
$labels['weekly'] = 'weekelijks';
$labels['monthly'] = 'maandelijks';
$labels['yearly'] = 'jaarlijks';
$labels['every'] = 'Elke';
$labels['days'] = 'dag(en)';
$labels['weeks'] = 'week / weken';
$labels['months'] = 'maand(en)';
$labels['years'] = 'year(s) in:';
$labels['bydays'] = 'Op';
$labels['untildate'] = 'de';
$labels['each'] = 'Elke';
$labels['onevery'] = 'Op elke';
$labels['onsamedate'] = 'Op dezelfde datum';
$labels['forever'] = 'oneindig';
$labels['recurrencend'] = 'tot';
$labels['forntimes'] = 'voor $nr keer';
$labels['first'] = 'eerste';
$labels['second'] = 'tweede';
$labels['third'] = 'derde';
$labels['fourth'] = 'vierde';
$labels['last'] = 'laatste';
$labels['dayofmonth'] = 'Dag van de maand';

$labels['changeeventconfirm'] = 'Wijzig evenement';
$labels['removeeventconfirm'] = 'Verwijder evenement';
$labels['currentevent'] = 'Huidige';
$labels['futurevents'] = 'Toekomst';
$labels['allevents'] = 'Alle';
$labels['saveasnew'] = 'Bewaar als nieuw';

?>
