<?php

/**
 * Localizations for Kolab Calendar plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/calendar/
 */

$labels = array();

// preferences
$labels['default_view'] = 'Standaard agenda';
$labels['time_format'] = 'Tijdsformaat';
$labels['timeslots'] = 'Tijdsdelen per uur';
$labels['first_day'] = 'Eerste weekdag';
$labels['first_hour'] = 'Eerste uur om weer te geven';
$labels['workinghours'] = 'Werkuren';
$labels['add_category'] = 'Categorie toevoegen';
$labels['remove_category'] = 'Categorie verwijderen';
$labels['defaultcalendar'] = 'Maak nieuwe afspraken in';
$labels['eventcoloring'] = 'Kleuren van afspraken';
$labels['coloringmode0'] = 'Volgens kalender';
$labels['coloringmode1'] = 'Volgens categorie';
$labels['coloringmode2'] = 'Kalender voor omtrek, categorie voor inhoud';
$labels['coloringmode3'] = 'Categorie voor omtrek, kalender voor inhoud';
$labels['afternothing'] = 'Do nothing';
$labels['aftertrash'] = 'Move to Trash';
$labels['afterdelete'] = 'Delete the message';
$labels['afterflagdeleted'] = 'Flag as deleted';
$labels['aftermoveto'] = 'Move to...';
$labels['itipoptions'] = 'Event Invitations';
$labels['afteraction'] = 'After an invitation or update message is processed';

// calendar
$labels['calendar'] = 'Kalender';
$labels['calendars'] = 'Kalenders';
$labels['category'] = 'Categorie';
$labels['categories'] = 'Categorieën';
$labels['createcalendar'] = 'Maak een nieuwe kalender';
$labels['editcalendar'] = 'Wijzig kalender eigenschappen';
$labels['name'] = 'Naam';
$labels['color'] = 'Kleur';
$labels['day'] = 'Dag';
$labels['week'] = 'Week';
$labels['month'] = 'Maand';
$labels['agenda'] = 'Agenda';
$labels['new'] = 'Nieuw';
$labels['new_event'] = 'Nieuwe afspraak';
$labels['edit_event'] = 'Wijzig afspraak';
$labels['edit'] = 'Wijzig';
$labels['save'] = 'Bewaar';
$labels['removelist'] = 'Remove from list';
$labels['cancel'] = 'Terug';
$labels['select'] = 'Selecteer';
$labels['print'] = 'Afdrukken';
$labels['printtitle'] = 'Kalenders afdrukken';
$labels['title'] = 'Samenvatting';
$labels['description'] = 'Omschrijving';
$labels['all-day'] = 'hele dag';
$labels['export'] = 'Exporteer naar ICS';
$labels['exporttitle'] = 'Als iCalender exporteren';
$labels['exportrange'] = 'Afspraken uit';
$labels['exportattachments'] = 'Exporteer bijlages';
$labels['customdate'] = 'Aangepaste datumweergave';
$labels['location'] = 'Locatie';
$labels['url'] = 'URL';
$labels['date'] = 'Datum';
$labels['start'] = 'Begin';
$labels['starttime'] = 'Start time';
$labels['end'] = 'Eind';
$labels['endtime'] = 'End time';
$labels['repeat'] = 'Herhaal';
$labels['selectdate'] = 'Kies datum';
$labels['freebusy'] = 'Toon mij als';
$labels['free'] = 'Vrij';
$labels['busy'] = 'Bezet';
$labels['outofoffice'] = 'Niet Aanwezig';
$labels['tentative'] = 'Misschien';
$labels['mystatus'] = 'My status';
$labels['status'] = 'Status';
$labels['status-confirmed'] = 'Bevestigd';
$labels['status-cancelled'] = 'Afgelast';
$labels['priority'] = 'Prioriteit';
$labels['sensitivity'] = 'Zichtbaarheid';
$labels['public'] = 'publiek';
$labels['private'] = 'prive';
$labels['confidential'] = 'vertrouwelijk';
$labels['alarms'] = 'Herinnering';
$labels['comment'] = 'Opmerking';
$labels['created'] = 'Created';
$labels['changed'] = 'Last Modified';
$labels['unknown'] = 'Onbekend';
$labels['eventoptions'] = 'Opties';
$labels['generated'] = 'gegenereerd op';
$labels['eventhistory'] = 'History';
$labels['printdescriptions'] = 'Print beschrijvingen';
$labels['parentcalendar'] = 'Voeg toe in';
$labels['searchearlierdates'] = '« Zoek voor eerdere afspraken';
$labels['searchlaterdates'] = 'Zoek voor latere afspraken »';
$labels['andnmore'] = '$nr meer...';
$labels['togglerole'] = 'Klik om van rol te wisselen';
$labels['createfrommail'] = 'Bewaar als afspraak';
$labels['importevents'] = 'Afspraken importeren';
$labels['importrange'] = 'Afspraken vanaf';
$labels['onemonthback'] = '1 maand terug';
$labels['nmonthsback'] = '$nr maanden terug';
$labels['showurl'] = 'Toon kalender URL';
$labels['showurldescription'] = 'Gebruik het volgende adres om uw kalendar te gebruiken (alleen lezen) in andere programma\'s. U kunt dit knippen en plakken in elk kalender programma dat het iCal formaat ondersteunt.';
$labels['caldavurldescription'] = 'Kopieer dit adres in een <a href="http://en.wikipedia.org/wiki/CalDAV" target="_blank">CalDAV</a> programma (bijv. Evolution of Mozilla Thunderbird) om deze specifieke kalender volledig te synchronizeren met je computer of mobiel apparaat.';
$labels['findcalendars'] = 'Vind agenda\'s...';
$labels['searchterms'] = 'Search terms';
$labels['calsearchresults'] = 'Beschikbare agenda\'s';
$labels['calendarsubscribe'] = 'Permanent weergeven';
$labels['nocalendarsfound'] = 'No calendars found';
$labels['nrcalendarsfound'] = '$nr calendars found';
$labels['quickview'] = 'View only this calendar';
$labels['invitationspending'] = 'Pending invitations';
$labels['invitationsdeclined'] = 'Declined invitations';
$labels['changepartstat'] = 'Change participant status';
$labels['rsvpcomment'] = 'Invitation text';

// agenda view
$labels['listrange'] = 'Bereik om te tonen:';
$labels['listsections'] = 'Verdeel in:';
$labels['smartsections'] = 'Slimme secties';
$labels['until'] = 'tot';
$labels['today'] = 'Vandaag';
$labels['tomorrow'] = 'Morgen';
$labels['thisweek'] = 'Deze week';
$labels['nextweek'] = 'Volgende week';
$labels['prevweek'] = 'Previous week';
$labels['thismonth'] = 'Deze maand';
$labels['nextmonth'] = 'Volgende maand';
$labels['weekofyear'] = 'Week';
$labels['pastevents'] = 'Verleden';
$labels['futureevents'] = 'Toekomst';

// alarm/reminder settings
$labels['showalarms'] = 'Toon herinneringen';
$labels['defaultalarmtype'] = 'Instelling standaard herinnering';
$labels['defaultalarmoffset'] = 'Standaard herinneringstijd';

// attendees
$labels['attendee'] = 'Deelnemer';
$labels['role'] = 'Rol';
$labels['availability'] = 'Beschikb.';
$labels['confirmstate'] = 'Status';
$labels['addattendee'] = 'Deelnemer toevoegen';
$labels['roleorganizer'] = 'Organisatie';
$labels['rolerequired'] = 'Verplicht';
$labels['roleoptional'] = 'Optioneel';
$labels['rolechair'] = 'Voorzitter';
$labels['rolenonparticipant'] = 'Afwezig';
$labels['cutypeindividual'] = 'Individueel';
$labels['cutypegroup'] = 'Groep';
$labels['cutyperesource'] = 'Middel';
$labels['cutyperoom'] = 'Kamer';
$labels['availfree'] = 'Vrij';
$labels['availbusy'] = 'Bezet';
$labels['availunknown'] = 'Onbekend';
$labels['availtentative'] = 'Misschien';
$labels['availoutofoffice'] = 'Niet Aanwezig';
$labels['delegatedto'] = 'Gedelegeerd aan';
$labels['delegatedfrom'] = 'Gedelegeerd door';
$labels['scheduletime'] = 'Vind beschikbaarheid';
$labels['sendinvitations'] = 'Verzend uitnodigingen';
$labels['sendnotifications'] = 'Verzend notificaties';
$labels['sendcancellation'] = 'Verzend annulering';
$labels['onlyworkinghours'] = 'Vind beschikbaarheid binnen mijn werkuren';
$labels['reqallattendees'] = 'Verplicht/alle deelnemers';
$labels['prevslot'] = 'vorig voorstel';
$labels['nextslot'] = 'volgend voorstel';
$labels['suggestedslot'] = 'Suggested Slot';
$labels['noslotfound'] = 'Geen voorstel gevonden';
$labels['invitationsubject'] = 'U bent uitgenodigd voor "$title"';
$labels['invitationmailbody'] = "*\$title*\n\nWanneer: \$date\n\nGenodigden: \$attendees\n\nBijgevoegd vindt u een iCalendar bestand met alle details omtrent de afspraak die u kunt importeren in uw kalender programma.";
$labels['invitationattendlinks'] = "In het geval dat uw email programma geen iTip verzoeken aankan, kunt u de volgende link gebruiken om deze uitnodiging te accepteren or af te wijzen :\n\$url";
$labels['eventupdatesubject'] = '"$title" is gewijzigd';
$labels['eventupdatesubjectempty'] = 'Een afspraak is gewijzigd';
$labels['eventupdatemailbody'] = "*\$title*\n\nWanneer: \$date\n\nGenodigden: \$attendees\n\nBijgevoegd vindt u een iCalendar bestand met de gewijzigde details omtrent de afspraak die u kunt importeren in uw kalender programma.";
$labels['eventcancelsubject'] = '"$title" is geannuleerd';
$labels['eventcancelmailbody'] = "*\$title*\n\nWanneer: \$date\n\nGenodigden: \$attendees\n\nDeze afspraak is geannuleerd door \$organizer.\n\nBijgevoegd vindt u een iCalendar bestand met de gewijzigde details omtrent de afspraak";

// invitation handling (overrides labels from libcalendaring)
$labels['itipobjectnotfound'] = 'De afspraak waaraan door dit bericht wordt gereferreerd is niet gevonden in uw kalender.';

$labels['itipmailbodyaccepted'] = "\$sender heeft de uitnodiging geaccepteerd voor de volgende afspraak:\n\n*\$title*\n\nWanneer: \$date\n\nGenodigden: \$attendees";
$labels['itipmailbodytentative'] = "\$sender heeft onder voorbehoud de uitnodiging geaccepteerd voor de volgende afspraak:\n\n*\$title*\n\nWanneer: \$date\n\nGenodigden: \$attendees";
$labels['itipmailbodydeclined'] = "\$sender heeft de uitnodiging afgewezen voor de volgende afspraak:\n\n*\$title*\n\nWanneer: \$date\n\nGenodigden: \$attendees";
$labels['itipmailbodycancel'] = "\$sender heeft je deelname afgewezen voor de volgende afspraak:\n\n*\$title*\n\nWanneer: \$date";
$labels['itipmailbodydelegated'] = "\$sender has delegated the participation in the following event:\n\n*\$title*\n\nWhen: \$date";
$labels['itipmailbodydelegatedto'] = "\$sender has delegated the participation in the following event to you:\n\n*\$title*\n\nWhen: \$date";

$labels['itipdeclineevent'] = 'Wil u de uitnodiging voor deze afspraak afwijzen?';
$labels['declinedeleteconfirm'] = 'Wilt u tevens deze afgewezen uitnodiging verwijderen uit je kalender?';
$labels['itipcomment'] = 'Invitation/notification comment';
$labels['itipcommenttitle'] = 'This comment will be attached to the invitation/notification message sent to participants';

$labels['notanattendee'] = 'U staat niet op de lijst van genodigden voor deze afspraak';
$labels['eventcancelled'] = 'Dit evenement is afgelast';
$labels['saveincalendar'] = 'bewaar in';
$labels['updatemycopy'] = 'Wijzig in mijn kalender';
$labels['savetocalendar'] = 'Opslaan in kalender';
$labels['openpreview'] = 'Check Calendar';
$labels['noearlierevents'] = 'No earlier events';
$labels['nolaterevents'] = 'No later events';

// resources
$labels['resource'] = 'Hulpmiddel';
$labels['addresource'] = 'Voeg hulpmiddel toe';
$labels['findresources'] = 'Vind hulpmiddelen';
$labels['resourcedetails'] = 'Details';
$labels['resourceavailability'] = 'Beschikbaarheid';
$labels['resourceowner'] = 'Eigenaar';
$labels['resourceadded'] = 'Hulpmiddel is toegevoegd aan uw afspraak';

// event dialog tabs
$labels['tabsummary'] = 'Samenvatting';
$labels['tabrecurrence'] = 'Herhaling';
$labels['tabattendees'] = 'Deelnemers';
$labels['tabresources'] = 'Middelen';
$labels['tabattachments'] = 'Toebehoren';
$labels['tabsharing'] = 'Delen';

// messages
$labels['deleteobjectconfirm'] = 'Weet je zeker dat je deze afspraak wilt verwijderen?';
$labels['deleteventconfirm'] = 'Weet u zeker dat u deze afspraak wilt verwijderen?';
$labels['deletecalendarconfirm'] = 'Weet u zeker dat u deze kalender samen met alle afspraken wilt verwijderen?';
$labels['deletecalendarconfirmrecursive'] = 'Weet u zeker dat je deze kalender samen met alle afspraken en er onder hangende kalenders wilt verwijderen?';
$labels['savingdata'] = 'Data wordt opgeslagen...';
$labels['errorsaving'] = 'Opslaan mislukt.';
$labels['operationfailed'] = 'De gevraagde opdracht is mislukt.';
$labels['invalideventdates'] = 'Ongeldige datums ingevoerd! Controleer aub uw invoer.';
$labels['invalidcalendarproperties'] = 'Ongeldige kalender eigenschappen! Gebruik aub een geldige naam.';
$labels['searchnoresults'] = 'Geen afspraken gevonden in de geselecteerde kalenders.';
$labels['successremoval'] = 'De afspraak is succesvol verwijdert.';
$labels['successrestore'] = 'De afspraak is succesvol herstelt';
$labels['errornotifying'] = 'Uitnodigingen versturen naar de genodigden van de afspraak is mislukt';
$labels['errorimportingevent'] = 'Afspraak importeren is mislukt';
$labels['importwarningexists'] = 'Een kopie van deze afspraak bevindt zich al in uw kalender.';
$labels['newerversionexists'] = 'Een nieuwere versie van deze afspraak bestaat! Bewerking afgebroken.';
$labels['nowritecalendarfound'] = 'Geen kalender gevonden om de afspraak in op te slaan';
$labels['importedsuccessfully'] = 'De afspraak is succesvol toegevoegd aan \'$calendar\'';
$labels['updatedsuccessfully'] = 'Het bijwerken van de gebeurtenis in \'$calendar\' is geslaagd';
$labels['attendeupdateesuccess'] = 'Status van genodigde succesvol gewijzigd';
$labels['itipsendsuccess'] = 'Uitnodiging verstuurd aan de genodigden.';
$labels['itipresponseerror'] = 'Antwoord op deze uitnodiging versturen is mislukt';
$labels['itipinvalidrequest'] = 'Deze uitnodiging is niet langer geldig';
$labels['sentresponseto'] = 'Antwoord op deze uitnodiging was succesvol verstuurd aan $mailto';
$labels['localchangeswarning'] = 'U bent bezig wijzigingen te maken die alleen zichtbaar zijn in u eigen kalender en die niet doorgestuurd zullen worden aan de organisator van de afspraak.';
$labels['importsuccess'] = 'Succesvol $nr afspraken geïmporteerd';
$labels['importnone'] = 'Geen afspraken gevonden om te importeren';
$labels['importerror'] = 'Er is een fout tijdens het importeren opgetreden';
$labels['aclnorights'] = 'U heeft geen administratieve rechten op deze kalender.';

$labels['changeeventconfirm'] = 'Wijzig afspraak';
$labels['removeeventconfirm'] = 'Delete event';
$labels['changerecurringeventwarning'] = 'Dit is een terugkerende afspraak. Wilt u alleen de huidige afspraak wijzigen, deze en alle toekomstige afspraken, alle afspraken of opslaan als een nieuwe afspraak?';
$labels['removerecurringeventwarning'] = 'This is a recurring event. Would you like to delete the current event only, this and all future occurences or all occurences of this event?';
$labels['currentevent'] = 'Huidige';
$labels['futurevents'] = 'Toekomstige';
$labels['allevents'] = 'Alle';
$labels['saveasnew'] = 'Bewaar als nieuw';

// birthdays calendar
$labels['birthdays'] = 'Verjaardagen';
$labels['birthdayscalendar'] = 'Verjaardagskalender';
$labels['displaybirthdayscalendar'] = 'Toon verjaardagskalender';
$labels['birthdayscalendarsources'] = 'Uit deze adresboeken';
$labels['birthdayeventtitle'] = 'verjaardag van $name';
$labels['birthdayage'] = 'Leeftijd $age';

// history dialog
$labels['eventchangelog'] = 'Change History';
$labels['eventdiff'] = 'Changes from revisions $rev';
$labels['revision'] = 'Revision';
$labels['user'] = 'Gebruiker';
$labels['operation'] = 'Action';
$labels['actionappend'] = 'Saved';
$labels['actionmove'] = 'Moved';
$labels['actiondelete'] = 'Deleted';
$labels['compare'] = 'Vergelijken';
$labels['showrevision'] = 'Show this version';
$labels['restore'] = 'Restore this version';
$labels['eventnotfound'] = 'Failed to load event data';
$labels['eventchangelognotavailable'] = 'Change history is not available for this event';
$labels['eventdiffnotavailable'] = 'No comparison possible for the selected revisions';
$labels['eventrestoreconfirm'] = 'Do you really want to restore revision $rev of this event? This will replace the current event with the old version.';


// (hidden) titles and labels for accessibility annotations
$labels['arialabelminical'] = 'Calendar date selection';
$labels['arialabelcalendarview'] = 'Calendar view';
$labels['arialabelsearchform'] = 'Event search form';
$labels['arialabelquicksearchbox'] = 'Event search input';
$labels['arialabelcalsearchform'] = 'Calendars search form';
$labels['calendaractions'] = 'Calendar actions';
$labels['arialabeleventattendees'] = 'Event participants list';
$labels['arialabeleventresources'] = 'Event resources list';
$labels['arialabelresourcesearchform'] = 'Resources search form';
$labels['arialabelresourceselection'] = 'Available resources';

?>
