<?php
$labels['calendar'] = 'Kalendarz';
$labels['calendars'] = 'Kalendarze';
$labels['name'] = 'Nazwa';
$labels['edit'] = 'Edytuj';
$labels['save'] = 'Zapisz';
$labels['remove'] = 'Usuń';
$labels['cancel'] = 'Anuluj';
$labels['title'] = 'Podsumowanie';
$labels['description'] = 'Opis';
$labels['start'] = 'Start';
$labels['alarms'] = 'Przypomnienie';
$labels['today'] = 'Dzisiaj';
$labels['tomorrow'] = 'Jutro';
$labels['showalarms'] = 'Pokaż alarmy';
$labels['role'] = 'Rola';
$labels['roleoptional'] = 'Opcjonalny';
$labels['tabsummary'] = 'Podsumowanie';
$labels['tabattachments'] = 'Załączniki';
$labels['savingdata'] = 'Zapisuję dane...';
$labels['allevents'] = 'Wszystkie';
?>
