<?php

/**
 * Localizations for Kolab Calendar plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/calendar/
 */

$labels = array();

// preferences
$labels['default_view'] = 'Visualização padrão';
$labels['time_format'] = 'Formato da hora';
$labels['timeslots'] = 'Time slots per hour';
$labels['first_day'] = 'Primeiro dia da semana';
$labels['first_hour'] = 'Primeira hora a mostrar';
$labels['workinghours'] = 'Horário de trabalho';
$labels['add_category'] = 'Adicionar categoria';
$labels['remove_category'] = 'Remover categoria';
$labels['defaultcalendar'] = 'Criar novos eventos em';
$labels['eventcoloring'] = 'Coloração de evento';
$labels['coloringmode0'] = 'De acordo com o calendário';
$labels['coloringmode1'] = 'De acordo com a categoria';
$labels['coloringmode2'] = 'Calendário para esboço, categoria para conteúdo';
$labels['coloringmode3'] = 'Categoria para esboço, calendário para conteúdo';
$labels['afternothing'] = 'Do nothing';
$labels['aftertrash'] = 'Move to Trash';
$labels['afterdelete'] = 'Delete the message';
$labels['afterflagdeleted'] = 'Flag as deleted';
$labels['aftermoveto'] = 'Move to...';
$labels['itipoptions'] = 'Event Invitations';
$labels['afteraction'] = 'After an invitation or update message is processed';

// calendar
$labels['calendar'] = 'Calendário';
$labels['calendars'] = 'Calendários';
$labels['category'] = 'Categoria';
$labels['categories'] = 'Categorias';
$labels['createcalendar'] = 'Criar novo calendário';
$labels['editcalendar'] = 'Editar propriedades do calendário';
$labels['name'] = 'Nome';
$labels['color'] = 'Cor';
$labels['day'] = 'Dia';
$labels['week'] = 'Semana';
$labels['month'] = 'Mês';
$labels['agenda'] = 'Agenda';
$labels['new'] = 'Novo';
$labels['new_event'] = 'Novo evento';
$labels['edit_event'] = 'Editar evento';
$labels['edit'] = 'Editar';
$labels['save'] = 'Gravar';
$labels['removelist'] = 'Remove from list';
$labels['cancel'] = 'Cancelar';
$labels['select'] = 'Selecionar';
$labels['print'] = 'Imprimir';
$labels['printtitle'] = 'Imprimir calendários';
$labels['title'] = 'Sumário';
$labels['description'] = 'Descrição';
$labels['all-day'] = 'dia todo';
$labels['export'] = 'Exportar';
$labels['exporttitle'] = 'Exportar para iCalendar';
$labels['exportrange'] = 'Eventos de';
$labels['exportattachments'] = 'With attachments';
$labels['customdate'] = 'Custom date';
$labels['location'] = 'Local';
$labels['url'] = 'URL';
$labels['date'] = 'Data';
$labels['start'] = 'Início';
$labels['starttime'] = 'Start time';
$labels['end'] = 'Término';
$labels['endtime'] = 'End time';
$labels['repeat'] = 'Repetir';
$labels['selectdate'] = 'Escolha a data';
$labels['freebusy'] = 'Mostrar me como';
$labels['free'] = 'Disponível';
$labels['busy'] = 'Ocupado';
$labels['outofoffice'] = 'Fora de escritório';
$labels['tentative'] = 'Tentativa';
$labels['mystatus'] = 'My status';
$labels['status'] = 'Situação';
$labels['status-confirmed'] = 'Confirmado';
$labels['status-cancelled'] = 'Cancalado';
$labels['priority'] = 'Prioridade';
$labels['sensitivity'] = 'Privacidade';
$labels['public'] = 'público';
$labels['private'] = 'privado';
$labels['confidential'] = 'confidencial';
$labels['alarms'] = 'Lembrete';
$labels['comment'] = 'Comentário';
$labels['created'] = 'Created';
$labels['changed'] = 'Last Modified';
$labels['unknown'] = 'Desconhecido';
$labels['eventoptions'] = 'Opções';
$labels['generated'] = 'gerado em';
$labels['eventhistory'] = 'History';
$labels['printdescriptions'] = 'Descrições de impressão';
$labels['parentcalendar'] = 'Inserir dentro';
$labels['searchearlierdates'] = '« Procurar por eventos anteriores';
$labels['searchlaterdates'] = 'Procurar por eventos posteriores »';
$labels['andnmore'] = '$nr mais...';
$labels['togglerole'] = 'Clique para alternar o papel';
$labels['createfrommail'] = 'Salvar como evento';
$labels['importevents'] = 'Importar eventos';
$labels['importrange'] = 'Eventos de';
$labels['onemonthback'] = '1 mês atrás';
$labels['nmonthsback'] = '$nr meses atrás';
$labels['showurl'] = 'Mostrar URL do calendário';
$labels['showurldescription'] = 'Use o seguinte endereço para acessar (somente leitura) seu calendário em outras aplicações. Você pode copiar e colar este endereço em qualquer software de calendário que suporte o formato iCal.';
$labels['caldavurldescription'] = 'Copy this address to a <a href="http://en.wikipedia.org/wiki/CalDAV" target="_blank">CalDAV</a> client application (e.g. Evolution or Mozilla Thunderbird) to fully synchronize this specific calendar with your computer or mobile device.';
$labels['findcalendars'] = 'Buscar calendários...';
$labels['searchterms'] = 'Search terms';
$labels['calsearchresults'] = 'Calendários disponíveis';
$labels['calendarsubscribe'] = 'Listar permanentemente';
$labels['nocalendarsfound'] = 'No calendars found';
$labels['nrcalendarsfound'] = '$nr calendars found';
$labels['quickview'] = 'View only this calendar';
$labels['invitationspending'] = 'Pending invitations';
$labels['invitationsdeclined'] = 'Declined invitations';
$labels['changepartstat'] = 'Change participant status';
$labels['rsvpcomment'] = 'Invitation text';

// agenda view
$labels['listrange'] = 'Intervalo para exibir:';
$labels['listsections'] = 'Dividir em:';
$labels['smartsections'] = 'Seções inteligentes';
$labels['until'] = 'até';
$labels['today'] = 'Hoje';
$labels['tomorrow'] = 'Amanhã';
$labels['thisweek'] = 'Esta semana';
$labels['nextweek'] = 'Próxima semana';
$labels['prevweek'] = 'Previous week';
$labels['thismonth'] = 'Este mês';
$labels['nextmonth'] = 'Próximo mês';
$labels['weekofyear'] = 'Semana';
$labels['pastevents'] = 'Passado';
$labels['futureevents'] = 'Futuro';

// alarm/reminder settings
$labels['showalarms'] = 'Show reminders';
$labels['defaultalarmtype'] = 'Configuração de lembrete padrão';
$labels['defaultalarmoffset'] = 'Horário padrão de lembrete';

// attendees
$labels['attendee'] = 'Participante';
$labels['role'] = 'Papel';
$labels['availability'] = 'Disp.';
$labels['confirmstate'] = 'Situação';
$labels['addattendee'] = 'Adicionar participante';
$labels['roleorganizer'] = 'Organizador';
$labels['rolerequired'] = 'Obrigatório';
$labels['roleoptional'] = 'Opcional';
$labels['rolechair'] = 'Chair';
$labels['rolenonparticipant'] = 'Absent';
$labels['cutypeindividual'] = 'Individual';
$labels['cutypegroup'] = 'Grupo';
$labels['cutyperesource'] = 'Recurso';
$labels['cutyperoom'] = 'Room';
$labels['availfree'] = 'Disponível';
$labels['availbusy'] = 'Ocupado';
$labels['availunknown'] = 'Desconhecido';
$labels['availtentative'] = 'Tentativa';
$labels['availoutofoffice'] = 'Fora de escritório';
$labels['delegatedto'] = 'Delegado para:';
$labels['delegatedfrom'] = 'Delegado de:';
$labels['scheduletime'] = 'Procurar disponibilidade';
$labels['sendinvitations'] = 'Enviar convites';
$labels['sendnotifications'] = 'Avisar os participantes sobre as modificações';
$labels['sendcancellation'] = 'Avisar os participantes sobre o cancelamento do evento';
$labels['onlyworkinghours'] = 'Procurar disponibilidade dentro do meu horário de trabalho';
$labels['reqallattendees'] = 'Obrigatório/todos os participantes';
$labels['prevslot'] = 'Espaço anterior';
$labels['nextslot'] = 'Próximo espaço';
$labels['suggestedslot'] = 'Suggested Slot';
$labels['noslotfound'] = 'Incapaz de encontrar um horário disponível';
$labels['invitationsubject'] = 'Você foi convidado para "$title"';
$labels['invitationmailbody'] = "*\$title*\n\nQuando: \$date\n\nConvidados: \$attendees\n\nSegue em anexo um arquivo iCalendar com todos os detalhes do evento na qual você pode importar para sua aplicação de calendário.";
$labels['invitationattendlinks'] = "No caso do seu cliente de e-mail não suportar requisições iTIP você pode usar o link a seguir para aceitar ou recusar este convite:\n\$url";
$labels['eventupdatesubject'] = '"$title" foi atualizado';
$labels['eventupdatesubjectempty'] = 'Um evento do seu interesse foi atualizado';
$labels['eventupdatemailbody'] = "*\$title*\n\nQuando: \$date\n\nConvidados: \$attendees\n\nSegue em anexo um arquivo iCalendar com os detalhes atualizados do evento na qual você pode importar para sua aplicação de calendário.";
$labels['eventcancelsubject'] = '"$title" foi cancelado';
$labels['eventcancelmailbody'] = "*\$title*\n\nQuando: \$date\n\nConvidados: \$attendees\n\nO evento foi cancelado por \$organizer.\n\nSegue em anexo um arquivo iCalendar com os detalhes atualizados do evento.";

// invitation handling (overrides labels from libcalendaring)
$labels['itipobjectnotfound'] = 'O evento referenciado por esta mensagem não foi encontrado em seu calendário.';

$labels['itipmailbodyaccepted'] = "\$sender aceitou o convite para o seguinte evento:\n\n*\$title*\n\nQuando: \$date\n\nConvidados: \$attendees";
$labels['itipmailbodytentative'] = "\$sender aceitou como tentativa o convite para o seguinte evento:\n\n*\$title*\n\nQuando: \$date\n\nConvidados: \$attendees";
$labels['itipmailbodydeclined'] = "\$sender recusou o convite para o seguinte evento:\n\n*\$title*\n\nQuando: \$date\n\nConvidados: \$attendees";
$labels['itipmailbodycancel'] = "\$sender rejeitou sua participação no seguinte evento:\n\n*\$title*\n\nQuando: \$date";
$labels['itipmailbodydelegated'] = "\$sender has delegated the participation in the following event:\n\n*\$title*\n\nWhen: \$date";
$labels['itipmailbodydelegatedto'] = "\$sender has delegated the participation in the following event to you:\n\n*\$title*\n\nWhen: \$date";

$labels['itipdeclineevent'] = 'Você deseja recusar o convite para este evento?';
$labels['declinedeleteconfirm'] = 'Do you also want to delete this declined event from your calendar?';
$labels['itipcomment'] = 'Invitation/notification comment';
$labels['itipcommenttitle'] = 'This comment will be attached to the invitation/notification message sent to participants';

$labels['notanattendee'] = 'Você não está listado como um participante deste evento';
$labels['eventcancelled'] = 'O evento foi cancelado';
$labels['saveincalendar'] = 'salvar em';
$labels['updatemycopy'] = 'Atualize em meu calendário';
$labels['savetocalendar'] = 'Gravar no calendário';
$labels['openpreview'] = 'Check Calendar';
$labels['noearlierevents'] = 'No earlier events';
$labels['nolaterevents'] = 'No later events';

// resources
$labels['resource'] = 'Recurso';
$labels['addresource'] = 'Livro de recursos';
$labels['findresources'] = 'Encontrar recursos';
$labels['resourcedetails'] = 'Detalhes';
$labels['resourceavailability'] = 'Disponibilidade';
$labels['resourceowner'] = 'Dono';
$labels['resourceadded'] = 'O recurso foi adicionado ao seu evento';

// event dialog tabs
$labels['tabsummary'] = 'Sumário';
$labels['tabrecurrence'] = 'Repetição';
$labels['tabattendees'] = 'Participantes';
$labels['tabresources'] = 'Recursos';
$labels['tabattachments'] = 'Anexos';
$labels['tabsharing'] = 'Compartilhamento';

// messages
$labels['deleteobjectconfirm'] = 'Você realmente deseja remover este evento?';
$labels['deleteventconfirm'] = 'Você realmente deseja remover este evento?';
$labels['deletecalendarconfirm'] = 'Você realmente deseja excluir este calendário com todos os seus eventos?';
$labels['deletecalendarconfirmrecursive'] = 'Do you really want to delete this calendar with all its events and sub-calendars?';
$labels['savingdata'] = 'Salvando dados...';
$labels['errorsaving'] = 'Falha ao salvar as modificações.';
$labels['operationfailed'] = 'A operação requisitada falhou.';
$labels['invalideventdates'] = 'Datas inválidas inseridas! Por favor verifique a inserção.';
$labels['invalidcalendarproperties'] = 'Propriedades de calendário inválidas! Por favor defina um nome válido.';
$labels['searchnoresults'] = 'Nenhum evento encontrado nos calendários selecionados.';
$labels['successremoval'] = 'O evento foi excluído com sucesso.';
$labels['successrestore'] = 'O evento foi restaurado com sucesso.';
$labels['errornotifying'] = 'Falha ao enviar notificações para os participantes do evento.';
$labels['errorimportingevent'] = 'Falha ao importar evento';
$labels['importwarningexists'] = 'Uma cópia deste evento já existe em seu calendário.';
$labels['newerversionexists'] = 'Já existe uma nova versão deste evento! Abortado.';
$labels['nowritecalendarfound'] = 'Nenhum calendário encontrado para salvar o evento';
$labels['importedsuccessfully'] = 'O evento foi adicionado com sucesso em \'$calendar\'';
$labels['updatedsuccessfully'] = 'O evento foi atualizado com sucesso em \'$calendar\'.';
$labels['attendeupdateesuccess'] = 'O status do participante foi atualizado com sucesso.';
$labels['itipsendsuccess'] = 'Convite enviado aos participantes.';
$labels['itipresponseerror'] = 'Falha ao enviar a resposta para este convite de evento';
$labels['itipinvalidrequest'] = 'Este convite não é mais válido';
$labels['sentresponseto'] = 'Resposta de convite enviada com sucesso para $mailto';
$labels['localchangeswarning'] = 'You are about to make changes that will only be reflected on your calendar and not be sent to the organizer of the event.';
$labels['importsuccess'] = 'Importado com sucesso $nr eventos';
$labels['importnone'] = 'Não há eventos a serem importados';
$labels['importerror'] = 'Ocorreu um erro na importação';
$labels['aclnorights'] = 'Você não tem permissão de administrador neste calendário.';

$labels['changeeventconfirm'] = 'Trocar evento';
$labels['removeeventconfirm'] = 'Delete event';
$labels['changerecurringeventwarning'] = 'Este é um evento com repetição. Você gostaria de editar o evento atual somente, estas e todas as futuras ocorrências ou salvar este como um novo evento?';
$labels['removerecurringeventwarning'] = 'This is a recurring event. Would you like to delete the current event only, this and all future occurences or all occurences of this event?';
$labels['currentevent'] = 'Atual';
$labels['futurevents'] = 'Futuro';
$labels['allevents'] = 'Todos';
$labels['saveasnew'] = 'Salvar como novo';

// birthdays calendar
$labels['birthdays'] = 'Birthdays';
$labels['birthdayscalendar'] = 'Birthdays Calendar';
$labels['displaybirthdayscalendar'] = 'Display birthdays calendar';
$labels['birthdayscalendarsources'] = 'From these address books';
$labels['birthdayeventtitle'] = '$name\'s Birthday';
$labels['birthdayage'] = 'Age $age';

// history dialog
$labels['eventchangelog'] = 'Change History';
$labels['eventdiff'] = 'Changes from revisions $rev';
$labels['revision'] = 'Revision';
$labels['user'] = 'Usuário';
$labels['operation'] = 'Action';
$labels['actionappend'] = 'Saved';
$labels['actionmove'] = 'Moved';
$labels['actiondelete'] = 'Deletado';
$labels['compare'] = 'Compare';
$labels['showrevision'] = 'Show this version';
$labels['restore'] = 'Restore this version';
$labels['eventnotfound'] = 'Failed to load event data';
$labels['eventchangelognotavailable'] = 'Change history is not available for this event';
$labels['eventdiffnotavailable'] = 'No comparison possible for the selected revisions';
$labels['eventrestoreconfirm'] = 'Do you really want to restore revision $rev of this event? This will replace the current event with the old version.';


// (hidden) titles and labels for accessibility annotations
$labels['arialabelminical'] = 'Calendar date selection';
$labels['arialabelcalendarview'] = 'Calendar view';
$labels['arialabelsearchform'] = 'Event search form';
$labels['arialabelquicksearchbox'] = 'Event search input';
$labels['arialabelcalsearchform'] = 'Calendars search form';
$labels['calendaractions'] = 'Calendar actions';
$labels['arialabeleventattendees'] = 'Event participants list';
$labels['arialabeleventresources'] = 'Event resources list';
$labels['arialabelresourcesearchform'] = 'Resources search form';
$labels['arialabelresourceselection'] = 'Available resources';

?>
