<?php
/**
 * Localizations for the Kolab Chat plugin
 *
 * Copyright (C) 2018, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_chat/
 */
$labels['chat'] = 'Chat';
$labels['showinextwin'] = 'Chatanwendung in einem neuen Fenster öffnen';
$labels['directmessage'] = 'Eine direkte Nachricht von $u.';
$labels['mentionmessage'] = 'Sie wurden von $u in $c erwähnt.';
$labels['openchat'] = 'Chat öffnen';
