<?php

/**
 * Localizations for the Kolab Chat plugin
 *
 * Copyright (C) 2018, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_chat/
 */

$labels['chat'] = 'Chat';
$labels['showinextwin'] = 'Open chat application in a new window';
$labels['defaultchannel'] = 'Open chat application on channel';
$labels['directmessage'] = 'A direct message from $u.';
$labels['mentionmessage'] = 'You have been mentioned by $u in $c.';
$labels['openchat'] = 'Open chat';
