<?php
/**
 * Localizations for the Kolab Chat plugin
 *
 * Copyright (C) 2018, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_chat/
 */
$labels['chat'] = 'Mensajería instantánea';
$labels['showinextwin'] = 'Abrir la aplicación de mensajería instantánea en una nueva ventana';
$labels['directmessage'] = 'Hay un mensaje directo de $u';
$labels['openchat'] = 'Abrir conversación';
