<?php
/**
 * Localizations for the Kolab Chat plugin
 *
 * Copyright (C) 2018, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_chat/
 */
$labels['chat'] = 'Чат';
$labels['showinextwin'] = 'Открыть приложение чата в новом окне';
$labels['defaultchannel'] = 'Открыть приложение чата на канале';
$labels['directmessage'] = 'Прямое сообщение от $u.';
$labels['mentionmessage'] = 'Вы были упомянуты $u в $c.';
$labels['openchat'] = 'Открыть чат';
