<?php
$labels['folderctype'] = 'Indholdstype';
$labels['foldertypemail'] = 'Post';
$labels['foldertypeevent'] = 'Kalender';
$labels['foldertypejournal'] = 'Journal';
$labels['foldertypetask'] = 'Opgaver';
$labels['foldertypenote'] = 'Noter';
$labels['foldertypecontact'] = 'Kontakter';
$labels['foldertypeconfiguration'] = 'Konfiguration';
$labels['foldertypefile'] = 'Filer';
$labels['foldertypefreebusy'] = 'Ledig-optaget';
$labels['default'] = 'Standard';
$labels['inbox'] = 'Indbakke';
$labels['drafts'] = 'Kladder';
$labels['sentitems'] = 'Sendt';
$labels['outbox'] = 'Udbakke';
$labels['wastebasket'] = 'Papirkurv';
$labels['junkemail'] = 'Uønsket';
$messages['defaultfolderexists'] = 'Der er allerede en standardmapper med angive type';
?>
