<?php
$labels['folderctype'] = 'Ordnerinhalt';
$labels['foldertypemail'] = 'E-Mail';
$labels['foldertypeevent'] = 'Kalender'; // Events?
$labels['foldertypejournal'] = 'Journal';
$labels['foldertypetask'] = 'Aufgaben';
$labels['foldertypenote'] = 'Notizen';
$labels['foldertypecontact'] = 'Kontakte';
$labels['foldertypeconfiguration'] = 'Konfiguration';
$labels['foldertypefile'] = 'Dateien';
$labels['foldertypefreebusy'] = 'Frei/Belegt';
$labels['default'] = 'Standard';
$labels['inbox'] = 'Posteingang';
$labels['drafts'] = 'Entwürfe';
$labels['sentitems'] = 'Gesendet';
$labels['outbox'] = 'Postausgang';
$labels['wastebasket'] = 'Mülleimer';
$labels['junkemail'] = 'Spam';
$messages['defaultfolderexists'] = 'Es gibt bereits einen Standardordner dieses Typs';
?>
