<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_folders/
 */
$labels['folderctype'] = 'Sisu liik';
$labels['foldertypemail'] = 'E-post';
$labels['foldertypeevent'] = 'Kalender';
$labels['foldertypejournal'] = 'Päevik';
$labels['foldertypetask'] = 'Ülesanded';
$labels['foldertypenote'] = 'Märkmed';
$labels['foldertypecontact'] = 'Kontaktid';
$labels['foldertypeconfiguration'] = 'Seadistamine';
$labels['foldertypefile'] = 'Failid';
$labels['foldertypefreebusy'] = 'Vaba-Hõivatud';
$labels['default'] = 'Vaikeväärtus';
$labels['inbox'] = 'Saabunud';
$labels['drafts'] = 'Mustandid';
$labels['sentitems'] = 'Saadetud';
$labels['outbox'] = 'Väljuvad';
$labels['wastebasket'] = 'Prügikast';
$labels['junkemail'] = 'Rämpspost';
$labels['confidential'] = 'Konfidentsiaalne';
?>
