<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_folders/
 */
$labels['folderctype'] = 'Tipo di contenuto';
$labels['foldertypemail'] = 'Mail';
$labels['foldertypeevent'] = 'Calendario';
$labels['foldertypetask'] = 'Attività';
$labels['foldertypenote'] = 'Annotazioni';
$labels['foldertypecontact'] = 'Contatti';
$labels['foldertypeconfiguration'] = 'Configurazione';
$labels['foldertypefile'] = 'File';
$labels['foldertypefreebusy'] = 'Libero-Occupato';
$labels['default'] = 'Predefinito';
$labels['wastebasket'] = 'Cestino';
?>
