<?php
$labels['folderctype'] = 'Tipo di contenuto';
$labels['foldertypemail'] = 'Mail';
$labels['foldertypeevent'] = 'Calendario';
$labels['foldertypetask'] = 'Attività';
$labels['foldertypenote'] = 'Annotazioni';
$labels['foldertypecontact'] = 'Contatti';
$labels['foldertypeconfiguration'] = 'Configurazione';
$labels['foldertypefile'] = 'File';
$labels['foldertypefreebusy'] = 'Libero-Occupato';
$labels['default'] = 'Predefinito';
$labels['wastebasket'] = 'Cestino';
?>
