<?php
$labels['folderctype'] = 'コンテンツタイプ';
$labels['foldertypemail'] = 'メール';
$labels['foldertypeevent'] = 'カレンダー'; // Events?
$labels['foldertypejournal'] = 'ジャーナル';
$labels['foldertypetask'] = 'タスク';
$labels['foldertypenote'] = 'ノート';
$labels['foldertypecontact'] = 'コンタクト';
$labels['foldertypeconfiguration'] = '設定';
$labels['foldertypefile'] = 'ファイル';
$labels['foldertypefreebusy'] = '空状況';
$labels['default'] = 'デフォルト';
$labels['inbox'] = '受信箱';
$labels['drafts'] = '下書き';
$labels['sentitems'] = '送信済';
$labels['outbox'] = '送信箱';
$labels['wastebasket'] = 'ごみ箱';
$labels['junkemail'] = '迷惑メール';
$messages['defaultfolderexists'] = '指定したタイプの初期フォルダは既にあります。';
?>
