<?php
$labels['folderctype'] = 'Typ treści';
$labels['foldertypemail'] = 'Poczta';
$labels['foldertypeevent'] = 'Kalendarz'; // Events?
$labels['foldertypejournal'] = 'Dziennik';
$labels['foldertypetask'] = 'Zadania';
$labels['foldertypenote'] = 'Notatki';
$labels['foldertypecontact'] = 'Kontakty';
$labels['foldertypeconfiguration'] = 'Konfiguracja';
$labels['foldertypefile'] = 'Pliki';
$labels['foldertypefreebusy'] = 'Wolny-Zajęty';
$labels['default'] = 'Domyślny';
$labels['inbox'] = 'Odebrane';
$labels['drafts'] = 'Kopie robocze';
$labels['sentitems'] = 'Wysłane';
$labels['outbox'] = 'Poczta wychodząca';
$labels['wastebasket'] = 'Kosz';
$labels['junkemail'] = 'Spam';
$messages['defaultfolderexists'] = 'Folder domyślny wybranego typu już istnieje';
?>
