<?php
/**
 * Localizations for the Kolab Folders plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_folders/
 */
$labels['folderctype'] = 'Typ treści';
$labels['foldertypemail'] = 'Poczta';
$labels['foldertypeevent'] = 'Kalendarz';
$labels['foldertypejournal'] = 'Dziennik';
$labels['foldertypetask'] = 'Zadania';
$labels['foldertypenote'] = 'Notatki';
$labels['foldertypecontact'] = 'Kontakty';
$labels['foldertypeconfiguration'] = 'Konfiguracja';
$labels['foldertypefile'] = 'Pliki';
$labels['foldertypefreebusy'] = 'Wolny-Zajęty';
$labels['default'] = 'Domyślny';
$labels['inbox'] = 'Odebrane';
$labels['drafts'] = 'Kopie robocze';
$labels['sentitems'] = 'Wysłane';
$labels['outbox'] = 'Poczta wychodząca';
$labels['wastebasket'] = 'Kosz';
$labels['junkemail'] = 'Spam';
$labels['confidential'] = 'Poufne';
$labels['private'] = 'Prywatne';
$labels['folderexpire'] = 'Usuń wiadomości starsze niż';
$labels['xdays'] = '$x days';
$messages['defaultfolderexists'] = 'Folder domyślny wybranego typu już istnieje';
?>
