<?php
/**
 * Localizations for the Kolab Tags plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_tags/
 */
$labels['tags'] = 'Mærker';
$labels['add'] = 'Tilføj';
$labels['edit'] = 'Redigér';
$labels['delete'] = 'Slet';
$labels['tagname'] = 'Navn';
$labels['tagcolor'] = 'Farve';
$labels['saving'] = 'Gemmer data...';
