<?php
/**
 * Localizations for the Kolab Tags plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_tags/
 */
$labels['tags'] = 'Tags';
$labels['add'] = 'Hinzufügen';
$labels['edit'] = 'Bearbeiten';
$labels['delete'] = 'Löschen';
$labels['tagname'] = 'Name';
$labels['tagcolor'] = 'Farbe';
$labels['saving'] = 'Speichere...';
