<?php
/**
 * Localizations for the Kolab Tags plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_tags/
 */
$labels['tags'] = 'Sildid';
$labels['unset'] = 'Eemalda kõigi valik';
$labels['manage'] = 'Siltide haldamine...';
$labels['tagactions'] = 'Siltide toimingud...';
$labels['tagadd'] = 'Sildista...';
$labels['tagremove'] = 'Eemalda silt...';
$labels['untag'] = 'Eemalda silt';
$labels['notags'] = 'Silte pole';
$labels['tagremoveall'] = 'Eemalda kõik sildid';
$labels['add'] = 'Lisa';
$labels['edit'] = 'Muuda';
$labels['delete'] = 'Kustuta';
$labels['tagname'] = 'Nimi';
$labels['tagcolor'] = 'Värv';
$labels['nameempty'] = 'Sildi nimi ei saa olle tühi!';
$labels['nameexists'] = 'Selle nimega silt on juba olemas!';
$labels['colorinvalid'] = 'Vigane värv!';
$labels['saving'] = 'Andmete salvestamine...';
$labels['updatesuccess'] = 'Silte on uuendatud.';
$labels['updateerror'] = 'Silteide info uuendamine ebaõnnestus.';
$labels['taggingsuccess'] = 'Sildid on määratud.';
$labels['taggingerror'] = 'Siltide määramine ebaõnnestus.';
$labels['untaggingsuccess'] = 'Silt (sildid) on eemaldatud.';
$labels['untaggingerror'] = 'Siltide eemaldamine ebaõnnestus.';
$labels['newtag'] = 'Uus silt';
$labels['tagsearchnew'] = 'Sisesta otsitav tekst või lisa uue silt';
