<?php
/**
 * Localizations for the Kolab Tags plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_tags/
 */
$labels['tags'] = 'Tunnisteet';
$labels['add'] = 'Lisää';
$labels['edit'] = 'Muokkaa';
$labels['delete'] = 'Poista';
$labels['tagname'] = 'Nimi';
$labels['tagcolor'] = 'Väri';
$labels['saving'] = 'Tallennetaan tietoja...';
