<?php
/**
 * Localizations for the Kolab Tags plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_tags/
 */
$labels['tags'] = 'Étiquettes';
$labels['add'] = 'Ajouter';
$labels['edit'] = 'Modifier';
$labels['delete'] = 'Supprimer';
$labels['tagname'] = 'Nom';
$labels['tagcolor'] = 'Couleur';
$labels['saving'] = 'Enregistrer...';
