<?php
/**
 * Localizations for the Kolab Tags plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_tags/
 */
$labels['tags'] = 'Kulcsszavak';
$labels['add'] = 'Add';
$labels['edit'] = 'Módosítás';
$labels['delete'] = 'Delete';
$labels['tagname'] = 'Név';
$labels['tagcolor'] = 'Szín';
$labels['saving'] = 'Adatok mentése...';
