<?php
/**
 * Localizations for the Kolab Tags plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_tags/
 */
$labels['tags'] = 'タグ';
$labels['unset'] = 'Unselect all';
$labels['manage'] = 'Manage tags...';
$labels['tagactions'] = 'Tag actions...';
$labels['tagadd'] = 'Tag as...';
$labels['tagremove'] = 'Remove tag...';
$labels['untag'] = 'Remove tag';
$labels['tagremoveall'] = 'Remove all tags';
$labels['add'] = '追加';
$labels['edit'] = '編集';
$labels['delete'] = '削除';
$labels['tagname'] = '名前';
$labels['tagcolor'] = '色';
$labels['nameempty'] = 'Tag name cannot be empty!';
$labels['nameexists'] = 'Tag with specified name already exists!';
$labels['colorinvalid'] = 'Invalid color specification!';
$labels['saving'] = 'データを保存中…';
$labels['updatesuccess'] = 'Tags have beed updated successfully.';
$labels['updateerror'] = 'Failed to update tags information.';
$labels['taggingsuccess'] = 'Tags have beed assigned successfully.';
$labels['taggingerror'] = 'Failed to assign tags.';
$labels['untaggingsuccess'] = 'Tag(s) have beed removed successfully.';
$labels['untaggingerror'] = 'Failed to remove tag assignments.';
