<?php
/**
 * Localizations for the Kolab Tags plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_tags/
 */
$labels['tags'] = 'Labels';
$labels['add'] = 'Toevoegen';
$labels['edit'] = 'Wijzig';
$labels['delete'] = 'Verwijderen';
$labels['tagname'] = 'Naam';
$labels['tagcolor'] = 'Kleur';
$labels['saving'] = 'Data wordt opgeslagen...';
