<?php
/**
 * Localizations for the Kolab Tags plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_tags/
 */
$labels['tags'] = 'Tagi';
$labels['unset'] = 'Odznacz wszystkie';
$labels['manage'] = 'Zarządzaj tagami...';
$labels['tagactions'] = 'Akcje tagów...';
$labels['tagadd'] = 'Otaguj jako...';
$labels['tagremove'] = 'Usuń tag...';
$labels['untag'] = 'Usuń tag';
$labels['notags'] = 'Brak tagów';
$labels['tagremoveall'] = 'Usuń wszystkie tagi';
$labels['add'] = 'Dodaj';
$labels['edit'] = 'Edytuj';
$labels['delete'] = 'Usuń';
$labels['tagname'] = 'Nazwa';
$labels['tagcolor'] = 'Kolor';
$labels['nameempty'] = 'Nazwa tagu jest wymagana!';
$labels['nameexists'] = 'Tag o podanej nazwie już istnieje!';
$labels['colorinvalid'] = 'Błędny format koloru!';
$labels['saving'] = 'Zapisuję dane...';
$labels['updatesuccess'] = 'Tagi zostały zaktualizowane pomyślnie.';
$labels['updateerror'] = 'Błąd podczas zapisu danych tagów.';
$labels['taggingsuccess'] = 'Tagi zostały przypisane pomyślnie.';
$labels['taggingerror'] = 'Błąd podczas przypisywania tagów.';
$labels['untaggingsuccess'] = 'Tagi zostały usunięte pomyślnie.';
$labels['untaggingerror'] = 'Błąd podczas usuwania powiązań z tagami.';
$labels['newtag'] = 'Nowa etykieta';
$labels['tagsearchnew'] = 'Wprowadź tekst aby wyszukać lub utworzyć nową etykietę';
