<?php
/**
 * Localizations for the Kolab Tags plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_tags/
 */
$labels['tags'] = 'Etiketter';
$labels['unset'] = 'Avmarkera alla';
$labels['manage'] = 'Hantera etiketter ...';
$labels['tagactions'] = 'Åtgärder för etiketter ...';
$labels['tagadd'] = 'Etikettera som ...';
$labels['tagremove'] = 'Ta bort etikett ...';
$labels['untag'] = 'Ta bort etikett';
$labels['notags'] = 'Inga etiketter';
$labels['tagremoveall'] = 'Ta bort alla etiketter';
$labels['add'] = 'Lägg till';
$labels['edit'] = 'Redigera';
$labels['delete'] = 'Ta bort';
$labels['tagname'] = 'Namn';
$labels['tagcolor'] = 'Färg';
$labels['nameempty'] = 'Etikettens namn kan inte vara tomt!';
$labels['nameexists'] = 'Etikett med angivet namn finns redan!';
$labels['colorinvalid'] = 'Ogiltig färgspecifikation!';
$labels['saving'] = 'Sparar data ...';
$labels['updatesuccess'] = 'Etiketter har uppdaterats.';
$labels['updateerror'] = 'Misslyckades att uppdatera etikettinformation.';
$labels['taggingsuccess'] = 'Etiketter har blivit tilldelade.';
$labels['taggingerror'] = 'Misslyckades att tilldela etiketter.';
$labels['untaggingsuccess'] = 'Etikett(er) har tagits bort.';
$labels['untaggingerror'] = 'Misslyckades att ta bort etikettilldelningar.';
$labels['newtag'] = 'Ny etikett';
$labels['tagsearchnew'] = 'Ange söktext eller skapa en ny etikett';
