<?php
/**
 * Localizations for the Kolab Tags plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_tags/
 */
$labels['tags'] = 'Etiketter';
$labels['add'] = 'Lägg till';
$labels['edit'] = 'Redigera';
$labels['delete'] = 'Ta bort';
$labels['tagname'] = 'Namn';
$labels['tagcolor'] = 'Färg';
$labels['saving'] = 'Sparar data ...';
