<?php
/**
 * Localizations for the Kolab Files plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_files/
 */
$labels['files'] = 'Файлове';
$labels['save'] = 'Запис';
$labels['cancel'] = 'Отказ';
$labels['folderinside'] = 'Внасяне вътре';
$labels['name'] = 'Име';
$labels['edit'] = 'Промяна';
$labels['save'] = 'Запис';
?>
