<?php
/**
 * Localizations for the Kolab Files plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_files/
 */
$labels['files'] = 'Files';
$labels['save'] = 'Desa';
$labels['cancel'] = 'Cancel·la';
$labels['folderinside'] = 'Insereix dins';
$labels['name'] = 'Nom';
$labels['edit'] = 'Edita';
$labels['save'] = 'Desa';
?>
