<?php
/**
 * Localizations for the Kolab Files plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_files/
 */
$labels['files'] = 'Soubory';
$labels['filepreview'] = 'Náhled souboru';
$labels['saveall'] = 'Uložit vše na server...';
$labels['saveto'] = 'Uložit na server...';
$labels['saveas'] = 'Uložit jako:';
$labels['create'] = 'Vytvořit';
$labels['save'] = 'Uložit';
$labels['cancel'] = 'Zrušit';
$labels['fromcloud'] = 'Ze serveru...';
$labels['selectfiles'] = 'Vybrat soubor(y) k připojení...';
$labels['attachsel'] = 'Příloha vybrána';
$labels['foldercreate'] = 'Vytvořit složku';
$labels['folderedit'] = 'Upravit složku';
$labels['foldermount'] = 'Přidat úložiště';
$labels['folderdelete'] = 'Smazat složku';
$labels['folderinside'] = 'Vložit dovnitř';
$labels['foldername'] = 'Název složky';
$labels['name'] = 'Název';
$labels['mtime'] = 'Změněno';
$labels['type'] = 'Typ';
$labels['upload'] = 'Nahrát';
$labels['uploadfile'] = 'Nahrát soubor(y)';
$labels['get'] = 'Stáhnout';
$labels['getfile'] = 'Stáhnout soubor';
$labels['view'] = 'Zobrazit';
$labels['viewfile'] = 'Zobrazit soubor';
$labels['rename'] = 'Přejmenovat soubor';
$labels['deletefile'] = 'Smazat soubor(y)';
$labels['edit'] = 'Upravit';
$labels['editfile'] = 'Upravit soubor';
$labels['save'] = 'Uložit';
$labels['savefile'] = 'Uložit soubor';
$labels['printfile'] = 'Tisk souboru';
$labels['fileedit'] = 'Vlastnosti souboru';
$labels['collection_audio'] = 'Zvuk';
$labels['collection_video'] = 'Obraz';
$labels['collection_image'] = 'Obrázky';
$labels['collection_document'] = 'Dokumenty';
$labels['uploading'] = 'Nahrávání soubor(ů)...';
$labels['attaching'] = 'Připojuje se soubor(y)...';
$labels['authenticating'] = 'Ověřuje se...';
$labels['foldercreating'] = 'Vytvoří se složka...';
$labels['folderupdating'] = 'Aktualizuje se složka...';
$labels['foldermounting'] = 'Přidává se vnější úložiště...';
$labels['folderdeleting'] = 'Maže se složka...';
$labels['folderdeleteconfirm'] = 'Opravdu chcete smazat vybranou složku?';
$labels['folderdeletenotice'] = 'Složka byla úspěšně smazána.';
$labels['folderupdatenotice'] = 'Složka aktualizována.';
$labels['foldercreatenotice'] = 'Složka úspěšně vytvořena.';
$labels['foldermountnotice'] = 'Úložiště bylo úspěšně přidáno.';
$labels['saveallnotice'] = 'Úspěšně uloženo $n soubor(ů).';
$labels['saveallerror'] = 'Ukládání $n souborů selhalo.';
$labels['attacherror'] = 'Nepodařilo se připojit soubor(y) ze serveru';
$labels['fileupdating'] = 'Aktualizuje se soubor...';
$labels['filemoving'] = 'Přesouvají se soubor(y)...';
$labels['filecopying'] = 'Kopíruje se soubor(y)...';
$labels['filedeleting'] = 'Maže se soubor(y)...';
$labels['filedeleteconfirm'] = 'Opravdu chcete smazat vybrané soubory?';
$labels['filedeletenotice'] = 'Soubor(y) úspěšně smazány.';
$labels['filemovenotice'] = 'Soubor(y) úspěšně přesunuty.';
$labels['filecopynotice'] = 'Soubor(y) úspěšně zkopírovány.';
$labels['uploadsizeerror'] = 'Dosažena maximální velikost ($size) souboru!';
$labels['allfolders'] = 'Hledat ve všech složkách';
$labels['fileskip'] = 'Přeskočit';
$labels['fileskipall'] = 'Přeskočit vše';
$labels['fileoverwrite'] = 'Přepsat';
$labels['fileoverwriteall'] = 'Přepsat vše';
$labels['filemoveconfirm'] = 'Tato akce přepíše cílový soubor: <b>$file</b>.';
$labels['storepasswords'] = 'Zapamatovat heslo';
$labels['storepasswordsdesc'] = 'Uložená hesla budou šifrována. Zapněte tuto volbu pokud nechcete být dotazováni na heslo při každém přihlášení nebo pokud toto úložiště má být dostupné přes WebDAV.';
$labels['arialabelsearchform'] = 'Hledání souborů';
$labels['arialabelquicksearchbox'] = 'Zadání hledání';
$labels['arialabellistoptions'] = 'Volby seznamu souborů';
$labels['arialabelfolderoptions'] = 'Činnosti složky';
$labels['arialabelfileeditform'] = 'Úprava souboru';
$labels['arialabelfoldercreateform'] = 'Vytvoření složky';
$labels['arialabelfoldereditform'] = 'Úprava složky';
$labels['arialabelfoldermountform'] = 'Vnější úložiště';
$labels['arialabelfolderauthform'] = 'Ověření vnějšího úložiště';
$labels['arialabelfolderlist'] = 'Výběr složky/sbírky';
$labels['arialabelfileselectdialog'] = 'Dialog pro výběr souboru';
$labels['arialabelattachmentoptions'] = 'Volby pro ukládání příloh';
$labels['arialabelfilesavedialog'] = 'Dialog pro ukládání souboru(ů)';
$labels['arialabelfileprops'] = 'Vlastnosti souboru';
$labels['arialabelfilecontent'] = 'Obsah souboru';
?>
