<?php
/**
 * Localizations for the Kolab Files plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_files/
 */
$labels['files'] = 'Filer';
$labels['saveall'] = 'Gem alle i skyen...';
$labels['saveto'] = 'Gem i skyen...';
$labels['saveas'] = 'Gem som:';
$labels['create'] = 'Opret';
$labels['save'] = 'Gem';
$labels['cancel'] = 'Annullér';
$labels['fromcloud'] = 'Fra sky...';
$labels['selectfiles'] = 'Vælg fil(er) til vedhæftning...';
$labels['attachsel'] = 'Vedhæfte den valgte';
$labels['foldercreate'] = 'Opret mappe';
$labels['folderdelete'] = 'Slet mappe';
$labels['folderinside'] = 'Indsæt indeni';
$labels['foldername'] = 'Mappenavn';
$labels['name'] = 'Navn';
$labels['mtime'] = 'Ændret';
$labels['type'] = 'Type';
$labels['upload'] = 'Overfør';
$labels['uploadfile'] = 'Overfør fil(er)';
$labels['get'] = 'Hent';
$labels['getfile'] = 'Hent fil';
$labels['view'] = 'Vis';
$labels['viewfile'] = 'Vis fil';
$labels['rename'] = 'Omdøb fil';
$labels['deletefile'] = 'Slet fil(er)';
$labels['edit'] = 'Redigér';
$labels['editfile'] = 'Redigér fil';
$labels['save'] = 'Gem';
$labels['savefile'] = 'Gem fil';
$labels['printfile'] = 'Udskriv fil';
$labels['fileedit'] = 'Filegenskaber';
$labels['collection_audio'] = 'Lyd';
$labels['collection_video'] = 'Video';
$labels['collection_image'] = 'Billeder';
$labels['collection_document'] = 'Dokumenter';
$labels['uploading'] = 'Overfører fil(er)..';
$labels['attaching'] = 'Vedhæfter fil(er)..';
$labels['foldercreating'] = 'Opretter mappe...';
$labels['folderdeleting'] = 'Sletter mappe...';
$labels['folderdeleteconfirm'] = 'Er du sikker på at du vil slette valgte mappe?';
$labels['folderdeletenotice'] = 'Sletningen af mappe blev gennemført.';
$labels['foldercreatenotice'] = 'Oprettelsen af mappe blev gennemført.';
$labels['saveallnotice'] = 'Gennemførte lagring af $n fil(er).';
$labels['saveallerror'] = 'Lagringen af $n fil(er) mislykkedes.';
$labels['attacherror'] = 'Mislykkedes med at vedhæfte fil(er) fra skyen';
$labels['fileupdating'] = 'Opdaterer fil...';
$labels['filemoving'] = 'Flytter fil(er)...';
$labels['filecopying'] = 'Kopierer fil(er)...';
$labels['filedeleting'] = 'Sletter fil(er)...';
$labels['filedeleteconfirm'] = 'Er du sikker på du vil slette valgte filer?';
$labels['filedeletenotice'] = 'Sletningen af fil(er) blev gennemført.';
$labels['filemovenotice'] = 'Flytning af fil(er) blev gennemført.';
$labels['filecopynotice'] = 'Kopiering af fil(er) blev gennemført.';
$labels['allfolders'] = 'søg i alle mapper';
$labels['fileskip'] = 'Spring over';
$labels['fileskipall'] = 'Spring alle over';
$labels['fileoverwrite'] = 'Overskriv';
$labels['fileoverwriteall'] = 'Overskriv alle';
$labels['filemoveconfirm'] = 'Denne handling vil overskrive destinationsfilen: <b>$file</b>.';
$labels['arialabelfileprops'] = 'Filegenskaber';
?>
