<?php
/**
 * Localizations for the Kolab Files plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_files/
 */
$labels['files'] = 'Dateien';
$labels['create'] = 'Erstellen';
$labels['save'] = 'Speichern';
$labels['cancel'] = 'Abbrechen';
$labels['folderinside'] = 'Erstellen in';
$labels['name'] = 'Name';
$labels['mtime'] = 'Geändert';
$labels['type'] = 'Typ';
$labels['get'] = 'Herunterladen';
$labels['edit'] = 'Bearbeiten';
$labels['save'] = 'Speichern';
$labels['collection_audio'] = 'Audio';
$labels['collection_video'] = 'Video';
$labels['collection_image'] = 'Bilder';
$labels['collection_document'] = 'Dokumente';
$labels['fileskip'] = 'Überspringen';
$labels['fileskipall'] = 'Alle überspringen';
$labels['fileoverwrite'] = 'Überschreiben';
$labels['fileoverwriteall'] = 'Alle überschreiben';
$labels['filemoveconfirm'] = 'Diese Aktion wird die Zieldatei <b>$file</b> überschreiben.';
?>
