<?php
/**
 * Localizations for the Kolab Files plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_files/
 */
$labels['files'] = 'Dateien';
$labels['create'] = 'Erstellen';
$labels['save'] = 'Speichern';
$labels['cancel'] = 'Abbrechen';
$labels['addfolder'] = 'Ordner hinzufügen';
$labels['foldermount'] = 'Speicherplatz hinzufügen';
$labels['name'] = 'Name';
$labels['type'] = 'Typ';
$labels['edit'] = 'Bearbeiten';
$labels['save'] = 'Speichern';
$labels['close'] = 'Schließen';
$labels['submit'] = 'Absenden';
$labels['confirmpassword'] = 'Passwort bestätigen';
$labels['foldermounting'] = 'Externe Speicherplatz hinzufügen';
$labels['foldermountnotice'] = 'Speicherplatz erfolgreich angelegt.';
$labels['additionalfolders'] = 'Zusätzliche Ordneren';
$labels['select'] = 'Auswählen';
$labels['participant'] = 'Teilnehmer';
$labels['status'] = 'Status';
$labels['addparticipant'] = 'Teilnehmer hinzufügen';
$labels['statusorganizer'] = 'Organisator';
$labels['statusaccepted'] = 'Akzeptiert';
$labels['statusdeclined'] = 'Abgelehnt';
$labels['removeparticipant'] = 'Entfernen';
$labels['owner'] = 'Besitzer';
$labels['comment'] = 'Kommentar';
