<?php
/**
 * Localizations for the Kolab Files plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_files/
 */
$labels['files'] = 'Dateien';
$labels['filepreview'] = 'Voransicht';
$labels['saveall'] = 'Alle in die Cloud speichern...';
$labels['saveto'] = 'In die Cloud speichern...';
$labels['saveas'] = 'Speichern als:';
$labels['create'] = 'Erstellen';
$labels['save'] = 'Speichern';
$labels['cancel'] = 'Abbrechen';
$labels['fromcloud'] = 'Aus der Cloud...';
$labels['selectfiles'] = 'Datei(en) zum Anhängen auswählen...';
$labels['attachsel'] = 'Ausgewählte anhängen';
$labels['foldercreate'] = 'Ordner erstellen';
$labels['folderdelete'] = 'Ordner löschen';
$labels['folderinside'] = 'Erstellen in';
$labels['foldername'] = 'Ordnername';
$labels['name'] = 'Name';
$labels['mtime'] = 'Geändert';
$labels['type'] = 'Typ';
$labels['upload'] = 'Hochladen';
$labels['uploadfile'] = 'Datei(en) hochladen';
$labels['get'] = 'Herunterladen';
$labels['getfile'] = 'Datei herunterladen';
$labels['view'] = 'Ansehen';
$labels['viewfile'] = 'Datei ansehen';
$labels['rename'] = 'Datei umbenennen';
$labels['deletefile'] = 'Datei(en) löschen';
$labels['edit'] = 'Bearbeiten';
$labels['editfile'] = 'Datei bearbeiten';
$labels['save'] = 'Speichern';
$labels['savefile'] = 'Datei speichern';
$labels['printfile'] = 'Datei drucken';
$labels['fileedit'] = 'Dateieigenschaften';
$labels['collection_audio'] = 'Audio';
$labels['collection_video'] = 'Video';
$labels['collection_image'] = 'Bilder';
$labels['collection_document'] = 'Dokumente';
$labels['uploading'] = 'Lade Datei(en) hoch...';
$labels['attaching'] = 'Hänge Datei(en) an...';
$labels['foldercreating'] = 'Erstelle Ordner...';
$labels['folderdeleting'] = 'Lösche Ordner...';
$labels['folderdeleteconfirm'] = 'Sind Sie sicher, dass Sie den gewählten Ordner löschen möchten?';
$labels['folderdeletenotice'] = 'Ordner erfolgreich gelöscht.';
$labels['foldercreatenotice'] = 'Ordner erfolgreich erstellt.';
$labels['saveallnotice'] = '$n Datei(en) erfolgreich gespeichert.';
$labels['saveallerror'] = 'Speichern von $n Datei(en) fehlgeschlagen.';
$labels['attacherror'] = 'Anhängen von Datei(en) aus der Cloud fehlgeschlagen.';
$labels['fileupdating'] = 'Aktualisiere Datei...';
$labels['filemoving'] = 'Verschiebe Datei(en)...';
$labels['filecopying'] = 'Kopiere Datei(en)...';
$labels['filedeleting'] = 'Lösche Datei(en)...';
$labels['filedeleteconfirm'] = 'Sind Sie sicher, dass Sie die gewählten Dateien löschen möchten?';
$labels['filedeletenotice'] = 'Datei(en) erfolgreich gelöscht.';
$labels['filemovenotice'] = 'Datei(en) erfolgreich verschoben.';
$labels['filecopynotice'] = 'Datei(en) erfolgreich kopiert.';
$labels['uploadsizeerror'] = 'Maimale Dateigröße ($size) überschritten!';
$labels['allfolders'] = 'suche in allen Ordnern';
$labels['fileskip'] = 'Überspringen';
$labels['fileskipall'] = 'Alle überspringen';
$labels['fileoverwrite'] = 'Überschreiben';
$labels['fileoverwriteall'] = 'Alle überschreiben';
$labels['filemoveconfirm'] = 'Diese Aktion wird die Zieldatei <b>$file</b> überschreiben.';
$labels['arialabelsearchform'] = 'Suchformular für Dateien';
$labels['arialabelquicksearchbox'] = 'Sucheingabe';
$labels['arialabellistoptions'] = 'Dateilisten Optionen';
$labels['arialabelfolderoptions'] = 'Ordner Aktionen';
$labels['arialabelfileeditform'] = 'Datei Bearbeiten Maske';
$labels['arialabelfoldercreateform'] = 'Ordner Erstellen Maske';
$labels['arialabelfolderlist'] = 'Ordner / Sammlungs Auswahl';
$labels['arialabelfileselectdialog'] = 'Datei Auswahl Dialog';
$labels['arialabelattachmentoptions'] = 'Anhänge speichern Optionen';
$labels['arialabelfilesavedialog'] = 'Datei(en) speichern Dialog';
$labels['arialabelfileprops'] = 'Dateieigenschaften';
$labels['arialabelfilecontent'] = 'Datei Inhalt';
?>
