<?php
/**
 * Localizations for the Kolab Files plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_files/
 */
$labels['files'] = 'Archivos';
$labels['filepreview'] = 'Vista preliminar del archivo';
$labels['saveall'] = 'Guardar todo en la nube...';
$labels['saveto'] = 'Guardar en la nube...';
$labels['saveas'] = 'Guardar como:';
$labels['create'] = 'Crear';
$labels['save'] = 'Guardar';
$labels['cancel'] = 'Cancelar';
$labels['fromcloud'] = 'De la nube...';
$labels['selectfiles'] = 'Seleccionar archivo(s) para adjuntar...';
$labels['attachsel'] = 'Adjunto seleccionado';
$labels['foldercreate'] = 'Crear carpeta';
$labels['folderdelete'] = 'Eliminar carpeta';
$labels['folderinside'] = 'Insertar dentro';
$labels['foldername'] = 'Nombre de carpeta';
$labels['name'] = 'Nombre';
$labels['mtime'] = 'Modificado';
$labels['type'] = 'Tipo';
$labels['upload'] = 'Subir';
$labels['uploadfile'] = 'Subir archivo(s)';
$labels['get'] = 'Descargar';
$labels['getfile'] = 'Descargar archivo';
$labels['view'] = 'Ver';
$labels['viewfile'] = 'Ver archivo';
$labels['rename'] = 'Renombrar archivo';
$labels['deletefile'] = 'Eliminar archivo(s)';
$labels['edit'] = 'Editar';
$labels['editfile'] = 'Editar archivo';
$labels['save'] = 'Guardar';
$labels['savefile'] = 'Guardar archivo';
$labels['printfile'] = 'Imprimir archivo';
$labels['fileedit'] = 'Propiedades del archivo';
$labels['collection_audio'] = 'Audio';
$labels['collection_video'] = 'Vídeo';
$labels['collection_image'] = 'Imágenes';
$labels['collection_document'] = 'Documentos';
$labels['uploading'] = 'Subiendo archivo(s)...';
$labels['attaching'] = 'Adjuntando archivo(s)...';
$labels['foldercreating'] = 'Creando carpeta...';
$labels['folderdeleting'] = 'Eliminando carpeta...';
$labels['folderdeleteconfirm'] = 'Confirme que desea eliminar la carpeta seleccionada';
$labels['folderdeletenotice'] = 'La carpeta fue eliminada exitosamente.';
$labels['foldercreatenotice'] = 'La carpeta fue creada exitosamente.';
$labels['saveallnotice'] = 'Se guardaron $n archivo(s) exitosamente.';
$labels['saveallerror'] = 'Fallo guardando $n archivos.';
$labels['attacherror'] = 'Fallo adjuntando archivo(s) de la nube';
$labels['fileupdating'] = 'Actualizando archivo...';
$labels['filemoving'] = 'Moviendo archivo(s)...';
$labels['filecopying'] = 'Copiando archivo(s)...';
$labels['filedeleting'] = 'Eliminando archivo(s)...';
$labels['filedeleteconfirm'] = 'Confirme que desea eliminar los archivos seleccionados';
$labels['filedeletenotice'] = 'Archivo(s) eliminados exitosamente.';
$labels['filemovenotice'] = 'Archivo(s) movidos exitosamente.';
$labels['filecopynotice'] = 'Archivo(s) copiados exitosamente.';
$labels['uploadsizeerror'] = 'Ha excedido el tamaño máximo de archivo ($size)';
$labels['allfolders'] = 'buscar en todas las carpetas';
$labels['fileskip'] = 'Omitir';
$labels['fileskipall'] = 'Omitir todo';
$labels['fileoverwrite'] = 'Sobreescribir';
$labels['fileoverwriteall'] = 'Sobreescribir todo';
$labels['filemoveconfirm'] = 'Esta acción sobreescribirá el archivo de destino: <b>$file</b>';
$labels['arialabelsearchform'] = 'Formulario de búsqueda de archivos';
$labels['arialabelquicksearchbox'] = 'Entrada de búsqueda';
$labels['arialabellistoptions'] = 'Opciones de lista de archivos';
$labels['arialabelfolderoptions'] = 'Acciones de carpeta';
$labels['arialabelfileeditform'] = 'Formulario de edición de archivo';
$labels['arialabelfoldercreateform'] = 'Formulario de creación de carpeta';
$labels['arialabelfolderlist'] = 'Selección de carpeta/colección';
$labels['arialabelfileselectdialog'] = 'Diálogo de selección de archivo';
$labels['arialabelattachmentoptions'] = 'Opciones para guardar adjunto';
$labels['arialabelfilesavedialog'] = 'Diálogo de guardado de archivo(s)';
$labels['arialabelfileprops'] = 'Propiedades del archivo';
$labels['arialabelfilecontent'] = 'Contenido del archivo';
?>
