<?php
/**
 * Localizations for the Kolab Files plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_files/
 */
$labels['save'] = 'Guardar';
$labels['cancel'] = 'Cancelar';
$labels['folderinside'] = 'Inserte en el interior';
$labels['name'] = 'Nombre';
$labels['type'] = 'Tipo';
$labels['edit'] = 'Editar';
$labels['save'] = 'Guardar';
$labels['listpermanent'] = 'Lista Permanente';
$labels['select'] = 'Seleccionar';
$labels['participant'] = 'Participante';
$labels['status'] = 'Estado';
$labels['addparticipant'] = 'Añada participante';
$labels['invitationtextlabel'] = 'Añadir comentarios a la Invitación/notificación';
$labels['statusorganizer'] = 'Organizador';
$labels['removeparticipant'] = 'Eliminar';
$labels['comment'] = 'Comentario';
