<?php
/**
 * Localizations for the Kolab Files plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_files/
 */
$labels['files'] = 'Tiedostot';
$labels['filepreview'] = 'Tiedoston esikatselu';
$labels['saveall'] = 'Tallenna kaikki pilveen...';
$labels['saveto'] = 'Tallenna pilveen...';
$labels['saveas'] = 'Tallenna nimellä:';
$labels['create'] = 'Luo';
$labels['save'] = 'Tallenna';
$labels['cancel'] = 'Peru';
$labels['fromcloud'] = 'Pilvestä...';
$labels['selectfiles'] = 'Valitse yksi tai useampi liitettävä tiedosto...';
$labels['attachsel'] = 'Liitä valitut';
$labels['foldercreate'] = 'Luo kansio';
$labels['folderedit'] = 'Muokkaa kansiota';
$labels['foldermount'] = 'Lisää tallennustila';
$labels['folderdelete'] = 'Poista kansio';
$labels['folderinside'] = 'Aseta sisään';
$labels['foldername'] = 'Kansion nimi';
$labels['name'] = 'Nimi';
$labels['mtime'] = 'Muokattu';
$labels['type'] = 'Tyyppi';
$labels['upload'] = 'Lähetä';
$labels['uploadfile'] = 'Lähetä yksi tai useampi tiedosto';
$labels['get'] = 'Lataa';
$labels['getfile'] = 'Lataa tiedosto';
$labels['view'] = 'Näytä';
$labels['viewfile'] = 'Näytä tiedosto';
$labels['rename'] = 'Muuta tiedoston nimeä';
$labels['deletefile'] = 'Poista yksi tai useampi tiedosto';
$labels['edit'] = 'Muokkaa';
$labels['editfile'] = 'Muokkaa tiedostoa';
$labels['save'] = 'Tallenna';
$labels['savefile'] = 'Tallenna tiedosto';
$labels['printfile'] = 'Tulosta tiedosto';
$labels['fileedit'] = 'Tiedoston ominaisuudet';
$labels['collection_audio'] = 'Ääni';
$labels['collection_video'] = 'Video';
$labels['collection_image'] = 'Kuvat';
$labels['collection_document'] = 'Asiakirjat';
$labels['uploading'] = 'Lähetetään tiedostoja...';
$labels['attaching'] = 'Liitetään tiedostoja...';
$labels['authenticating'] = 'Tunnistaudutaan...';
$labels['foldercreating'] = 'Luodaan kansiota...';
$labels['folderupdating'] = 'Päivitetään kansiota...';
$labels['foldermounting'] = 'Lisätään erillistä tallennustilaa...';
$labels['folderdeleting'] = 'Poistetaan kansiota...';
$labels['folderdeleteconfirm'] = 'Haluatko varmasti poistaa valitun kansion?';
$labels['folderdeletenotice'] = 'Kansio poistettu onnistuneesti.';
$labels['folderupdatenotice'] = 'Kansio päivitetty onnistuneesti.';
$labels['foldercreatenotice'] = 'Kansio luotu onnistuneesti.';
$labels['foldermountnotice'] = 'Tallennustila lisätty onnistuneesti.';
$labels['folderauthtitle'] = 'Kirjaudu palveluun $title';
$labels['saveallnotice'] = '$n tiedosto(a) tallennettiin onnistuneesti.';
$labels['saveallerror'] = '$n tiedoston tallentaminen epäonnistui.';
$labels['attacherror'] = 'Tiedostojen liittäminen pilvestä epäonnistui';
$labels['fileupdating'] = 'Päivitetään tiedostoa...';
$labels['filemoving'] = 'Siirretään tiedosto(ja)...';
$labels['filecopying'] = 'Kopioidaan tiedosto(ja)...';
$labels['filedeleting'] = 'Poistetaan tiedosto(ja)...';
$labels['filedeleteconfirm'] = 'Haluatko varmasti poistaa valitut tiedostot?';
$labels['filedeletenotice'] = 'Tiedosto(t) poistettiin onnistuneesti.';
$labels['filemovenotice'] = 'Tiedosto(t) siirrettiin onnistuneesti.';
$labels['filecopynotice'] = 'Tiedosto(t) kopioitiin onnistuneesti.';
$labels['uploadsizeerror'] = 'Lähetykse enimmäiskoko ($size) ylitetty!';
$labels['allfolders'] = 'etsi kaikista kansioista';
$labels['fileskip'] = 'Ohita';
$labels['fileskipall'] = 'Ohita kaikki';
$labels['fileoverwrite'] = 'Korvaa';
$labels['fileoverwriteall'] = 'Korvaa kaikki';
$labels['filemoveconfirm'] = 'Tämä toiminto korvaa kohdetiedoston: <b>$file</b>.';
$labels['storepasswords'] = 'muista salasana';
$labels['storepasswordsdesc'] = 'Tallennetut salasanat salataan. Ota tämä asetus käyttöön, jos et halua salasanaa kysyttävän jokaisella kirjautumiskerralla tai haluat tämän tallennustilan olevan käytettävissä WebDAVin välityksellä.';
$labels['arialabelsearchform'] = 'Tiedostojen hakulomake';
$labels['arialabelfolderoptions'] = 'Kansion toiminnot';
$labels['arialabelfileeditform'] = 'Tiedoston muokkauslomake';
$labels['arialabelfoldercreateform'] = 'Kansion luontilomake';
$labels['arialabelfoldereditform'] = 'Kansion muokkauslomake';
$labels['arialabelfoldermountform'] = 'Erillisen tallennustilan lomake';
$labels['arialabelfolderauthform'] = 'Erillisen tallennustilan tunnistautumisen lomake';
$labels['arialabelfolderlist'] = 'Kansion/kokoelman valinta';
$labels['arialabelfileselectdialog'] = 'Tiedostonvalintaikkuna';
$labels['arialabelattachmentoptions'] = 'Liitteen tallennusvalinnat';
$labels['arialabelfilesavedialog'] = 'Tiedostojen tallennusikkuna';
$labels['arialabelfileprops'] = 'Tiedoston ominaisuudet';
$labels['arialabelfilecontent'] = 'Tiedoston sisältö';
?>
