<?php
/**
 * Localizations for the Kolab Files plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_files/
 */
$labels['files'] = 'ファイル';
$labels['save'] = '保存';
$labels['cancel'] = 'キャンセル';
$labels['folderinside'] = '内に挿入';
$labels['foldername'] = 'フォルダネーム';
$labels['name'] = '名前';
$labels['edit'] = '編集';
$labels['save'] = '保存';
?>
