<?php
/**
 * Localizations for the Kolab Files plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_files/
 */
$labels['files'] = 'Bestanden';
$labels['saveall'] = 'Sla alles op in de cloud...';
$labels['saveto'] = 'Sla op in de cloud...';
$labels['saveas'] = 'Opslaan als:';
$labels['create'] = 'Creëer';
$labels['save'] = 'Opslaan';
$labels['cancel'] = 'Annuleren';
$labels['fromcloud'] = 'Uit de cloud...';
$labels['selectfiles'] = 'Selecteer bestand(en) om toe te voegen...';
$labels['attachsel'] = 'Voeg het geselekteerde toe';
$labels['foldercreate'] = 'Creëer map';
$labels['folderdelete'] = 'Verwijder map';
$labels['folderinside'] = 'Insert inside';
$labels['foldername'] = 'Map naam';
$labels['name'] = 'Naam';
$labels['mtime'] = 'Gewijzigd';
$labels['type'] = 'Type';
$labels['upload'] = 'Upload';
$labels['uploadfile'] = 'Upload bestand(en)';
$labels['get'] = 'Downloaden';
$labels['getfile'] = 'Download bestand';
$labels['view'] = 'Bekijken';
$labels['viewfile'] = 'Bekijk bestand';
$labels['rename'] = 'Hernoem bestand';
$labels['deletefile'] = 'Verwijder bestand(en)';
$labels['edit'] = 'Wijzigen';
$labels['editfile'] = 'Wijzig bestand';
$labels['save'] = 'Opslaan';
$labels['savefile'] = 'Sla bestand op';
$labels['printfile'] = 'Druk bestand af';
$labels['fileedit'] = 'Eigenschappen van bestand';
$labels['collection_audio'] = 'Geluid';
$labels['collection_video'] = 'Video';
$labels['collection_image'] = 'Afbeeldingen';
$labels['collection_document'] = 'Documenten';
$labels['uploading'] = 'Uploaden van bestand(en)...';
$labels['attaching'] = 'Bestand(en) toevoegen...';
$labels['foldercreating'] = 'Creëren van map...';
$labels['folderdeleting'] = 'Verwijderen van map...';
$labels['folderdeleteconfirm'] = 'Weet u zeker dat u de geselecteerde map wilt verwijderen?';
$labels['folderdeletenotice'] = 'Map succesvol verwijderd.';
$labels['foldercreatenotice'] = 'Map succesvol aangemaakt.';
$labels['saveallnotice'] = 'Succesvol $n bestand(en) opgeslagen.';
$labels['saveallerror'] = 'Opslaan van $n bestand(en) mislukt.';
$labels['attacherror'] = 'Toevoegen van bestand(en) uit de cloud mislukt';
$labels['fileupdating'] = 'Wijzigen van bestand...';
$labels['filemoving'] = 'Verplaatsen van bestand(en)...';
$labels['filecopying'] = 'Kopiëren van bestand(en)...';
$labels['filedeleting'] = 'Verwijderen van bestand(en)...';
$labels['filedeleteconfirm'] = 'Weet u zeker dat u de geselecteerde bestanden wilt verwijderen?';
$labels['filedeletenotice'] = 'Bestand(en) succesvol verwijderd.';
$labels['filemovenotice'] = 'Bestand(en) succesvol verplaatst.';
$labels['filecopynotice'] = 'Bestand(en) succesvol gekopieerd.';
$labels['uploadsizeerror'] = 'Maximale bestandsgrootte ($size)  overschreden!';
$labels['allfolders'] = 'Zoek in alle mappen';
$labels['fileskip'] = 'Overslaan';
$labels['fileskipall'] = 'Sla allen over';
$labels['fileoverwrite'] = 'Overschrijven';
$labels['fileoverwriteall'] = 'Overschrijf alle';
$labels['filemoveconfirm'] = 'Deze actie overschrijft het volgende doelbestand: <b>$file</b>.';
$labels['arialabelfileprops'] = 'Eigenschappen van bestand';
?>
