<?php
/**
 * Localizations for the Kolab Files plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_files/
 */
$labels['files'] = 'Pliki';
$labels['filepreview'] = 'Podgląd pliku';
$labels['saveas'] = 'Zapisz jako:';
$labels['create'] = 'Utwórz';
$labels['save'] = 'Zapisz';
$labels['cancel'] = 'Anuluj';
$labels['name'] = 'Nazwa';
$labels['mtime'] = 'Zmodyfikowano';
$labels['type'] = 'Typ';
$labels['get'] = 'Pobierz';
$labels['getfile'] = 'Pobierz plik';
$labels['rename'] = 'Zmień nazwę';
$labels['deletefile'] = 'Usuń plik(i)';
$labels['edit'] = 'Edytuj';
$labels['editfile'] = 'Edytuj plik';
$labels['save'] = 'Zapisz';
$labels['savefile'] = 'Zapisz plik';
$labels['printfile'] = 'Wydrukuj plik';
$labels['fileedit'] = 'Właściwości';
$labels['collection_audio'] = 'Audio';
$labels['collection_video'] = 'Video';
$labels['collection_image'] = 'Obrazy';
$labels['collection_document'] = 'Dokumenty';
$labels['authenticating'] = 'Uwierzytelnianie...';
$labels['foldercreating'] = 'Utwórz folder...';
$labels['folderupdating'] = 'Aktualizacja folderu...';
$labels['folderdeleting'] = 'Usuwanie folderu...';
$labels['folderauthtitle'] = 'Zaloguj do $title';
$labels['uploadsizeerror'] = 'Maksymalny rozmiar pliku ($size) przekroczony!';
$labels['fileskip'] = 'Pomiń';
$labels['fileskipall'] = 'Pomiń wszystko';
$labels['fileoverwrite'] = 'Nadpisz';
$labels['fileoverwriteall'] = 'Nadpisz wszystko';
$labels['storepasswords'] = 'zapamiętaj hasło';
$labels['arialabelfileprops'] = 'Właściwości';
?>
