<?php
/**
 * Localizations for the Kolab Files plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_files/
 */
$labels['files'] = 'Pliki';
$labels['filepreview'] = 'Podgląd pliku';
$labels['saveall'] = 'Zapisz wszystkie w chmurze...';
$labels['saveto'] = 'Zapisz w chmurze...';
$labels['saveas'] = 'Zapisz jako:';
$labels['create'] = 'Utwórz';
$labels['save'] = 'Zapisz';
$labels['cancel'] = 'Anuluj';
$labels['fromcloud'] = 'Z chmury...';
$labels['selectfiles'] = 'Wybierz pliki do załączenia...';
$labels['attachsel'] = 'Załącz wybrane';
$labels['foldercreate'] = 'Utwórz folder';
$labels['folderedit'] = 'Edytuj folder';
$labels['foldermount'] = 'Dodaj przestrzeń';
$labels['folderdelete'] = 'Usuń folder';
$labels['folderinside'] = 'Wstaw wewnątrz';
$labels['foldername'] = 'Nazwa folderu';
$labels['name'] = 'Nazwa';
$labels['mtime'] = 'Zmodyfikowano';
$labels['type'] = 'Typ';
$labels['upload'] = 'Wyślij';
$labels['uploadfile'] = 'Wyślij plik(i)';
$labels['get'] = 'Pobierz';
$labels['getfile'] = 'Pobierz plik';
$labels['view'] = 'Podgląd';
$labels['viewfile'] = 'Podgląd pliku';
$labels['rename'] = 'Zmień nazwę pliku';
$labels['deletefile'] = 'Usuń plik(i)';
$labels['edit'] = 'Edytuj';
$labels['editfile'] = 'Edytuj plik';
$labels['save'] = 'Zapisz';
$labels['savefile'] = 'Zapisz plik';
$labels['printfile'] = 'Drukuj plik';
$labels['fileedit'] = 'Właściwości pliku';
$labels['collection_audio'] = 'Audio';
$labels['collection_video'] = 'Video';
$labels['collection_image'] = 'Obrazy';
$labels['collection_document'] = 'Dokumenty';
$labels['uploading'] = 'Zapisywanie plików...';
$labels['attaching'] = 'Załączanie plików...';
$labels['authenticating'] = 'Uwierzytelnianie...';
$labels['foldercreating'] = 'Tworzenie folderu...';
$labels['folderupdating'] = 'Aktualizowanie folderu...';
$labels['foldermounting'] = 'Dodawanie przestrzeni zewnętrznej...';
$labels['folderdeleting'] = 'Usuwanie folderu...';
$labels['folderdeleteconfirm'] = 'Czy na pewno chcesz usunąć wybrany folder?';
$labels['folderdeletenotice'] = 'Folder został usunięty.';
$labels['folderupdatenotice'] = 'Folder został zaktualizowany.';
$labels['foldercreatenotice'] = 'Folder został utworzony.';
$labels['foldermountnotice'] = 'Przestrzeń dodana pomyślnie.';
$labels['saveallnotice'] = 'Pomyślnie zapisano $n plików.';
$labels['saveallerror'] = 'Nie można zapisać $n plików.';
$labels['attacherror'] = 'Nie udało się załączenie plików z chmury';
$labels['fileupdating'] = 'Aktualizowanie pliku...';
$labels['filemoving'] = 'Przenoszenie plików...';
$labels['filecopying'] = 'Kopiowanie plików...';
$labels['filedeleting'] = 'Usuwanie plików...';
$labels['filedeleteconfirm'] = 'Czy na pewno chcesz usunąć wybrane pliki?';
$labels['filedeletenotice'] = 'Plik(i) zostały usunięte.';
$labels['filemovenotice'] = 'Plik(i) zostały przeniesione.';
$labels['filecopynotice'] = 'Plik(i) zostały skopiowane.';
$labels['uploadsizeerror'] = 'Przekroczono maksymalny rozmiar pliku ($size)! ';
$labels['allfolders'] = 'szukaj we wszystkich folderach';
$labels['fileskip'] = 'Omiń';
$labels['fileskipall'] = 'Omiń wszystkie';
$labels['fileoverwrite'] = 'Nadpisz';
$labels['fileoverwriteall'] = 'Nadpisz wszystkie';
$labels['filemoveconfirm'] = 'Akcja ta nadpisze docelowy plik: <b>$file</b>.';
$labels['storepasswords'] = 'zapamiętaj hasło';
$labels['arialabelsearchform'] = 'Formularz wyszukiwania plików';
$labels['arialabelquicksearchbox'] = 'Fraza wyszukiwania';
$labels['arialabellistoptions'] = 'Opcje listy plików';
$labels['arialabelfolderoptions'] = 'Akcje folderów';
$labels['arialabelfileeditform'] = 'Formularz edycji pliku';
$labels['arialabelfoldercreateform'] = 'Formularz tworzenia folderów';
$labels['arialabelfoldereditform'] = 'Formularz edycji folderów';
$labels['arialabelfoldermountform'] = 'Formularz zewnętrznego przechowywania';
$labels['arialabelfolderlist'] = 'Wybór foldera/kolekcji';
$labels['arialabelfileselectdialog'] = 'Okno wyboru pliku';
$labels['arialabelattachmentoptions'] = 'Opcje zapisu załączników';
$labels['arialabelfilesavedialog'] = 'Okno zapisu plików';
$labels['arialabelfileprops'] = 'Właściwości pliku';
$labels['arialabelfilecontent'] = 'Treść pliku';
?>
