<?php
/**
 * Localizations for the Kolab Files plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_files/
 */
$labels['files'] = 'Файлы';
$labels['filepreview'] = 'Предпросмотр файла';
$labels['saveall'] = 'Сохранить всё в облако...';
$labels['saveto'] = 'Сохранить в облако...';
$labels['saveas'] = 'Сохранить как:';
$labels['create'] = 'Создать';
$labels['save'] = 'Сохранить';
$labels['cancel'] = 'Отмена';
$labels['fromcloud'] = 'Из облака...';
$labels['selectfiles'] = 'Выбрать файл(ы) для прикрепления...';
$labels['attachsel'] = 'Прикрепить выбранные';
$labels['foldercreate'] = 'Создать папку';
$labels['folderrename'] = 'Переименовать папку';
$labels['folderdelete'] = 'Удалить папку';
$labels['folderinside'] = 'Вставить внутрь';
$labels['foldername'] = 'Имя папки';
$labels['name'] = 'Имя';
$labels['mtime'] = 'Изменён';
$labels['type'] = 'Тип';
$labels['upload'] = 'Закачать';
$labels['uploadfile'] = 'Закачать файл(ы)';
$labels['get'] = 'Скачать';
$labels['getfile'] = 'Скачать файл';
$labels['view'] = 'Просмотреть';
$labels['viewfile'] = 'Просмотреть файл';
$labels['rename'] = 'Переименовать файл';
$labels['deletefile'] = 'Удалить файл(ы)';
$labels['edit'] = 'Редактировать';
$labels['editfile'] = 'Редактировать файл';
$labels['save'] = 'Сохранить';
$labels['savefile'] = 'Сохранить файл';
$labels['printfile'] = 'Распечатать файл';
$labels['fileedit'] = 'Свойства файла';
$labels['collection_audio'] = 'Аудио';
$labels['collection_video'] = 'Видео';
$labels['collection_image'] = 'Картинки';
$labels['collection_document'] = 'Документы';
$labels['uploading'] = 'Закачиваются файлы...';
$labels['attaching'] = 'Прикрепляются файлы...';
$labels['foldercreating'] = 'Создаётся папка...';
$labels['folderdeleting'] = 'Удаляется папка...';
$labels['folderdeleteconfirm'] = 'Вы уверены, что хотите удалить выбранную папку?';
$labels['folderdeletenotice'] = 'Папка удалена успешно.';
$labels['foldercreatenotice'] = 'Папка создана успешно.';
$labels['saveallnotice'] = 'Успешно сохранены $n файл(ов).';
$labels['saveallerror'] = 'Сохранение $n файл(ов) не удалось.';
$labels['attacherror'] = 'Не удалось прикрепить файл(ы) из облака';
$labels['fileupdating'] = 'Обновляется файл...';
$labels['filemoving'] = 'Перемещаются файлы...';
$labels['filecopying'] = 'Копируются файлы...';
$labels['filedeleting'] = 'Удаляются файлы...';
$labels['filedeleteconfirm'] = 'Вы уверены, что хотите удалить выбранные файлы?';
$labels['filedeletenotice'] = 'Файл(ы) удален(ы) успешно.';
$labels['filemovenotice'] = 'Файл(ы) перемещен(ы) успешно.';
$labels['filecopynotice'] = 'Файл(ы) скопирован(ы) успешно.';
$labels['uploadsizeerror'] = 'Максимальный размер файла ($size) превышен!';
$labels['allfolders'] = 'искать во всех папках';
$labels['fileskip'] = 'Пропустить';
$labels['fileskipall'] = 'Пропустить все';
$labels['fileoverwrite'] = 'Перезаписать';
$labels['fileoverwriteall'] = 'Перезаписать все';
$labels['filemoveconfirm'] = 'Это действие перезапишет файл: <b>$file</b>.';
$labels['arialabelsearchform'] = 'Искать файлы от';
$labels['arialabelquicksearchbox'] = 'Искать';
$labels['arialabellistoptions'] = 'Настройки списка файлов';
$labels['arialabelfolderoptions'] = 'Действия с папками';
$labels['arialabelfileeditform'] = 'Форма изменения файла';
$labels['arialabelfoldercreateform'] = 'Форма создания файла';
$labels['arialabelfolderlist'] = 'Выбор Папки/Коллекции';
$labels['arialabelfileselectdialog'] = 'Диалог выбора файлов';
$labels['arialabelattachmentoptions'] = 'Настройки сохранения вложений';
$labels['arialabelfilesavedialog'] = 'Диалог сохранения файлов';
$labels['arialabelfileprops'] = 'Свойства файла';
$labels['arialabelfilecontent'] = 'Содержимое файла';
?>
