<?php
/**
 * Localizations for the Kolab Files plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_files/
 */
$labels['files'] = 'Dokumenti';
$labels['save'] = 'Shrani';
$labels['cancel'] = 'Prekliči';
$labels['folderinside'] = 'Vstavi';
$labels['name'] = 'Ime';
$labels['edit'] = 'Uredi';
$labels['save'] = 'Shrani';
?>
