<?php
/**
 * Localizations for the Kolab Files plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_files/
 */
$labels['files'] = 'Filer';
$labels['filepreview'] = 'Förhandsgranska';
$labels['saveall'] = 'Spara samtliga till moln ...';
$labels['saveto'] = 'Spara till moln ...';
$labels['saveas'] = 'Spara som:';
$labels['create'] = 'Skapa';
$labels['save'] = 'Spara';
$labels['cancel'] = 'Avbryt';
$labels['fromcloud'] = 'Från moln ...';
$labels['selectfiles'] = 'Välj fil(er) att bifoga ...';
$labels['attachsel'] = 'Bifoga vald(a)';
$labels['foldercreate'] = 'Skapa mapp';
$labels['folderedit'] = 'Redigera mapp';
$labels['foldermount'] = 'Lägg till lagring';
$labels['folderdelete'] = 'Ta bort mapp';
$labels['folderinside'] = 'Infoga inuti';
$labels['foldername'] = 'Mappnamn';
$labels['name'] = 'Namn';
$labels['mtime'] = 'Ändrad';
$labels['type'] = 'Typ';
$labels['upload'] = 'Ladda upp';
$labels['uploadfile'] = 'Ladda upp fil(er)';
$labels['get'] = 'Ladda ner';
$labels['getfile'] = 'Ladda ner fil';
$labels['view'] = 'Visa';
$labels['viewfile'] = 'Visa fil';
$labels['rename'] = 'Byt namn på fil';
$labels['deletefile'] = 'Ta bort fil(er)';
$labels['edit'] = 'Redigera';
$labels['editfile'] = 'Redigera fil';
$labels['save'] = 'Spara';
$labels['savefile'] = 'Spara fil';
$labels['printfile'] = 'Skriv ut fil';
$labels['fileedit'] = 'Filegenskaper';
$labels['collection_audio'] = 'Audio';
$labels['collection_video'] = 'Video';
$labels['collection_image'] = 'Bilder';
$labels['collection_document'] = 'Dokument';
$labels['uploading'] = 'Laddar upp fil(er) ...';
$labels['attaching'] = 'Bifogar fil(er) ...';
$labels['authenticating'] = 'Autentiserar ...';
$labels['foldercreating'] = 'Skapar mapp ...';
$labels['folderupdating'] = 'Uppdaterar mapp ...';
$labels['foldermounting'] = 'Lägger till extern lagring ...';
$labels['folderdeleting'] = 'Tar bort mapp ...';
$labels['folderdeleteconfirm'] = 'Vill du verkligen ta bort vald mapp?';
$labels['folderdeletenotice'] = 'Mapp borttagen.';
$labels['folderupdatenotice'] = 'Mapp uppdaterad.';
$labels['foldercreatenotice'] = 'Mapp skapad.';
$labels['foldermountnotice'] = 'Lagring lades till.';
$labels['folderauthtitle'] = 'Logga in på';
$labels['saveallnotice'] = 'Sparade $n fil(er).';
$labels['saveallerror'] = 'Sparar $n fil(er) misslyckades.';
$labels['attacherror'] = 'Misslyckades att bifoga fil(er) från molnet';
$labels['fileupdating'] = 'Uppdaterar fil ...';
$labels['filemoving'] = 'Flyttar fil(er) ...';
$labels['filecopying'] = 'Kopierar fil(er) ...';
$labels['filedeleting'] = 'Tar bort fil(er) ...';
$labels['filedeleteconfirm'] = 'Vill du verkligen ta bort valda filer?';
$labels['filedeletenotice'] = 'Fil(er) borttagna.';
$labels['filemovenotice'] = 'Fil(er) flyttade.';
$labels['filecopynotice'] = 'Fil(er) kopierade.';
$labels['uploadsizeerror'] = 'Maximal filstorlek ($size) överskriden!';
$labels['allfolders'] = 'sök i alla mappar';
$labels['fileskip'] = 'Hoppa över';
$labels['fileskipall'] = 'Hoppa över alla';
$labels['fileoverwrite'] = 'Skriv över';
$labels['fileoverwriteall'] = 'Skriv över alla';
$labels['filemoveconfirm'] = 'Denna åtgärd kommer att skriva över målfilen: <b>$file</b>.';
$labels['storepasswords'] = 'kom ihåg lösenord';
$labels['storepasswordsdesc'] = 'Lagrade lösenord kommer att krypteras. Aktivera det här om du inte vill bli tillfrågad om lösenordet vid varje inloggning eller om du vill att denna lagring ska vara tillgänglig via WebDAV.';
$labels['arialabelsearchform'] = 'Sökformulär för filer';
$labels['arialabelquicksearchbox'] = 'Sökinmatning';
$labels['arialabellistoptions'] = 'Fillistningsval';
$labels['arialabelfolderoptions'] = 'Mappåtgärd';
$labels['arialabelfileeditform'] = 'Filredigeringsformulär';
$labels['arialabelfoldercreateform'] = 'Formulär för skapa-mapp';
$labels['arialabelfoldereditform'] = 'Formulär för mappredigering';
$labels['arialabelfoldermountform'] = 'Formulär för extern lagring';
$labels['arialabelfolderauthform'] = 'Autentiseringsformulär för extern lagring';
$labels['arialabelfolderlist'] = 'Mapp-/samlingsurval';
$labels['arialabelfileselectdialog'] = 'Filurvalsdialog';
$labels['arialabelattachmentoptions'] = 'Alternativ för att spara bilagor';
$labels['arialabelfilesavedialog'] = 'Dialog för atta spara fil(er)';
$labels['arialabelfileprops'] = 'Filegenskaper';
$labels['arialabelfilecontent'] = 'Filinnehåll';
?>
