<?php
/**
 * Localizations for the Kolab Files plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_files/
 */
$labels['files'] = 'Filer';
$labels['filepreview'] = 'Förhandsgranska';
$labels['saveall'] = 'Spara samtliga till moln ...';
$labels['saveto'] = 'Spara till moln ...';
$labels['saveas'] = 'Spara som:';
$labels['create'] = 'Skapa';
$labels['save'] = 'Spara';
$labels['cancel'] = 'Avbryt';
$labels['fromcloud'] = 'Från moln ...';
$labels['selectfiles'] = 'Välj fil(er) att bifoga ...';
$labels['foldercreate'] = 'Skapa mapp';
$labels['folderedit'] = 'Redigera mapp';
$labels['foldermount'] = 'Lägg till lagring';
$labels['folderdelete'] = 'Ta bort mapp';
$labels['folderinside'] = 'Infoga inuti';
$labels['foldername'] = 'Mappnamn';
$labels['name'] = 'Namn';
$labels['mtime'] = 'Ändrad';
$labels['type'] = 'Typ';
$labels['upload'] = 'Ladda upp';
$labels['uploadfile'] = 'Ladda upp fil(er)';
$labels['get'] = 'Ladda ner';
$labels['getfile'] = 'Ladda ner fil';
$labels['view'] = 'Visa';
$labels['viewfile'] = 'Visa fil';
$labels['rename'] = 'Byt namn på fil';
$labels['deletefile'] = 'Ta bort fil(er)';
$labels['edit'] = 'Redigera';
$labels['editfile'] = 'Redigera fil';
$labels['save'] = 'Spara';
$labels['savefile'] = 'Spara fil';
$labels['printfile'] = 'Skriv ut fil';
$labels['fileedit'] = 'Filegenskaper';
$labels['collection_audio'] = 'Audio';
$labels['collection_video'] = 'Video';
$labels['collection_image'] = 'Bilder';
$labels['collection_document'] = 'Dokument';
$labels['authenticating'] = 'Autentiserar ...';
$labels['folderauthtitle'] = 'Logga in på';
$labels['fileskip'] = 'Hoppa över';
$labels['fileskipall'] = 'Hoppa över alla';
$labels['fileoverwrite'] = 'Skriv över';
$labels['fileoverwriteall'] = 'Skriv över alla';
$labels['filemoveconfirm'] = 'Denna åtgärd kommer att skriva över målfilen: <b>$file</b>.';
$labels['storepasswords'] = 'kom ihåg lösenord';
$labels['storepasswordsdesc'] = 'Lagrade lösenord kommer att krypteras. Aktivera det här om du inte vill bli tillfrågad om lösenordet vid varje inloggning eller om du vill att denna lagring ska vara tillgänglig via WebDAV.';
$labels['arialabelfileprops'] = 'Filegenskaper';
?>
