<?php
/**
 * Localizations for the Kolab Files plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_files/
 */
$labels['files'] = 'Файли';
$labels['create'] = 'Створити';
$labels['save'] = 'Зберегти';
$labels['cancel'] = 'Відмінити';
$labels['folderinside'] = 'Вставити всередину';
$labels['name'] = 'Назва';
$labels['edit'] = 'Редагувати';
$labels['save'] = 'Зберегти';
?>
