<?php
/**
 * Localizations for the Kolab Files plugin
 *
 * Copyright (C) 2014, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_files/
 */
$labels['files'] = '文件';
$labels['filepreview'] = '文件预览';
$labels['create'] = '创建';
$labels['save'] = '保存';
$labels['cancel'] = '取消';
$labels['foldercreate'] = '创建文件夹';
$labels['foldername'] = '文件夹名';
$labels['name'] = '名称';
$labels['type'] = '类型';
$labels['upload'] = '上传';
$labels['get'] = '下载';
$labels['edit'] = '编辑';
$labels['save'] = '保存';
$labels['collection_audio'] = '声音';
$labels['collection_video'] = '视频';
$labels['collection_image'] = '图片';
$labels['collection_document'] = '文档';
$labels['fileskip'] = '略过';
$labels['fileskipall'] = '忽略全部';
$labels['storepasswords'] = '记住密码';
?>
