<?php

$labels = array();

// itip related labels
$labels['itipinvitation'] = 'Invitation to';
$labels['itipupdate'] = 'Update of';
$labels['itipcancellation'] = 'Отказано:';
$labels['itipreply'] = 'Отговор на';
$labels['itipaccepted'] = 'Приемане';
$labels['itiptentative'] = 'Може би';
$labels['itipdeclined'] = 'Отхвърляне';

$labels['itipsubjectaccepted'] = '"$title" беше прието от $name';
$labels['itipsubjectdeclined'] = '"$title" беше отхвърлено от $name';

$labels['importtocalendar'] = 'Запазване в моя календар';
$labels['removefromcalendar'] = 'Премахване от моя календар';
$labels['updateattendeestatus'] = 'Подновяване на статусът на участника';
$labels['acceptinvitation'] = 'Приемате ли тази покана?';
$labels['youhaveaccepted'] = 'Вие сте приели тази покана';

$labels['savingdata'] = 'Запазване на данни...';