<?php

$labels = array();

// itip related labels
$labels['itipinvitation'] = 'Invito a';
$labels['itipupdate'] = 'Aggiornamento di';
$labels['itipcancellation'] = 'Annullato:';
$labels['itipreply'] = 'Rispondi a';
$labels['itipaccepted'] = 'Accetta';
$labels['itiptentative'] = 'Forse';
$labels['itipdeclined'] = 'Rifiuta';

$labels['itipsubjectaccepted'] = '"$title" è stato accettato da $name';
$labels['itipsubjecttentative'] = '"$title" è stato accettato con riserva da $name';
$labels['itipsubjectdeclined'] = '"$title" è stato rifiutato da $name';

$labels['importtocalendar'] = 'Salva nel mio calendario';
$labels['removefromcalendar'] = 'Rimuovi dal mio calendario';
$labels['updateattendeestatus'] = 'Aggiorna lo stato dei partecipanti';
$labels['acceptinvitation'] = 'Accetti questo invito?';
$labels['youhaveaccepted'] = 'Hai accettato questo invito';
$labels['youhavetentative'] = 'Hai accettato con riserva questo invito';
$labels['youhavedeclined'] = 'Hai rifiutato questo invito';

$labels['savingdata'] = 'Salvataggio dati...';

?>