<?php

$labels = array();

$labels['alarmemail'] = 'Verzend E-mail';
$labels['alarmdisplay'] = 'Bericht weergeven';
$labels['alarmdisplayoption'] = 'Bericht';
$labels['alarmemailoption'] = 'E-mail';
$labels['alarmat'] = 'op $datetime';
$labels['trigger@'] = 'op datum';
$labels['trigger-M'] = 'minuten voor';
$labels['trigger-H'] = 'uren voor';
$labels['trigger-D'] = 'dagen voor';
$labels['trigger+M'] = 'minuten na';
$labels['trigger+H'] = 'uren na';
$labels['trigger+D'] = 'dagen na';
$labels['addalarm'] = 'alarm toevoegen';

$labels['alarmtitle'] = 'Aankomende evenementen';
$labels['dismissall'] = 'Dismiss all';
$labels['dismiss'] = 'Dismiss';
$labels['snooze'] = 'Snooze';
$labels['repeatinmin'] = 'Herhaal over $min minuten';
$labels['repeatinhr'] = 'Herhaal over 1 uur';
$labels['repeatinhrs'] = 'Herhaal over $hrs uur';
$labels['repeattomorrow'] = 'Herhaal morgen';
$labels['repeatinweek'] = 'Herhaal over een week';

$labels['showmore'] = 'Toon meer...';

// itip related labels
$labels['itipinvitation'] = 'Uitnodiging voor';
$labels['itipupdate'] = 'Update van';
$labels['itipcancellation'] = 'Afgelast:';
$labels['itipreply'] = 'Reply to';
$labels['itipaccepted'] = 'Accepteer';
$labels['itiptentative'] = 'Misschien';
$labels['itipdeclined'] = 'Afwijzen';

$labels['itipsubjectaccepted'] = '"$title" is geaccepteerd door $name';
$labels['itipsubjecttentative'] = '"$title" has been tentatively accepted by $name';
$labels['itipsubjectdeclined'] = '"$title" has been declined by $name';

$labels['importtocalendar'] = 'Bewaar in mijn kalender';
$labels['removefromcalendar'] = 'Verwijder van mijn kalender';
$labels['updateattendeestatus'] = 'Update status van deelnemer';
$labels['acceptinvitation'] = 'Accepteer je deze uitnodiging?';
$labels['youhaveaccepted'] = 'Je hebt de uitnodiging geaccepteerd';
$labels['youhavetentative'] = 'You have tentatively accepted this invitation';
$labels['youhavedeclined'] = 'Je hebt deze uitnodiging afgewezen';
$labels['notanattendee'] = 'You\'re not listed as an attendee of this event';

$labels['savingdata'] = 'Data wordt opgeslagen...';
