<?php
/**
 * Localizations for the Kolab 2-Factor-Auth plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_2fa/
 */
$labels['created'] = 'Luotu';
$labels['remove'] = 'Poista';
$labels['continue'] = 'Jatka';
$labels['yes'] = 'kyllä';
$labels['no'] = 'ei';
$labels['label'] = 'Nimi';
$labels['verifycodeexplainhotp'] = $labels['verifycodeexplaintotp'];
$labels['enterhighsecurity'] = 'Vahvista';
