<?php
/**
 * Localizations for the Kolab 2-Factor-Auth plugin
 *
 * Copyright (C) 2015, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_2fa/
 */
$labels['created'] = 'Создана';
$labels['remove'] = 'Убрать';
$labels['continue'] = 'Продолжить';
$labels['yes'] = 'да';
$labels['no'] = 'нет';
$labels['label'] = 'Имя';
$labels['verifycodeexplainhotp'] = $labels['verifycodeexplaintotp'];
$labels['enterhighsecurity'] = 'Подтвердить';
