<?php
$labels['tabtitle'] = 'Activesync';
$labels['devices'] = 'Zařízení';
$labels['devicealias'] = 'Název zařízení';
$labels['synchronize'] = 'Synchronizovat';
$labels['syncsettings'] = 'Nastavení synchronizace';
$labels['deviceconfig'] = 'Konfigurace zařízení';
$labels['folderstosync'] = 'Složky k synchronizaci';
$labels['mail'] = 'E-mail';
$labels['contact'] = 'Adresáře';
$labels['event'] = 'Kalendáře';
$labels['task'] = 'Úkoly';
$labels['note'] = 'Poznámky';
$labels['configuration'] = 'Nastavení';
$labels['deletedevice'] = 'Smazat zařízení';
$labels['nodevices'] = 'Momentálně tu nejsou žádná registrovaná zařízení.<br/><br/>Pro registraci zařízení, nejprve jej prosím připojte k serveru za pomocí  <a href="http://wiki.kolab.org/Setup_ActiveSync">instrukcí na stránce Wiki</a>. Poté zde bude k dispozici zařízení ke konfiguraci.';
$labels['savingdata'] = 'Ukládám data...';
$labels['savingerror'] = 'Nepodařilo se uložit konfiguraci';
$labels['devicedeleteconfirm'] = 'Opravdu chcete smazat konfiguraci pro toto zařízení?';
$labels['successfullydeleted'] = 'Konfigurace zařízení byla úspěšně odebrána';
$labels['devicenotfound'] = 'Nelze přečíst konfigurace zařízení';
$labels['devicetype'] = 'Typ zařízení';
$labels['acsversion'] = 'Verze protokolu';
$labels['friendlyname'] = 'Zobrazovaný název';
$labels['os'] = 'Operační systém';
$labels['oslanguage'] = 'Jazyk OS';
$labels['phonenumber'] = 'Telefonní číslo';
?>
