<?php
$labels['devices'] = 'Seadmed';
$labels['devicealias'] = 'Seadme nimi';
$labels['synchronize'] = 'Sünkrooni';
$labels['deviceconfig'] = 'Seadme häälestamine';
$labels['folderstosync'] = 'Sünkroonitavad kaustad';
$labels['mail'] = 'E-post';
$labels['contact'] = 'Kontaktid';
$labels['event'] = 'Kalendrid';
$labels['task'] = 'Ülesanded';
$labels['note'] = 'Märkmed';
$labels['configuration'] = 'Seadistamine';
$labels['deletedevice'] = 'Kustuta seade';
$labels['savingdata'] = 'Andmete salvestamine...';
$labels['devicetype'] = 'Seadme liik';
$labels['friendlyname'] = 'Inimsõbralik nimi';
$labels['os'] = 'Operatsioonisüsteem';
$labels['oslanguage'] = 'OS-i keel';
$labels['phonenumber'] = 'Telefoninumber';
?>
