<?php
$labels['tabtitle'] = 'Activesync';
$labels['devices'] = 'Périphériques';
$labels['devicealias'] = 'Nom du Périphérique';
$labels['synchronize'] = 'Synchroniser';
$labels['withalarms'] = 'Avec alarmes';
$labels['syncsettings'] = 'Paramètres de synchronisation';
$labels['folderstosync'] = 'Dossiers à synchroniser';
$labels['mail'] = 'Adresse de messagerie';
$labels['contact'] = 'Carnet d\'adresses';
$labels['event'] = 'Agendas';
$labels['task'] = 'Tâches';
$labels['note'] = 'Notes';
$labels['configuration'] = 'Configuration';
$labels['deletedevice'] = 'Supprimer ce périphérique';
$labels['savingdata'] = 'Enregistrer...';
$labels['savingerror'] = 'Échec de l\'enregistrement de la configuration';
$labels['notsupported'] = 'Votre serveur ne supporte pas les métadonnées ou les annotations';
$labels['devicedeleteconfirm'] = 'Voulez-vous vraiment supprimer la configuration de ce périphérique?';
$labels['successfullydeleted'] = 'La configuration de ce périphérique a été supprimée';
$labels['devicenotfound'] = 'Impossible de lire la configuration du périphérique';
$labels['phonenumber'] = 'Numéro de téléphone';
?>
