<?php
$labels['tabtitle'] = 'アクティブシンク';
$labels['devices'] = '機器';
$labels['devicealias'] = '機器名';
$labels['synchronize'] = '同期';
$labels['withalarms'] = 'アラーム付';
$labels['syncsettings'] = '同期設定';
$labels['folderstosync'] = '同期するフォルダ';
$labels['contact'] = 'アドレス帳';
$labels['event'] = 'カレンダー';
$labels['task'] = 'タスク';
$labels['note'] = 'ノート';
$labels['configuration'] = '設定';
$labels['deletedevice'] = '機器の削除';
$labels['savingdata'] = 'データを保存中…';
$labels['savingerror'] = '設定の保存に失敗しました';
$labels['notsupported'] = 'サーバはmetadata/annotionsをサポートしていません';
$labels['devicedeleteconfirm'] = '本当にこのデバイスの設定を削除しますか？';
$labels['successfullydeleted'] = 'デヴァイスの削除に成功しました';
$labels['devicenotfound'] = 'デヴァイスの設定を読込めません';
$labels['phonenumber'] = '電話番号';
?>
