<?php
$labels['tabtitle'] = 'Activesync';
$labels['syncmode'] = 'Synchronizatie modus';
$labels['modeauto'] = 'Stel automatisch vast';
$labels['modeflat'] = 'Forceer vlakke modus';
$labels['modefolder'] = 'Forceer mappen modus';
$labels['synchronize'] = 'Synchronizeren';
$labels['withalarms'] = 'Met alarmen';
$labels['syncsettings'] = 'Synchronizatie instellingen';
$labels['mail'] = 'Email';
$labels['contact'] = 'Adresboeken';
$labels['event'] = 'Kalenders';
$labels['task'] = 'Taken';
$labels['note'] = 'Notities';
$labels['configuration'] = 'Configuratie';
$labels['laxpiclabel'] = 'Sta PNG en GIF plaatjes toe';
$labels['savingdata'] = 'Data wordt opgeslagen...';
?>
