<?php

$labels['tabtitle'] = 'Activesync';
$labels['activesynctitle'] = 'Beheer Activesync-apparaten';
$labels['devices'] = 'Apparaten';
$labels['devicealias'] = 'Apparaat naam';
$labels['synchronize'] = 'Synchronizeren';
$labels['withalarms'] = 'Met alarmen';
$labels['syncsettings'] = 'Synchronizatie instellingen';
$labels['deviceconfig'] = 'Apparaat configuratie';
$labels['folderstosync'] = 'Mappen voor synchronisatie';
$labels['mail'] = 'Email';
$labels['contact'] = 'Adresboeken';
$labels['event'] = 'Kalenders';
$labels['task'] = 'Taken';
$labels['note'] = 'Notities';
$labels['configuration'] = 'Configuratie';
$labels['deletedevice'] = 'Verwijder apparaat';
$labels['nodevices'] = 'There are currently no devices registered.<br/><br/>In order to register a device, please connect it to the server first, using instructions from <a href="$url" target="_blank">this page</a>. Afterwards the device should become available for configuration here.';
$labels['savingdata'] = 'Data wordt opgeslagen...';
$labels['savingerror'] = 'Fout in opslaan van configuratie';
$labels['notsupported'] = 'Uw server ondersteunt geen metadata/annotaties';
$labels['devicedeleteconfirm'] = 'Wilt u de configuratie voor dit apparaat echt verwijderen?';
$labels['successfullydeleted'] = 'Het apparaat is succesvol verwijderd';
$labels['devicenotfound'] = 'Lezen van apparaat configuratie mislukt';
$labels['devicetype'] = 'Apparaat type';
$labels['acsversion'] = 'Protocol versie';
$labels['useragent'] = 'User agent';
$labels['friendlyname'] = 'Weergave naam';
$labels['os'] = 'Besturingssysteem';
$labels['oslanguage'] = 'Taal besturingssysteem';
$labels['phonenumber'] = 'Telefoonnummer';
$labels['arialabeldeviceframe'] = 'Device synchronization settings form';

?>
