<?php
$labels['tabtitle'] = 'ActiveSync';
$labels['devices'] = 'Urządzenia';
$labels['devicealias'] = 'Nazwa urządzenia';
$labels['syncmode'] = 'Tryb synchronizacji';
$labels['modeauto'] = 'Ustaw automatycznie';
$labels['modeflat'] = 'Wymuszaj tryb "płaski"';
$labels['modefolder'] = 'Wymuszaj tryb folderów';
$labels['synchronize'] = 'Synchronizuj';
$labels['withalarms'] = 'Z alarmami';
$labels['syncsettings'] = 'Ustawienia synchronizacji';
$labels['deviceconfig'] = 'Konfiguracja urządzenia';
$labels['folderstosync'] = 'Foldery do synchronizacji';
$labels['mail'] = 'Poczta';
$labels['contact'] = 'Książki adresowe';
$labels['event'] = 'Kalendarze';
$labels['task'] = 'Zadania';
$labels['note'] = 'Notatki';
$labels['configuration'] = 'Konfiguracja';
$labels['deletedevice'] = 'Usuń urządzenie';
$labels['imageformat'] = 'Format obrazków';
$labels['savingdata'] = 'Zapisuję dane...';
$labels['savingerror'] = 'Nie udało się zapisać konfiguracji';
$labels['notsupported'] = 'Twój serwer nie obsługuje rozszerzenia metadata/annotations';
$labels['devicedeleteconfirm'] = 'Czy na pewno chcesz usunąć konfigurację tego urządzenia?';
$labels['successfullydeleted'] = 'Konfiguracja urządzenie została usunięta';
$labels['devicenotfound'] = 'Nie można odczytać konfiguracji urządzenia';
?>
